//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UITableViewController.h>

#import <SensorKitUI/SRAuthorizationCellDelegate-Protocol.h>
#import <SensorKitUI/UITableViewDelegatePrivate-Protocol.h>

@class NSArray, NSBundle, NSMutableDictionary, NSString, SRAuthorizationStore;

@interface SRAuthorizationCategoryGroupViewController : UITableViewController <SRAuthorizationCellDelegate, UITableViewDelegatePrivate>
{
    NSBundle *_appBundle;
    NSMutableDictionary *_readerAuthState;
    NSMutableDictionary *_writerAuthState;
    SRAuthorizationStore *_authStore;
    NSArray *_sortedReaderAuthorizationServices;
    NSArray *_sortedWriterAuthorizationServices;
}

@property(retain, nonatomic) NSArray *sortedWriterAuthorizationServices; // @synthesize sortedWriterAuthorizationServices=_sortedWriterAuthorizationServices;
@property(retain, nonatomic) NSArray *sortedReaderAuthorizationServices; // @synthesize sortedReaderAuthorizationServices=_sortedReaderAuthorizationServices;
@property(retain) SRAuthorizationStore *authStore; // @synthesize authStore=_authStore;
@property(retain, nonatomic) NSMutableDictionary *writerAuthState; // @synthesize writerAuthState=_writerAuthState;
@property(retain, nonatomic) NSMutableDictionary *readerAuthState; // @synthesize readerAuthState=_readerAuthState;
@property(retain, nonatomic) NSBundle *appBundle; // @synthesize appBundle=_appBundle;
- (void)openPrivacy;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)confirmAuthChangeForService:(id)arg1 value:(_Bool)arg2 indexPath:(id)arg3 setOverride:(_Bool)arg4;
- (void)authorizationSwitchToggledWithValue:(_Bool)arg1 indexPath:(id)arg2;
- (id)serviceFromIndexPath:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (_Bool)indexPathIsInWriterSection:(id)arg1;
- (long long)readerAuthSectionStart;
- (long long)writerAuthSectionStart;
- (long long)usageSectionStart;
- (void)dealloc;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

