//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface PHAPhotoLibraryList : NSObject
{
    NSMutableDictionary *_photoLibrariesByPath;
}

@property(retain) NSMutableDictionary *photoLibrariesByPath; // @synthesize photoLibrariesByPath=_photoLibrariesByPath;
- (void).cxx_destruct;
- (void)enumeratePhotoLibrariesWithBlock:(CDUnknownBlockType)arg1;
- (void)removeAllPhotoLibraries;
- (void)removePhotoLibraryAtURL:(id)arg1;
- (void)addPhotoLibraryAtURL:(id)arg1;
- (void)saveToPersistentStorage;
@property(readonly) unsigned long long count;
- (id)init;

@end

