//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSData, NSDictionary;

@interface PHAPrivateFederatedLearningRunnerResponse : NSObject
{
    NSData *_dataPackage;
    NSDictionary *_trainingMetrics;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *trainingMetrics; // @synthesize trainingMetrics=_trainingMetrics;
@property(retain, nonatomic) NSData *dataPackage; // @synthesize dataPackage=_dataPackage;
- (id)initWithDataPackage:(id)arg1 layersToTrain:(id)arg2 trainingLossesPerEpoch:(id)arg3 trainingAccuraciesPerEpoch:(id)arg4;

@end

