//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IKViewElement, NSDictionary;

@interface IKServiceContext : NSObject
{
    NSDictionary *_contextDictionary;
    IKViewElement *_element;
}

@property(readonly, nonatomic) IKViewElement *element; // @synthesize element=_element;
@property(readonly, copy, nonatomic) NSDictionary *contextDictionary; // @synthesize contextDictionary=_contextDictionary;
- (void).cxx_destruct;
- (id)initWithContextDictionary:(id)arg1 element:(id)arg2;

@end

