//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <PreferencesUI/PSSpecifierGroup-Protocol.h>

@class NSString, PSListController, PSSpecifier;

@interface PSUICellularDataPlanListGroup : NSObject <PSSpecifierGroup>
{
    PSSpecifier *_groupSpecifier;
    PSListController *_listController;
}

@property(nonatomic) __weak PSListController *listController; // @synthesize listController=_listController;
@property(nonatomic) __weak PSSpecifier *groupSpecifier; // @synthesize groupSpecifier=_groupSpecifier;
- (void).cxx_destruct;
- (void)selectPlanWithSpecifier:(id)arg1;
- (void)addNewPlanPressed:(id)arg1;
- (void)listController:(id)arg1 didSelectSpecifier:(id)arg2;
- (id)specifiers;
- (id)initWithListController:(id)arg1 groupSpecifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

