//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CSContentCutoutBoundsCalculator : NSObject
{
}

+ (struct CGRect)_normalizedContentCutoutForScreenBounds:(struct CGRect)arg1 contentBoundingRect:(struct CGRect)arg2;
+ (struct CGRect)_screenBoundsForPortrait:(_Bool)arg1;
+ (struct CGRect)_contentCutoutBoundsForPortrait:(_Bool)arg1 forModal:(_Bool)arg2;
+ (struct CGRect)modalNormalizedContentCutoutBoundsForOrientation:(long long)arg1;
+ (struct CGRect)modalContentCutoutBoundsForOrientation:(long long)arg1;
+ (struct CGRect)modalContentCutoutBoundsForInterfaceOrientation:(long long)arg1;
+ (struct CGRect)normalizedContentCutoutBoundsForOrientation:(long long)arg1;
+ (struct CGRect)contentCutoutBoundsForOrientation:(long long)arg1;
+ (struct CGRect)contentCutoutBoundsForInterfaceOrientation:(long long)arg1;

@end

