//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewListCell.h>

#import <HomeUI/HUDisableableCellProtocol-Protocol.h>
#import <HomeUI/HUEditableTextCellProtocol-Protocol.h>

@class NSArray, NSString, UIListContentView, UITextField;

@interface HUEditableTextCollectionListCell : UICollectionViewListCell <HUEditableTextCellProtocol, HUDisableableCellProtocol>
{
    _Bool _disabled;
    UITextField *_textField;
    UIListContentView *_listContentView;
    NSArray *_textFieldConstraints;
    NSArray *_listContentViewConstraints;
}

+ (_Bool)requiresConstraintBasedLayout;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *listContentViewConstraints; // @synthesize listContentViewConstraints=_listContentViewConstraints;
@property(retain, nonatomic) NSArray *textFieldConstraints; // @synthesize textFieldConstraints=_textFieldConstraints;
@property(retain, nonatomic) UIListContentView *listContentView; // @synthesize listContentView=_listContentView;
@property(nonatomic, getter=isDisabled) _Bool disabled; // @synthesize disabled=_disabled;
@property(readonly, nonatomic) UITextField *textField; // @synthesize textField=_textField;
- (void)updateConstraints;
- (void)setSelected:(_Bool)arg1;
- (void)setContentConfiguration:(id)arg1;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

