//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Home/HFItemModule.h>

@class HFItem, HFStaticItemProvider, HMHome, HUPrimaryUserItemProvider;
@protocol HFMediaProfileContainer;

@interface HUPrimaryUserSettingsItemModule : HFItemModule
{
    HMHome *_home;
    id <HFMediaProfileContainer> _mediaProfileContainer;
    HFItem *_primaryUserSettingsHeaderItem;
    HFItem *_homePodAccountSelectionItem;
    HUPrimaryUserItemProvider *_primaryUserItemProvider;
    HFStaticItemProvider *_staticItemProvider;
}

+ (CDUnknownBlockType)_userItemComparator;
- (void).cxx_destruct;
@property(retain, nonatomic) HFStaticItemProvider *staticItemProvider; // @synthesize staticItemProvider=_staticItemProvider;
@property(retain, nonatomic) HUPrimaryUserItemProvider *primaryUserItemProvider; // @synthesize primaryUserItemProvider=_primaryUserItemProvider;
@property(retain, nonatomic) HFItem *homePodAccountSelectionItem; // @synthesize homePodAccountSelectionItem=_homePodAccountSelectionItem;
@property(retain, nonatomic) HFItem *primaryUserSettingsHeaderItem; // @synthesize primaryUserSettingsHeaderItem=_primaryUserSettingsHeaderItem;
@property(readonly, nonatomic) id <HFMediaProfileContainer> mediaProfileContainer; // @synthesize mediaProfileContainer=_mediaProfileContainer;
@property(readonly, nonatomic) HMHome *home; // @synthesize home=_home;
- (id)_updatePrimaryUserSelectionType:(unsigned long long)arg1 user:(id)arg2;
- (void)_buildItemProviders;
- (id)updatePrimaryUserSelectionType:(unsigned long long)arg1 user:(id)arg2;
- (id)buildSectionsWithDisplayedItems:(id)arg1;
- (id)itemProviders;
- (id)initWithItemUpdater:(id)arg1 home:(id)arg2 mediaProfileContainer:(id)arg3;

@end

