//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewCell.h>

@class NSString, UIActivityIndicatorView, UIImage, UIImageView;

@interface HUWallpaperPhotoCell : UICollectionViewCell
{
    _Bool _busy;
    NSString *_assetIdentifier;
    UIImageView *_imageView;
    UIActivityIndicatorView *_spinnerView;
}

@property(retain, nonatomic) UIActivityIndicatorView *spinnerView; // @synthesize spinnerView=_spinnerView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) _Bool busy; // @synthesize busy=_busy;
@property(copy, nonatomic) NSString *assetIdentifier; // @synthesize assetIdentifier=_assetIdentifier;
- (void).cxx_destruct;
@property(copy, nonatomic) UIImage *image;
- (void)setHighlighted:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

