//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <NanoPassKit/NSObject-Protocol.h>

@class NPKPaymentProvisioningFlowController, NPKPaymentProvisioningFlowStepContext;

@protocol NPKPaymentProvisioningFlowControllerDelegate <NSObject>
- (void)paymentProvisioningFlowController:(NPKPaymentProvisioningFlowController *)arg1 didTransitionFromStep:(unsigned long long)arg2 toStep:(unsigned long long)arg3 withContext:(NPKPaymentProvisioningFlowStepContext *)arg4;
@end

