//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CLKUIMetalResourcePool, NSBundle;
@protocol MTLDevice, MTLTexture;

@interface NUNIRenderer : NSObject
{
    id <MTLDevice> _mtlDevice;
    NSBundle *_bundle;
    struct NUNIRendererResources _resources;
    unsigned long long _viewMtlPixelFormat;
    struct _NUNIGeometryRange _octahedronGeomRange;
    struct _NUNIGeometryRange _quadGeomRange;
    union float4x4 _globeLinesMatrix;
    CLKUIMetalResourcePool *_globeLineTextureResourcePool;
    id <MTLTexture> _globeLinesCurrentTexture;
    struct NUNIRendererState _state;
}

+ (void)_deallocInstanceWithPixelFormat:(unsigned long long)arg1;
+ (id)sharedInstanceWithPixelFormat:(unsigned long long)arg1;
- (void).cxx_destruct;
- (void)_asyncDeallocInstance;
- (void)_initPrograms;
- (void)_createPipelineForProgramType:(unsigned long long)arg1 fromLibrary:(id)arg2 librarySPI:(id)arg3;
- (void)_updateStateWithScene:(id)arg1 viewport:(struct NUNIViewport)arg2 resources:(id)arg3;
- (void)renderOffscreenWithScene:(id)arg1 viewport:(struct NUNIViewport)arg2 resources:(id)arg3 commandBuffer:(id)arg4;
- (void)renderWithScene:(id)arg1 viewport:(struct NUNIViewport)arg2 resources:(id)arg3 encoder:(id)arg4;
- (void)drawSpriteWithEncoder:(id)arg1 state:(const struct NUNIRendererState *)arg2 spheroid:(id)arg3 resources:(id)arg4;
- (id)_renderGlobeLinesWithCommandBuffer:(id)arg1 state:(const struct NUNIRendererState *)arg2 spheroid:(id)arg3 resources:(id)arg4;
- (void)drawOffscreen3DWithCommandBuffer:(id)arg1 state:(const struct NUNIRendererState *)arg2 spheroid:(id)arg3 resources:(id)arg4;
- (void)draw3DWithEncoder:(id)arg1 state:(const struct NUNIRendererState *)arg2 spheroid:(id)arg3 resources:(id)arg4;
- (void)bindAssetArt:(unsigned long long)arg1 withEncoder:(id)arg2 resources:(id)arg3 toSlot:(unsigned long long)arg4;
- (void)_initHemi;
- (void)_initDepthStencilState;
- (void)dealloc;
- (id)initWithPixelFormat:(unsigned long long)arg1;

@end

