//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreData/NSManagedObject.h>

@class NSDate;

@interface PARSafariSession : NSManagedObject
{
}

+ (id)fetchRequest;

// Remaining properties
@property(nonatomic) short goToSite; // @dynamic goToSite;
@property(nonatomic) short localGoto; // @dynamic localGoto;
@property(nonatomic) short localTap; // @dynamic localTap;
@property(nonatomic) short other; // @dynamic other;
@property(nonatomic) short parsecGoto; // @dynamic parsecGoto;
@property(nonatomic) short parsecTap; // @dynamic parsecTap;
@property(nonatomic) short thirdPartyCompletionOrRecentSearch; // @dynamic thirdPartyCompletionOrRecentSearch;
@property(nonatomic) short thirdPartyGoto; // @dynamic thirdPartyGoto;
@property(nonatomic) short thirdPartyTap; // @dynamic thirdPartyTap;
@property(copy, nonatomic) NSDate *timestamp; // @dynamic timestamp;

@end

