//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ICQLink, NSDictionary, NSString;

@interface _ICQButtonSpecification : NSObject
{
    NSDictionary *_serverDict;
    ICQLink *_buttonLink;
    NSString *_buttonFormat;
    NSString *_textFormat;
    NSString *_linkFormat;
    NSDictionary *_linkForBundleIdentifier;
}

+ (id)buttonSpecificationSampleForLevel:(long long)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *linkForBundleIdentifier; // @synthesize linkForBundleIdentifier=_linkForBundleIdentifier;
@property(readonly, nonatomic) NSString *linkFormat; // @synthesize linkFormat=_linkFormat;
@property(readonly, nonatomic) NSString *textFormat; // @synthesize textFormat=_textFormat;
@property(readonly, nonatomic) NSString *buttonFormat; // @synthesize buttonFormat=_buttonFormat;
- (id)linkForBundleIdentifier:(id)arg1;
@property(readonly, nonatomic) ICQLink *buttonLink;
- (id)initWithServerDictionary:(id)arg1;

@end

