//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TAPrivateVehicleClassificationReason : NSObject
{
    unsigned long long _reason;
}

@property(readonly, nonatomic) unsigned long long reason; // @synthesize reason=_reason;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)initWithReason:(unsigned long long)arg1;

@end

