//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSData, NSString;

@interface HSNowPlayingArtworkResponse
{
    NSData *_artworkData;
    NSString *_artworkMIMEType;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *artworkMIMEType; // @synthesize artworkMIMEType=_artworkMIMEType;
@property(retain, nonatomic) NSData *artworkData; // @synthesize artworkData=_artworkData;

@end

