//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface (null) (WorkoutCore)
- (void)workoutSession:(id)arg1 didDisconnectFromRemoteDeviceWithError:(id)arg2;
- (void)workoutSession:(id)arg1 didReceiveDataFromRemoteDevice:(id)arg2;
- (void)workoutSession:(id)arg1 didFailWithError:(id)arg2;
- (void)workoutSession:(id)arg1 didChangeToState:(long long)arg2 fromState:(long long)arg3 date:(id)arg4;
@end

