//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface AXFBFakeProcessState : NSObject
{
    int _pid;
}

@property(nonatomic) int pid; // @synthesize pid=_pid;

@end

