//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <HealthUI/HKChartPoint-Protocol.h>

@class NSDate, NSNumber, NSString;
@protocol HKGraphSeriesBlockCoordinateInfo;

@interface _HKBloodGlucosePercentInRangeChartPoint : NSObject <HKChartPoint>
{
    NSDate *_midDate;
    NSNumber *_fractionBelowUpperLevel2HypoglycemiaBound;
    NSNumber *_fractionBelowUpperLevel1HypoglycemiaBound;
    NSNumber *_fractionBelowUpperEuglycemiaBound;
    id <HKGraphSeriesBlockCoordinateInfo> _userInfo;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <HKGraphSeriesBlockCoordinateInfo> userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) NSNumber *fractionBelowUpperEuglycemiaBound; // @synthesize fractionBelowUpperEuglycemiaBound=_fractionBelowUpperEuglycemiaBound;
@property(retain, nonatomic) NSNumber *fractionBelowUpperLevel1HypoglycemiaBound; // @synthesize fractionBelowUpperLevel1HypoglycemiaBound=_fractionBelowUpperLevel1HypoglycemiaBound;
@property(retain, nonatomic) NSNumber *fractionBelowUpperLevel2HypoglycemiaBound; // @synthesize fractionBelowUpperLevel2HypoglycemiaBound=_fractionBelowUpperLevel2HypoglycemiaBound;
@property(retain, nonatomic) NSDate *midDate; // @synthesize midDate=_midDate;
- (id)maxYValue;
- (id)minYValue;
- (id)allYValues;
- (id)yValueForKey:(id)arg1;
- (id)yValue;
- (id)maxXValueAsGenericType;
- (id)minXValueAsGenericType;
- (id)xValueAsGenericType;
- (id)initWithStartDate:(id)arg1 endDate:(id)arg2 userInfo:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

