//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DOMTimeRanges
{
}

- (double)end:(unsigned int)arg1;
- (double)start:(unsigned int)arg1;
@property(readonly) unsigned int length;
- (void)dealloc;

@end

