//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <HealthKit/NSObject-Protocol.h>

@class NSArray, NSString;

@protocol HKMedicalRecordCodings <NSObject>
+ (NSString *)defaultDisplayString;
@property(readonly, nonatomic) NSArray *medicalRecordPreferredSystems;
@property(readonly, nonatomic) NSArray *medicalRecordCodings;
@property(readonly, nonatomic) NSArray *indexKeywords;
- (NSString *)fallbackDisplayString;
@end

