//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewListCell.h>

@class MISSING_TYPE;

@interface _TtC15ConversationKit35InCallControlsIgnoreLMIRequestsCell : UICollectionViewListCell
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *$__lazy_storage_$_ignoreLMIRequestsSwitch;
    MISSING_TYPE *$__lazy_storage_$_switchAccessory;
    MISSING_TYPE *$__lazy_storage_$_cellContentConfiguration;
}

- (void).cxx_destruct;
- (void)didToggleMuteState:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

