//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UITableViewCell.h>

@class MISSING_TYPE, _TtC15ConversationKit19InCallControlButton;

@interface _TtC15ConversationKit41InCallControlsAddParticipantTableViewCell : UITableViewCell
{
    MISSING_TYPE *titleLabel;
    MISSING_TYPE *button;
    MISSING_TYPE *isAccessiblityConstraintsEnabled;
    MISSING_TYPE *nameLabelFirstBaselineLayoutConstraint;
    MISSING_TYPE *nameLabelLastBaselineLayoutConstraint;
    MISSING_TYPE *delegate;
    MISSING_TYPE *isEnabled;
}

- (void).cxx_destruct;
- (void)traitCollectionDidChange:(id)arg1;
- (void)didTapButton:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
@property(nonatomic, readonly) _TtC15ConversationKit19InCallControlButton *button; // @synthesize button;

@end

