//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface PDFTilePoolPrivate : NSObject
{
    NSObject<OS_dispatch_queue> *workQueue;
    struct os_unfair_lock_s surfacesLock;
    NSMutableDictionary *surfaces;
    int surfaceType;
}

- (void).cxx_destruct;

@end

