//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface BRKWriter : NSObject
{
    struct os_unfair_lock_s _lock;
    NSString *_path;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *path; // @synthesize path=_path;
- (void)performWithLock:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithPath:(id)arg1;

@end

