//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <WorkflowUICore/WFTreeNode.h>

@class MISSING_TYPE;

@interface _TtC14WorkflowEditorP33_FA761DC98093C80AEEA5EF5E79114EB710ActionNode : WFTreeNode
{
    MISSING_TYPE *action;
}

- (void).cxx_destruct;
- (id)initWithRepresentedObject:(id)arg1;

@end

