//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CKWeakObjectContainer : NSObject
{
    id _object;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id object; // @synthesize object=_object;

@end

