//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewLayoutAttributes.h>

@class UIColor;

@interface WFModulesCollectionViewLayoutAttributes : UICollectionViewLayoutAttributes
{
    UIColor *_connectorColor;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIColor *connectorColor; // @synthesize connectorColor=_connectorColor;
- (_Bool)_isTransitionVisibleTo:(id)arg1;

@end

