//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <WorkflowEditor/NSSecureCoding-Protocol.h>

@class WFParameter;
@protocol WFParameterState;

@interface WFUIKitParameterEditingRequest : NSObject <NSSecureCoding>
{
    WFParameter *_parameter;
    id <WFParameterState> _currentState;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(readonly, nonatomic) id <WFParameterState> currentState; // @synthesize currentState=_currentState;
@property(readonly, nonatomic) WFParameter *parameter; // @synthesize parameter=_parameter;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithParameter:(id)arg1 currentState:(id)arg2;

@end

