//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <HMFoundation/HMFObject.h>

@class HMDDevice, NSString;

__attribute__((visibility("hidden")))
@interface HMDCameraIDSSessionInviterDeviceVerifier : HMFObject
{
    NSString *_sessionID;
    HMDDevice *_expectedInviter;
}

+ (id)logCategory;
- (void).cxx_destruct;
@property(readonly) HMDDevice *expectedInviter; // @synthesize expectedInviter=_expectedInviter;
@property(readonly) NSString *sessionID; // @synthesize sessionID=_sessionID;
- (id)logIdentifier;
- (_Bool)canAcceptInvitationForSessionWithIdentifier:(id)arg1;
- (_Bool)canAcceptInvitationFromDeviceWithHandle:(id)arg1;
- (id)initWithSessionID:(id)arg1 expectedInviter:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

