//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <HMFoundation/HMFObject.h>

@class HMDNetworkObserver;

__attribute__((visibility("hidden")))
@interface HMDHouseholdNetworkStabilityLogEventFactory : HMFObject
{
    HMDNetworkObserver *_networkObserver;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) HMDNetworkObserver *networkObserver; // @synthesize networkObserver=_networkObserver;
- (void)deleteCountersAfterDate:(id)arg1;
- (void)deleteCountersBeforeDate:(id)arg1;
- (id)coalescedLogEventsFromLogEvents:(id)arg1 homeUUID:(id)arg2;
- (id)logEventsFromDictionary:(id)arg1;
- (id)serializeLogEvents:(id)arg1;
- (id)logEventsPopulatedForHomeWithUUID:(id)arg1 associatedWithDate:(id)arg2;
- (id)initWithNetworkObserver:(id)arg1;

@end

