//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "TVPMutableChapter.h"

@class AVMetadataItem;

__attribute__((visibility("hidden")))
@interface TVPAVTimedMetadataGroupChapter : TVPMutableChapter
{
    AVMetadataItem *_imageMetadataItem;
}

- (void).cxx_destruct;
@property(retain, nonatomic) AVMetadataItem *imageMetadataItem; // @synthesize imageMetadataItem=_imageMetadataItem;
- (void)_loadChapterNameFromMetadataItem:(id)arg1;
- (id)initWithAVTimedMetadataGroup:(id)arg1 filterByLanguages:(id)arg2;

@end

