//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TrialProto/TRIPBMessage.h>

@class NSString, TRIPBTimestamp;

@interface TRIPersistedNamespaceStatus : TRIPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasLatestNotificationQueryLocalTime; // @dynamic hasLatestNotificationQueryLocalTime;
@property(nonatomic) _Bool hasNamespaceCompatibilityVersion; // @dynamic hasNamespaceCompatibilityVersion;
@property(nonatomic) _Bool hasNamespaceName; // @dynamic hasNamespaceName;
@property(retain, nonatomic) TRIPBTimestamp *latestNotificationQueryLocalTime; // @dynamic latestNotificationQueryLocalTime;
@property(nonatomic) unsigned int namespaceCompatibilityVersion; // @dynamic namespaceCompatibilityVersion;
@property(copy, nonatomic) NSString *namespaceName; // @dynamic namespaceName;

@end

