//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MaterialKit/MTMaterialOverlaySettings-Protocol.h>

@protocol MTMaterialLuminanceOverlaySettings <MTMaterialOverlaySettings>
@property(nonatomic) double auxiliaryOverlayBlurRadius;
@property(nonatomic) double secondaryOverlayBrightness;
@property(nonatomic) double secondaryOverlaySaturation;
@property(nonatomic) double primaryOverlayBrightness;
@property(nonatomic) double primaryOverlaySaturation;
@property(nonatomic) double baseOverlayBlurRadius;
@property(nonatomic) double baseOverlayBrightness;
@property(nonatomic) double baseOverlaySaturation;
@end

