//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol OS_dispatch_queue;

@interface PHImportDeleteJob : NSObject
{
    _Bool _canCancel;
    CDUnknownBlockType _completion;
    NSMutableArray *_cameraFiles;
    NSObject<OS_dispatch_queue> *_serializer;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *serializer; // @synthesize serializer=_serializer;
@property(nonatomic) _Bool canCancel; // @synthesize canCancel=_canCancel;
@property(retain, nonatomic) NSMutableArray *cameraFiles; // @synthesize cameraFiles=_cameraFiles;
@property(readonly, copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void).cxx_destruct;
- (unsigned long long)removeCameraFile:(id)arg1;
- (void)deleteAllCameraFiles;
- (void)deleteNextCameraFile;
- (id)initWithCameraFiles:(id)arg1 canCancel:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;

@end

