//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class QLItem, QLPreviewItemStore;

@protocol QLPreviewItemStoreDelegate
- (_Bool)itemStore:(QLPreviewItemStore *)arg1 canEditItem:(QLItem *)arg2;
- (_Bool)itemStore:(QLPreviewItemStore *)arg1 canShareItem:(QLItem *)arg2;
@end

