//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSPointerArray.h>

@interface NSPointerArray (HMFoundation)
- (void)hmf_addObject:(id)arg1;
- (_Bool)hmf_removeObject:(id)arg1;
- (_Bool)hmf_removePointer:(void *)arg1;
@end

