//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface PPCustomDonation : NSObject
{
}

+ (_Bool)donateParsecNamedEntitiesAndTopics:(id)arg1 rawQuery:(id)arg2 reformulatedQuery:(id)arg3 source:(id)arg4 error:(id *)arg5;
+ (_Bool)donatePhotosTopics:(id)arg1 bundleId:(id)arg2 date:(id)arg3 error:(id *)arg4;
+ (id)_photosTopicMap;
+ (_Bool)donatePhotosNamedEntities:(id)arg1 bundleId:(id)arg2 date:(id)arg3 error:(id *)arg4;
+ (_Bool)donatePhotosLocationNamedEntities:(id)arg1 bundleId:(id)arg2 error:(id *)arg3;
+ (_Bool)donatePhotosOneUpLocationNamedEntities:(id)arg1 bundleId:(id)arg2 error:(id *)arg3;
+ (_Bool)donateSiriQuery:(id)arg1 results:(id)arg2 error:(id *)arg3;

@end

