//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface PUCurationGeoHashContainer : NSObject
{
    NSString *_geoHash;
    long long _assetCount;
    NSArray *_assetUUIDs;
    NSString *_cityName;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *cityName; // @synthesize cityName=_cityName;
@property(readonly, nonatomic) NSArray *assetUUIDs; // @synthesize assetUUIDs=_assetUUIDs;
@property(readonly, nonatomic) long long assetCount; // @synthesize assetCount=_assetCount;
@property(readonly, nonatomic) NSString *geoHash; // @synthesize geoHash=_geoHash;
- (id)initWithGeoHash:(id)arg1 assetUUIDs:(id)arg2 cityName:(id)arg3;

@end

