//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSProgress, PXContextualNotification;

__attribute__((visibility("hidden")))
@interface PUOneUpAssetSuggestionInfo : NSObject
{
    long long _state;
    NSProgress *_progress;
    PXContextualNotification *_contextualNotification;
}

- (void).cxx_destruct;
@property(retain, nonatomic) PXContextualNotification *contextualNotification; // @synthesize contextualNotification=_contextualNotification;
@property(retain, nonatomic) NSProgress *progress; // @synthesize progress=_progress;
@property(nonatomic) long long state; // @synthesize state=_state;

@end

