//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _LTDLanguageAssetService : NSObject
{
}

+ (id)canonicalLocaleIdentifiersWithError:(id *)arg1;
+ (void)installedLocales:(CDUnknownBlockType)arg1;
+ (void)setInstalledLocales:(id)arg1 useCellular:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)setAssets:(id)arg1 options:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)installedAssetsWithCompletion:(CDUnknownBlockType)arg1;
+ (void)selectedAssetsWithCompletion:(CDUnknownBlockType)arg1;
+ (void)availableAssetsWithCompletion:(CDUnknownBlockType)arg1;
+ (id)server;
+ (void)assetsWithCompletion:(CDUnknownBlockType)arg1;
+ (id)queue;
+ (void)assetsWithOptions:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)filterAssets:(id)arg1 options:(unsigned long long)arg2;
+ (void)unsubscribeAll;
+ (void)unsubscribe:(id)arg1;
+ (id)subscribeBlock:(CDUnknownBlockType)arg1;
+ (void)flushCache;
+ (id)cache;

@end

