//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSData, NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface FTSpan : NSObject
{
    NSMutableDictionary *_storage;
    NSData *_data;
    const struct Span *_root;
}

- (void).cxx_destruct;
- (id)flatbuffData;
- (Offset_fbc62bac)addObjectToBuffer:(void *)arg1;
@property(readonly, nonatomic) NSString *meta_info;
@property(readonly, nonatomic) _Bool do_not_translate;
@property(readonly, nonatomic) int end_index;
@property(readonly, nonatomic) int start_index;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithFlatbuffData:(id)arg1 root:(const struct Span *)arg2 verify:(_Bool)arg3;
- (id)initWithFlatbuffData:(id)arg1 root:(const struct Span *)arg2;
- (id)initAndVerifyWithFlatbuffData:(id)arg1;
- (id)initWithFlatbuffData:(id)arg1;

@end

