//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface NCNotificationListCellAccessibility
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (id)_accessibilitySupplementaryFooterViews;
- (id)axCustomActionsForActions:(id)arg1;
- (id)_accessibilityUserTestingChildren;
- (id)_accessibilityCellButtons;
- (id)_accessibilityCellActions;
- (id)_accessibilityOpenAction;
- (id)accessibilityIdentifier;
- (id)accessibilityLabel;
- (id)_accessibilityListViewParent;
- (_Bool)_axIsCollapsed;
- (id)_axNCNotificationViewController;
- (id)_axLookView;
- (id)accessibilityHint;
- (_Bool)_accessibilityIsSpeakThisElement;
- (_Bool)isAccessibilityElement;
- (_Bool)_accessibilityIsAwayAlertElement;
- (id)accessibilityDragSourceDescriptors;
- (id)accessibilityCustomActions;
- (_Bool)accessibilityActivate;
- (_Bool)_accessibilitySupportsActivateAction;
- (unsigned long long)accessibilityTraits;

@end

