//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SearchUI/NUIContainerViewDelegate-Protocol.h>

@class NSString, TLKSplitHeaderView;

@interface SearchUIScoreSummaryCardSectionView <NUIContainerViewDelegate>
{
    TLKSplitHeaderView *_splitHeaderView;
}

+ (id)dragTitleForCardSection:(id)arg1;
+ (id)titleForScoreBoard:(id)arg1 forDisplay:(_Bool)arg2;
+ (int)separatorStyleForCardSection:(id)arg1;
+ (_Bool)supportsRecyclingForCardSection:(id)arg1;
@property(retain, nonatomic) TLKSplitHeaderView *splitHeaderView; // @synthesize splitHeaderView=_splitHeaderView;
- (void).cxx_destruct;
- (void)updateChevronVisible:(_Bool)arg1 leaveSpaceForChevron:(_Bool)arg2;
- (struct CGSize)containerView:(id)arg1 systemLayoutSizeFittingSize:(struct CGSize)arg2 forArrangedSubview:(id)arg3;
- (void)updateWithRowModel:(id)arg1;
- (id)setupContentView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

