//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class SearchUILabel, SearchUITruncatingListLabel;

@interface SearchUISplitCardSectionView
{
    SearchUILabel *_topTitleLabel;
    SearchUILabel *_secondaryTopTitleLabel;
    SearchUITruncatingListLabel *_listLabel;
    SearchUILabel *_bottomTitleLabel;
    SearchUILabel *_bodyLabel;
}

+ (_Bool)supportsRecyclingForCardSection:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) SearchUILabel *bodyLabel; // @synthesize bodyLabel=_bodyLabel;
@property(retain, nonatomic) SearchUILabel *bottomTitleLabel; // @synthesize bottomTitleLabel=_bottomTitleLabel;
@property(retain, nonatomic) SearchUITruncatingListLabel *listLabel; // @synthesize listLabel=_listLabel;
@property(retain, nonatomic) SearchUILabel *secondaryTopTitleLabel; // @synthesize secondaryTopTitleLabel=_secondaryTopTitleLabel;
@property(retain, nonatomic) SearchUILabel *topTitleLabel; // @synthesize topTitleLabel=_topTitleLabel;
- (struct UIEdgeInsets)layoutMargins;
- (void)updateWithRowModel:(id)arg1;
- (id)setupContentView;

@end

