//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SearchFoundation/SFAppIconCardSection.h>

@interface SFAppIconCardSection (SearchUIViewClass)
- (Class)_searchUIViewClass;
- (void)customizeRowModelsForAppTopHitWithShortcuts:(id)arg1;
- (long long)preferredBackgroundStyleForIsLeadingPrimaryCard:(_Bool)arg1;
- (void)customizeSection:(id)arg1 isLeading:(_Bool)arg2;
- (struct NSDirectionalEdgeInsets)searchUIGridSectionModel_sectionInsetsFor:(id)arg1;
- (struct NSDirectionalEdgeInsets)searchUIGridSectionModel_groupInset;
- (double)searchUIGridSectionModel_interItemSpacing;
@end

