//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

#import <Intents/NSCopying-Protocol.h>

@class PBUnknownFields, _INPBDouble, _INPBString;

@interface _INPBHomeAttributeValue : PBCodable <NSCopying>
{
    PBUnknownFields *_unknownFields;
    _INPBDouble *_doubleValue;
    _INPBString *_stringValue;
    int _valueType;
    _Bool _booleanValue;
    struct {
        unsigned int valueType:1;
        unsigned int booleanValue:1;
    } _has;
}

+ (id)options;
@property(retain, nonatomic) _INPBString *stringValue; // @synthesize stringValue=_stringValue;
@property(retain, nonatomic) _INPBDouble *doubleValue; // @synthesize doubleValue=_doubleValue;
@property(nonatomic) _Bool booleanValue; // @synthesize booleanValue=_booleanValue;
- (void).cxx_destruct;
@property(readonly, nonatomic) PBUnknownFields *unknownFields;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasStringValue;
@property(readonly, nonatomic) _Bool hasDoubleValue;
@property(nonatomic) _Bool hasBooleanValue;
- (int)StringAsValueType:(id)arg1;
- (id)valueTypeAsString:(int)arg1;
@property(nonatomic) _Bool hasValueType;
@property(nonatomic) int valueType; // @synthesize valueType=_valueType;

@end

