//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDate, _HMCameraSnapshot;

@interface HMCameraSnapshot
{
    _HMCameraSnapshot *_snapshot;
}

@property(retain, nonatomic) _HMCameraSnapshot *snapshot; // @synthesize snapshot=_snapshot;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDate *captureDate;
- (id)initWithSnapshot:(id)arg1;

@end

