//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class HMCHIPServiceHome, NSString;

@interface HMCHIPEcosystemPairAccessoryRequest
{
    HMCHIPServiceHome *_home;
    NSString *_pairingIdentifier;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *pairingIdentifier; // @synthesize pairingIdentifier=_pairingIdentifier;
@property(readonly, copy, nonatomic) HMCHIPServiceHome *home; // @synthesize home=_home;
- (id)attributeDescriptions;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)messageType;
- (id)initWithSetupPayload:(id)arg1;
- (id)initWithSetupURLString:(id)arg1;
- (id)initWithPairingIdentifier:(id)arg1 home:(id)arg2;

@end

