//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface _TtC8VideosUI31LibDownloadingEpisodesViewModel
{
    MISSING_TYPE *_textViewModel;
    MISSING_TYPE *showEntity;
    MISSING_TYPE *cancellables;
    MISSING_TYPE *seasons;
}

- (void)fetchShowDetails;

@end

