//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface _TtC8VideosUI21UpsellOfferViewLayout
{
    MISSING_TYPE *$__lazy_storage_$_backgroundImageLayout;
    MISSING_TYPE *$__lazy_storage_$_contentLogoLayout;
    MISSING_TYPE *$__lazy_storage_$_contentTextLayout;
    MISSING_TYPE *$__lazy_storage_$_coverArtImageLayout;
    MISSING_TYPE *$__lazy_storage_$_tagsLayout;
    MISSING_TYPE *$__lazy_storage_$_contextImageLayout;
    MISSING_TYPE *$__lazy_storage_$_titleTextLayout;
    MISSING_TYPE *$__lazy_storage_$_descriptionTextLayout;
    MISSING_TYPE *minHeightForUberLayout;
    MISSING_TYPE *gradientHeightPhone;
    MISSING_TYPE *gradientHeightPad;
}

@end

