//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class IKAppContext, NSDictionary;

__attribute__((visibility("hidden")))
@interface VUIActionTypeGDPR
{
    NSDictionary *_contextData;
    IKAppContext *_appContext;
}

- (void).cxx_destruct;
@property(nonatomic) __weak IKAppContext *appContext; // @synthesize appContext=_appContext;
@property(retain, nonatomic) NSDictionary *contextData; // @synthesize contextData=_contextData;
- (void)performWithTargetResponder:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)initWithContextData:(id)arg1 appContext:(id)arg2;

@end

