//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSURL;

@interface VUIBootURLController : NSObject
{
    NSURL *_localAppURL;
}

@property(retain, nonatomic) NSURL *localAppURL; // @synthesize localAppURL=_localAppURL;
- (void).cxx_destruct;
- (void)fetchBootURLWithCompletionHandler:(CDUnknownBlockType)arg1;
- (id)initWithLocalAppURL:(id)arg1;
- (id)init;

@end

