//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CLTOption, NSArray, NSMutableArray, NSString;

@interface CLTOptionParser : NSObject
{
    _Bool _succeedWithoutArguments;
    _Bool _succeedWithUnkownFlags;
    NSString *_toolName;
    NSString *_versionString;
    NSString *_introductionaryDescription;
    NSString *_usageOptionsDescription;
    NSArray *_additionalHelpLines;
    CLTOption *_defaultHelpOption;
    CLTOption *_defaultVersionOption;
    NSArray *_remainingArguments;
    NSArray *_inputArguments;
    NSMutableArray *_options;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *options; // @synthesize options=_options;
@property(retain, nonatomic) NSArray *inputArguments; // @synthesize inputArguments=_inputArguments;
@property(retain, nonatomic) NSArray *remainingArguments; // @synthesize remainingArguments=_remainingArguments;
@property(retain, nonatomic) CLTOption *defaultVersionOption; // @synthesize defaultVersionOption=_defaultVersionOption;
@property(retain, nonatomic) CLTOption *defaultHelpOption; // @synthesize defaultHelpOption=_defaultHelpOption;
@property(retain, nonatomic) NSArray *additionalHelpLines; // @synthesize additionalHelpLines=_additionalHelpLines;
@property(nonatomic) _Bool succeedWithUnkownFlags; // @synthesize succeedWithUnkownFlags=_succeedWithUnkownFlags;
@property(nonatomic) _Bool succeedWithoutArguments; // @synthesize succeedWithoutArguments=_succeedWithoutArguments;
@property(retain, nonatomic) NSString *usageOptionsDescription; // @synthesize usageOptionsDescription=_usageOptionsDescription;
@property(retain, nonatomic) NSString *introductionaryDescription; // @synthesize introductionaryDescription=_introductionaryDescription;
@property(retain, nonatomic) NSString *versionString; // @synthesize versionString=_versionString;
@property(retain, nonatomic) NSString *toolName; // @synthesize toolName=_toolName;
- (void)addOption:(id)arg1;
- (void)removeAllOptions;
- (int)parseWithSuccessHandler:(CDUnknownBlockType)arg1;
- (id)parse;
- (id)usageString;
- (id)usageLine;
- (id)helpString;
@property(readonly, nonatomic) NSString *versionLine;
- (id)initWithArguments:(id)arg1;
- (id)init;

@end

