//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CKMessageEntryRecordedAudioViewAccessibility
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (void)updateProgress;
- (_Bool)accessibilityViewIsModal;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_accessibilityLoadAccessibilityInformation;
- (void)_accessibilityApplyPlayPauseDeleteButtonLabel;

@end

