//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSNumber;

@interface MPAssistantMusicSummaryLogEvent
{
    double _blockingSecureKeyLoadDuration;
    NSNumber *_perceivedTotalStartupTime;
    double _tracklistLoadDuration;
}

@property(nonatomic) double tracklistLoadDuration; // @synthesize tracklistLoadDuration=_tracklistLoadDuration;
@property(copy, nonatomic) NSNumber *perceivedTotalStartupTime; // @synthesize perceivedTotalStartupTime=_perceivedTotalStartupTime;
@property(nonatomic) double blockingSecureKeyLoadDuration; // @synthesize blockingSecureKeyLoadDuration=_blockingSecureKeyLoadDuration;
- (void).cxx_destruct;
- (id)eventPayload;
- (long long)eventCode;

@end

