//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol MPMediaRemoteEntityArtworkGenerator;

@interface MPMediaRemoteEntityTranslatorContext : NSObject
{
    id <MPMediaRemoteEntityArtworkGenerator> _artworkGenerator;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id <MPMediaRemoteEntityArtworkGenerator> artworkGenerator; // @synthesize artworkGenerator=_artworkGenerator;

@end

