//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CAMRAWStatusIndicator
{
    long long _rawMode;
}

@property(nonatomic, setter=setRAWMode:) long long rawMode; // @synthesize rawMode=_rawMode;
- (id)imageNameForAXHUD;
- (void)setOrientation:(long long)arg1 animated:(_Bool)arg2;
- (struct CGSize)intrinsicContentSize;
- (id)imageNameForCurrentState;
- (_Bool)shouldShowSlashForCurrentState;
- (_Bool)shouldUseSlash;
- (void)setRAWMode:(long long)arg1 animated:(_Bool)arg2;

@end

