//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <FileProvider/NSSecureCoding-Protocol.h>

@class NSData, NSURL;

@interface FPSandboxingURLWrapper : NSObject <NSSecureCoding>
{
    NSURL *_url;
    NSData *_scope;
    NSData *_promiseScope;
    NSURL *_promiseURL;
}

+ (void)assembleURL:(id)arg1 sandbox:(id)arg2 physicalURL:(id)arg3 physicalSandbox:(id)arg4;
+ (_Bool)supportsSecureCoding;
+ (id)wrapperWithSecurityScopedURL:(id)arg1;
+ (id)wrapperWithURL:(id)arg1 extensionClass:(const char *)arg2 report:(_Bool)arg3 error:(id *)arg4;
+ (id)wrapperWithURL:(id)arg1 extensionClass:(const char *)arg2 error:(id *)arg3;
+ (id)wrapperWithURL:(id)arg1 readonly:(_Bool)arg2 error:(id *)arg3;
+ (id)wrapperWithURL:(id)arg1 readonly:(_Bool)arg2;
+ (id)wrapperWithURL:(id)arg1;
- (void).cxx_destruct;
@property(retain) NSURL *promiseURL; // @synthesize promiseURL=_promiseURL;
@property(retain) NSData *promiseScope; // @synthesize promiseScope=_promiseScope;
@property(retain) NSData *scope; // @synthesize scope=_scope;
@property(copy, nonatomic) NSURL *url; // @synthesize url=_url;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)initWithURL:(id)arg1 extensionClass:(const char *)arg2 report:(_Bool)arg3 error:(id *)arg4;
- (id)_init;
- (id)init;

@end

