//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDictionary;

@interface TPSMonitoringEvents
{
    NSDictionary *_initialDisplayEventMap;
    NSDictionary *_displayEventMap;
    NSDictionary *_restartTrackingTriggerEventMap;
    NSDictionary *_restartTrackingDisplayEventMap;
    NSDictionary *_dismissalEventMap;
    NSDictionary *_desiredOutcomeEventMap;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(copy, nonatomic) NSDictionary *desiredOutcomeEventMap; // @synthesize desiredOutcomeEventMap=_desiredOutcomeEventMap;
@property(copy, nonatomic) NSDictionary *dismissalEventMap; // @synthesize dismissalEventMap=_dismissalEventMap;
@property(copy, nonatomic) NSDictionary *restartTrackingDisplayEventMap; // @synthesize restartTrackingDisplayEventMap=_restartTrackingDisplayEventMap;
@property(copy, nonatomic) NSDictionary *restartTrackingTriggerEventMap; // @synthesize restartTrackingTriggerEventMap=_restartTrackingTriggerEventMap;
@property(copy, nonatomic) NSDictionary *displayEventMap; // @synthesize displayEventMap=_displayEventMap;
@property(copy, nonatomic) NSDictionary *initialDisplayEventMap; // @synthesize initialDisplayEventMap=_initialDisplayEventMap;
- (id)debugDescription;
- (id)clientContextEventsForMap:(id)arg1;
- (id)clientContextKeysForMap:(id)arg1;
- (id)registrableContextualEventsForMap:(id)arg1 type:(long long)arg2;
- (id)autoDismissEvents;
- (id)registrableContextualEventsForEventOptions:(unsigned long long)arg1 type:(long long)arg2;
- (id)clientContextKeysForEventOptions:(unsigned long long)arg1;
- (_Bool)hasRegistrableContextualEventsForEventOptions:(unsigned long long)arg1;
- (_Bool)hasClientContextKeysForEventOptions:(unsigned long long)arg1;
- (unsigned long long)eventOptionsForEventIdentifier:(id)arg1;
- (id)eventMapFromMonitoringEventsDictionary:(id)arg1;
@property(readonly, nonatomic) _Bool hasEvents; // @dynamic hasEvents;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionary:(id)arg1 desiredOutcomeDictionary:(id)arg2;

@end

