//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TipsCore/NSCopying-Protocol.h>
#import <TipsCore/NSSecureCoding-Protocol.h>

@class TPSSize;

@interface TPSSizes <NSCopying, NSSecureCoding>
{
    TPSSize *_compact;
    TPSSize *_regular;
}

+ (id)classSet;
+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(retain, nonatomic) TPSSize *regular; // @synthesize regular=_regular;
@property(retain, nonatomic) TPSSize *compact; // @synthesize compact=_compact;
- (id)description;
- (double)heightToWidthRatioForViewMode:(long long)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithDictionary:(id)arg1;

@end

