//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Preferences/PSListController.h>

@class NSMutableSet, PSSpecifier;

@interface AssistantDetailController : PSListController
{
    NSMutableSet *_disabledSpotlightBundles;
    NSMutableSet *_disabledLockScreenBundles;
    NSMutableSet *_disabledSpotlightApps;
    NSMutableSet *_disabledSpotlightShortcuts;
    NSMutableSet *_disabledSuggestApps;
    PSSpecifier *_onHomeScreenGroup;
    PSSpecifier *_onHomeScreenShowAppSpecifier;
    PSSpecifier *_onHomeScreenSuggestAppSpecifier;
    PSSpecifier *_onHomeScreenShowContentSpecifier;
    PSSpecifier *_onHomeScreenSuggestShortcutsSpecifier;
    PSSpecifier *_onLockScreenGroup;
    PSSpecifier *_onLockScreenShowSiriSuggestionsSpecifier;
}

- (void).cxx_destruct;
- (id)_appName;
- (id)_bundleId;
- (id)_watchBundleToMirrorWithBundleId:(id)arg1;
- (id)_siriSuggestionsClients;
- (void)setAskSiriUseWithAskSiriEnabled:(id)arg1 specifier:(id)arg2;
- (id)askSiriUseWithAskSiriEnabled:(id)arg1;
- (id)_enableSiriAppSpecifiersWithAppId:(id)arg1 accessGranted:(_Bool)arg2;
- (void)_fetchIntentsSpecifiersWithCompletion:(CDUnknownBlockType)arg1;
- (void)_asyncAddAskSiriSettingsIfNecessary;
- (void)_saveOnLockScreenShowSiriSuggestionsEnabled:(_Bool)arg1;
- (void)setOnLockScreenShowSiriSuggestionsEnabled:(id)arg1 specifier:(id)arg2;
- (id)onLockScreenShowSiriSuggestionsEnabled:(id)arg1;
- (_Bool)_showLockscreenGroup;
- (void)_saveOnHomeScreenShowAppEnabled:(_Bool)arg1;
- (void)setOnHomeScreenShowAppEnabled:(id)arg1 specifier:(id)arg2;
- (id)onHomeScreenShowAppEnabled:(id)arg1;
- (id)_loadDisabledSuggestAppsSet;
- (void)_saveOnHomeScreenSuggestAppEnabled:(_Bool)arg1;
- (void)setOnHomeScreenSuggestAppEnabled:(id)arg1 specifier:(id)arg2;
- (id)onHomeScreenSuggestAppEnabled:(id)arg1;
- (id)_loadDisabledShortcutsSet;
- (void)_saveOnHomeScreenSuggestShortcutsEnabled:(_Bool)arg1;
- (void)setOnHomeScreenSuggestShortcutsEnabled:(id)arg1 specifier:(id)arg2;
- (id)onHomeScreenSuggestShortcutsEnabled:(id)arg1;
- (void)_saveOnHomeScreenShowContentEnabled:(_Bool)arg1;
- (void)setOnHomeScreenShowContentEnabled:(id)arg1 specifier:(id)arg2;
- (id)onHomeScreenShowContentEnabled:(id)arg1;
- (void)_addonHomeScreenSpecifiersToSpecifiers:(id)arg1;
- (id)_inAppFooterString;
- (id)_inAppShowToggleLableString;
- (void)setInAppLearnFromAppEnabled:(id)arg1 specifier:(id)arg2;
- (id)inAppLearnFromAppEnabled:(id)arg1;
- (void)setNanoInAppShowSiriSuggestionsEnabled:(_Bool)arg1 bundleId:(id)arg2;
- (void)setInAppShowSiriSuggestionsEnabled:(id)arg1 specifier:(id)arg2;
- (id)inAppShowSiriSuggestionsEnabled:(id)arg1;
- (void)_addInAppSpecifiersToSpecifiers:(id)arg1;
- (id)specifiers;
- (void)viewWillAppear:(_Bool)arg1;

@end

