//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface ASTNetworkReachability : NSObject
{
}

+ (_Bool)reachabilityHasCellOnlyNetworkConnection:(struct __SCNetworkReachability *)arg1;
+ (_Bool)reachabilityHasNetworkConnection:(struct __SCNetworkReachability *)arg1;
+ (struct __SCNetworkReachability *)createReachabilityForVoiceDownload;
+ (_Bool)hasCellOnlyNetworkConnection;
+ (_Bool)hasNetworkConnection;

@end

