//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class HDProfile, HDSQLitePredicate, _HDWorkoutCondenserAnalyticsAccumulator;

__attribute__((visibility("hidden")))
@interface _HDWorkoutCondensationConfiguration : NSObject
{
    HDProfile *_profile;
    HDSQLitePredicate *_predicate;
    double _minimumWorkoutDuration;
    long long _minimumSeriesSize;
    long long _maximumSeriesSize;
    long long _deletedSampleThreshold;
    _HDWorkoutCondenserAnalyticsAccumulator *_analyticsAccumulator;
}

- (void).cxx_destruct;

@end

