//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <HealthDaemon/NSSecureCoding-Protocol.h>

@class NSUUID;

@interface HDObjectAuthorizationRecord : NSObject <NSSecureCoding>
{
    NSUUID *_objectUUID;
    NSUUID *_sourceUUID;
    NSUUID *_sessionUUID;
    long long _status;
    double _modificationDate;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(nonatomic) double modificationDate; // @synthesize modificationDate=_modificationDate;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(copy, nonatomic) NSUUID *sessionUUID; // @synthesize sessionUUID=_sessionUUID;
@property(copy, nonatomic) NSUUID *sourceUUID; // @synthesize sourceUUID=_sourceUUID;
@property(copy, nonatomic) NSUUID *objectUUID; // @synthesize objectUUID=_objectUUID;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)init;

@end

