//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIViewController.h>

@class MISSING_TYPE;

@interface _TtCV12PhotosUICoreP33_B710F56EBF55D875B7CD9A668821701039PXLargeNavigationTitleIntrospectionView29IntrospectionUIViewController : UIViewController
{
    MISSING_TYPE *configuration;
}

- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)willMoveToParentViewController:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

