//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <PhotosUICore/PXAudioAssetEntryPoint-Protocol.h>

@class NSArray, NSString;

@interface PXConcreteAudioAssetEntryPoint : NSObject <PXAudioAssetEntryPoint>
{
    double _time;
    NSArray *_fadeInKeyTimeOffsets;
    NSArray *_fadeInKeyGainValues;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSArray *fadeInKeyGainValues; // @synthesize fadeInKeyGainValues=_fadeInKeyGainValues;
@property(readonly, copy, nonatomic) NSArray *fadeInKeyTimeOffsets; // @synthesize fadeInKeyTimeOffsets=_fadeInKeyTimeOffsets;
@property(readonly, nonatomic) double time; // @synthesize time=_time;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (float)fadeInGainAtOffset:(double)arg1;
@property(readonly, copy) NSString *description;
- (id)initWithTime:(double)arg1 fadeInKeyTimeOffsets:(id)arg2 fadeInKeyGainValues:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

