//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PXDiagnosticsSettings
{
    _Bool _enableContextualGesture;
    _Bool _enableGenericService;
    _Bool _enableMemoriesRelatedService;
    _Bool _enableTitleFontService;
    _Bool _simulateLaunchedToTest;
}

+ (id)sharedInstance;
+ (id)settingsControllerModule;
@property(nonatomic) _Bool simulateLaunchedToTest; // @synthesize simulateLaunchedToTest=_simulateLaunchedToTest;
@property(nonatomic) _Bool enableTitleFontService; // @synthesize enableTitleFontService=_enableTitleFontService;
@property(nonatomic) _Bool enableMemoriesRelatedService; // @synthesize enableMemoriesRelatedService=_enableMemoriesRelatedService;
@property(nonatomic) _Bool enableGenericService; // @synthesize enableGenericService=_enableGenericService;
@property(nonatomic) _Bool enableContextualGesture; // @synthesize enableContextualGesture=_enableContextualGesture;
- (void)setDefaultValues;
- (id)parentSettings;

@end

