//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface PXFaceTileImageCombiner : NSObject
{
    unsigned long long _currentGeneration;
}

+ (id)_generateCombinedImageFromImages:(id)arg1 context:(id)arg2;
+ (id)placeholderImageForNumberOfItems:(unsigned long long)arg1 context:(id)arg2;
+ (void)initialize;
- (void)_returnCombinedImage:(id)arg1 generation:(unsigned long long)arg2 resultHandler:(CDUnknownBlockType)arg3;
- (void)requestCombinedImageForItems:(id)arg1 context:(id)arg2 resultHandler:(CDUnknownBlockType)arg3;

@end

