//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <PhotosUICore/NSObject-Protocol.h>

@class PXPeoplePreviewActionViewController, PXPersonItem;

@protocol PXPeoplePreviewActionViewControllerDelegate <NSObject>
- (void)peoplePreviewActionViewController:(PXPeoplePreviewActionViewController *)arg1 wantsToChangePerson:(PXPersonItem *)arg2 toType:(long long)arg3;
@end

