//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDictionary, NSMapTable, PXPhotosViewModel;

@interface PXPhotosGridActionManager
{
    PXPhotosViewModel *_viewModel;
    NSDictionary *_actionPerformersByType;
    NSMapTable *_actionTypeByBarButtonItem;
}

+ (id)actionsWithActionPerformers;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSMapTable *actionTypeByBarButtonItem; // @synthesize actionTypeByBarButtonItem=_actionTypeByBarButtonItem;
@property(readonly, nonatomic) NSDictionary *actionPerformersByType; // @synthesize actionPerformersByType=_actionPerformersByType;
@property(readonly, nonatomic) __weak PXPhotosViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (id)activityForActionType:(id)arg1;
- (id)alertActionForActionType:(id)arg1;
- (void)_handleBarButtonItem:(id)arg1;
- (id)barButtonItemForActionType:(id)arg1;
- (id)localizedTitleForActionType:(id)arg1 useCase:(unsigned long long)arg2;
- (id)actionPerformerForActionType:(id)arg1;
- (_Bool)canPerformActionType:(id)arg1;
- (id)init;
- (id)initWithViewModel:(id)arg1;

@end

