//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface PXSharingConfidentialityController : NSObject
{
}

+ (id)confidentialFeatureWarningMessage;
+ (id)confidentialityWarningMessage;
+ (id)confidentialityWarningTitle;
+ (_Bool)confidentialityCheckRequired;
+ (_Bool)confidentialWarningRequiredForShareableSelection:(id)arg1;
+ (_Bool)confidentialWarningRequiredForAssetReferences:(id)arg1;
+ (_Bool)confidentialWarningRequiredForAssets:(id)arg1;
+ (_Bool)confidentialWarningRequiredForAsset:(id)arg1;
+ (id)confidentialityAlertWithActions:(id)arg1;

@end

