//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSMutableSet, NSSet;

__attribute__((visibility("hidden")))
@interface VCHardwareSettings : NSObject
{
    _Bool _supportVCPEncoderInitialized;
    _Bool _supportVCPEncoder;
    NSMutableDictionary *_hardwareUsageModeSettings;
    NSMutableSet *_pixelFormatCollections;
    _Bool _isSiriVoiceTapSupported;
    _Bool _isSiriVoicePlayoutSupported;
    _Bool _vcpSupportsHEVCEncoder;
    _Bool _isMLEnhanceOneToOneSupported;
}

+ (_Bool)isMLEnhanceOneToOneSupported;
+ (_Bool)isDeviceLargeScreen;
+ (_Bool)isAppleSilicon;
+ (_Bool)isMediaRecordingSupported;
+ (_Bool)isRemoteCameraSenderSupported;
+ (_Bool)supportsMultiway720pStream;
+ (_Bool)retainPixelBufferForMediaRecordingEnabled;
+ (_Bool)isCellularTappingSupported;
+ (_Bool)isExternalCameraSupported;
+ (_Bool)isViewPointCorrectionSupported;
+ (_Bool)isSiriVoicePlayoutSupported;
+ (_Bool)isSiriVoiceTapSupported;
+ (unsigned int)maxVCPSupportedTemporalLayers;
+ (_Bool)preferPresentationTimestamp;
+ (_Bool)supportsPortraitCameraCapture;
+ (_Bool)isVideoRenderingSupported;
+ (unsigned int)maxActiveVideoDecoders;
+ (unsigned int)maxActiveVideoEncoders;
+ (long long)screenShareCapabilities;
+ (double)previewPreferredAspectRatio;
+ (_Bool)disableMLScalarDuringSharing;
+ (_Bool)supportsDedicatedSystemAudioStream;
+ (_Bool)supportsSystemAudioTap;
+ (_Bool)supportsScreenCapture;
+ (_Bool)limitCameraDownlinkBitrateDuringSharing;
+ (id)supportedVideoPayloads;
+ (unsigned int)maxMultiwayFramerateSupported;
+ (unsigned int)maxOneToOneFramerateSupported;
+ (_Bool)supportsMultiway1080pStream;
+ (_Bool)supportsHEVCDecoding;
+ (_Bool)supportsHEVCEncoding;
+ (_Bool)supportsHEIFEncoding;
+ (_Bool)isVoiceProcessingAt24KSupported;
+ (_Bool)isCaptionsSupported;
+ (_Bool)isCaptureSIFRPreferred;
+ (_Bool)isSpatialAudioSupported;
+ (_Bool)isDisplayPortrait;
+ (unsigned int)maxFrameRateSupportedBackgroundBlur;
+ (unsigned int)maxActiveScreenEncoders;
+ (_Bool)shouldEnforceScreenFrameRateLimit;
+ (unsigned int)maxFrameRateSupportedScreenShare;
+ (unsigned long long)maxScreenEncodingSizeSupported;
+ (_Bool)supportsFilteredScreenCapture;
+ (unsigned int)screenHeightForDisplayID:(unsigned int)arg1;
+ (unsigned int)screenWidthForDisplayID:(unsigned int)arg1;
+ (unsigned int)screenHeight;
+ (unsigned int)screenWidth;
+ (_Bool)shouldOverrideGPUMuxing;
+ (_Bool)disableViewPointCorrectionForSharing;
+ (unsigned int)maxFpsCameraCaptureDuringSharing;
+ (unsigned int)maxRemoteParticipants30fps;
+ (unsigned int)builtinMicCount;
+ (long long)deviceClass;
+ (id)virtualHardwareSettings:(id)arg1;
@property(readonly, nonatomic) _Bool isMLEnhanceOneToOneSupported; // @synthesize isMLEnhanceOneToOneSupported=_isMLEnhanceOneToOneSupported;
@property(readonly, nonatomic) NSSet *pixelFormatCollections; // @synthesize pixelFormatCollections=_pixelFormatCollections;
@property(readonly, nonatomic) _Bool vcpSupportsHEVCEncoder; // @synthesize vcpSupportsHEVCEncoder=_vcpSupportsHEVCEncoder;
@property(readonly, nonatomic) _Bool isSiriVoicePlayoutSupported;
@property(readonly, nonatomic) _Bool isSiriVoiceTapSupported;
@property(readonly, nonatomic) _Bool isVideoRenderingSupported;
- (unsigned int)maxNetworkBitrateMultiwayVideoOnWifi:(_Bool)arg1;
- (unsigned int)maxNetworkBitrateMultiwayAudioOnWifi:(_Bool)arg1 isLowLatencyAudio:(_Bool)arg2;
- (_Bool)storeHardwareSettingsForAllOperatingModes;
- (unsigned int)tilesPerVideoFrame:(int)arg1 hdrMode:(unsigned long long)arg2;
- (unsigned int)tilesPerVideoFrame:(int)arg1;
- (id)featureListStringForHEVC:(int)arg1;
- (id)featureListStringForH264:(int)arg1;
- (void)dealloc;
- (id)init;

@end

