//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface VCRateControlBandwidthEstimatorMap : NSObject
{
    unsigned int _mode;
    unsigned int _radioAccessTechnology;
    double _estimatedBandwidth;
    double _estimatedBandwidthUncapped;
    NSMutableDictionary *_estimatorMap;
    unsigned int _currentActiveEstimatorID;
    int _state;
}

@property(nonatomic) double estimatedBandwidthUncapped; // @synthesize estimatedBandwidthUncapped=_estimatedBandwidthUncapped;
@property(nonatomic) unsigned int mode; // @synthesize mode=_mode;
@property(nonatomic) unsigned int radioAccessTechnology; // @synthesize radioAccessTechnology=_radioAccessTechnology;
@property(nonatomic) double estimatedBandwidth; // @synthesize estimatedBandwidth=_estimatedBandwidth;
- (void)deregisterBandwidthEstimatorWithID:(unsigned int)arg1;
- (id)bandwidthEstimatorWithID:(unsigned int)arg1 isProbingSequence:(_Bool)arg2 isEndOfProbingSequence:(_Bool)arg3;
- (void)dealloc;
- (id)init;

@end

