//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC7VFXCore13ScriptCodeGen : _TtCs12_SwiftObject
{
    MISSING_TYPE *entityManager;
    MISSING_TYPE *userProjectName;
    MISSING_TYPE *mangledProjectName;
    MISSING_TYPE *isGeneratingForTesting;
}

@end

