//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <MusicLibrary/NSSecureCoding-Protocol.h>

@class NSDictionary;

@interface ML3ClientImportResult : NSObject <NSSecureCoding>
{
    _Bool _success;
    NSDictionary *_resultingDatabasePersistentIDs;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDictionary *resultingDatabasePersistentIDs; // @synthesize resultingDatabasePersistentIDs=_resultingDatabasePersistentIDs;
@property(readonly, nonatomic) _Bool success; // @synthesize success=_success;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithSuccess:(_Bool)arg1 resultingDatabasePersistentIDs:(id)arg2;

@end

