//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCO24IntelligencePlatformCore10ViewUpdate7Manager : _TtCs12_SwiftObject
{
    MISSING_TYPE *viewDb;
    MISSING_TYPE *viewGenerators;
    MISSING_TYPE *config;
    MISSING_TYPE *synchronizedUpdater;
}

@end

