//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

#import <TrustedPeers/NSCopying-Protocol.h>

@class NSMutableArray, NSString;

@interface TPPBPolicyIntroducersByCategory : PBCodable <NSCopying>
{
    NSString *_category;
    NSMutableArray *_introducers;
}

+ (Class)introducersType;
+ (id)TPPBPolicyIntroducersByCategoryWithCategory:(id)arg1 introducers:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *introducers; // @synthesize introducers=_introducers;
@property(retain, nonatomic) NSString *category; // @synthesize category=_category;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
- (id)introducersAtIndex:(unsigned long long)arg1;
- (unsigned long long)introducersCount;
- (void)addIntroducers:(id)arg1;
- (void)clearIntroducers;
@property(readonly, nonatomic) _Bool hasCategory;

@end

