//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AssetCatalogFoundation/IBPlaceholderImageInfo.h>

@interface IBPlaceholderImageInfo (IBCTTSupport)
+ (id)placeholderImageWithSize:(struct CGSize)arg1;
+ (id)createNewPlaceholderImageInstance;
- (id)image;
@end

