//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIBackgroundConfiguration.h>

@interface UIBackgroundConfiguration (IBCocoaTouchToolIntegration)
- (void)ibApplyNonDefaultValuesToConfiguration:(id)arg1;
- (id)initWithBinaryUnarchiver:(id)arg1;
@end

