//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

#import <MapKit/MKActivityObserving-Protocol.h>

@class NSString, UIActivityIndicatorView, UIImageView, UILabel, UITapGestureRecognizer, UIVisualEffectView;
@protocol MKAddPhotoBadgeViewDelegate;

__attribute__((visibility("hidden")))
@interface MKAddPhotoBadgeView : UIView <MKActivityObserving>
{
    UILabel *_label;
    UIImageView *_imageView;
    struct CGSize _size;
    UITapGestureRecognizer *_gestureRecognizer;
    UIActivityIndicatorView *_spinner;
    UIVisualEffectView *_backgroundView;
    id <MKAddPhotoBadgeViewDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <MKAddPhotoBadgeViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)endAnimatingActivityIndicatorWithError:(id)arg1;
- (void)beginAnimatingActivityIndicator;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;
- (void)_badgeViewTapped;
- (void)_setupGestureRecognizer;
- (void)_setupSubviews;
@property(readonly, nonatomic) double fullHeight;
@property(readonly, nonatomic) double fullWidth;
@property(readonly, nonatomic) double compressedWidth;
@property(readonly, nonatomic) double margin;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

