//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CNContactStyle;

__attribute__((visibility("hidden")))
@interface CNContactListStyleWrapperProvider
{
    CNContactStyle *_contactStyle;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) CNContactStyle *contactStyle; // @synthesize contactStyle=_contactStyle;
- (_Bool)navigationBarIsTranslucent;
- (long long)navigationBarStyle;
- (_Bool)searchBarIsTranslucent;
- (long long)searchBarKeyboardAppearance;
- (long long)searchBarStyle;
- (id)searchBarPlaceholderTextDisabledColor;
- (id)searchBarPlaceholderTextColor;
- (id)searchBarTextDisabledColor;
- (id)searchBarTextColor;
- (id)searchBarBackgroundColor;
- (_Bool)usesInsetPlatterStyle;
- (_Bool)tableIsOpaque;
- (long long)tableSeparatorOverlayBlendMode;
- (long long)tableSeparatorStyle;
- (unsigned long long)tableNoContactsAvailableStyle;
- (id)tableSeparatorColor;
- (id)tableSectionIndexBackgroundColor;
- (id)tableBackgroundFilteredColor;
- (id)tableBackgroundColor;
- (id)bannerTitleTextColor;
- (id)headerIndexTextColor;
- (id)headerBackgroundColor;
- (_Bool)cellIsVibrant;
- (_Bool)cellIsOpaque;
- (struct UIEdgeInsets)cellSeparatorInset;
- (id)cellNameTextEmphasisedFont;
- (id)cellNameTextFont;
- (id)cellSearchResultTextDisabledColor;
- (id)cellSearchResultTextColor;
- (id)cellSearchBackgroundColor;
- (id)cellNameTextHighlightedColor;
- (id)cellNameTextColor;
- (id)cellBackgroundSelectedColor;
- (id)cellBackgroundColor;
- (id)initWithContactStyle:(id)arg1;

@end

