//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewCell.h>

@class MISSING_TYPE, _TtC12GameCenterUI16DynamicTypeLabel, _TtC12GameCenterUI23GKMultiplayerStatusView;

@interface _TtC12GameCenterUI42GKMultiplayerParticipantCollectionViewCell : UICollectionViewCell
{
    MISSING_TYPE *contentBackgroundView;
    MISSING_TYPE *avatarView;
    MISSING_TYPE *silhouetteView;
    MISSING_TYPE *shouldDisplaySilhouette;
    MISSING_TYPE *nameLabel;
    MISSING_TYPE *subtitleLabel;
    MISSING_TYPE *removeButton;
    MISSING_TYPE *vibrantRemoveButton;
    MISSING_TYPE *focusGuide;
    MISSING_TYPE *displaysMessagesIcon;
    MISSING_TYPE *messagesIconView;
    MISSING_TYPE *statusAccessoryView;
    MISSING_TYPE *tapHandler;
    MISSING_TYPE *layoutMode;
    MISSING_TYPE *viewStatus;
}

+ (id)reuseIdentifier;
- (void).cxx_destruct;
@property(nonatomic, readonly) _TtC12GameCenterUI23GKMultiplayerStatusView *accessibilityStatusAccessoryView;
@property(nonatomic, readonly) _TtC12GameCenterUI16DynamicTypeLabel *accessibilitySubtitleLabel;
@property(nonatomic, readonly) _TtC12GameCenterUI16DynamicTypeLabel *accessibilityNameLabel;
- (void)didTapRemoveButton:(id)arg1;
- (void)prepareForReuse;
- (void)layoutSubviews;
- (void)applyWithParticipant:(id)arg1 number:(long long)arg2 isRemovingEnabled:(_Bool)arg3 isInvitingEnabled:(_Bool)arg4 layoutMode:(long long)arg5;
@property(nonatomic) _Bool removeButtonHidden;
@property(nonatomic, copy) CDUnknownBlockType tapHandler;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

