//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface GKAtomicBox : NSObject
{
    id _value;
}

- (void).cxx_destruct;
@property __weak id value; // @synthesize value=_value;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)init;
- (id)initWithValue:(id)arg1;

@end

