//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <GameCenterUI/GKTurnBasedMatchmakerHostProtocol-Protocol.h>
#import <GameCenterUI/GKTurnBasedMatchmakerServiceProtocol-Protocol.h>

@class GKGame, GKTurnBasedMatchmakerViewController, NSString;

@interface GKTurnBasedMatchmakerHostViewController <GKTurnBasedMatchmakerHostProtocol, GKTurnBasedMatchmakerServiceProtocol>
{
    GKTurnBasedMatchmakerViewController *_delegate;
}

+ (_Bool)dismissAutomaticallyAfterExtensionCompletion;
+ (id)turnBasedMatchmakerExtension;
- (void).cxx_destruct;
@property(nonatomic) __weak GKTurnBasedMatchmakerViewController *delegate; // @synthesize delegate=_delegate;
- (void)extensionIsCanceling;
- (void)messageFromExtension:(id)arg1;
- (void)refreshMatches;
- (void)setShowQuit:(_Bool)arg1;
- (void)setShowPlay:(_Bool)arg1;
- (void)setShowExistingMatches:(_Bool)arg1;
- (void)setMatchRequestInternal:(id)arg1;
- (id)extensionObjectProxy;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) GKGame *game;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

