//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewCell.h>

@class NSString, UIColor, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface SKUIGallerySwooshCollectionViewCell : UICollectionViewCell
{
    UIView *_contentChildView;
    UIColor *_titleColor;
    UILabel *_titleLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *contentChildView; // @synthesize contentChildView=_contentChildView;
- (void)layoutSubviews;
@property(copy, nonatomic) NSString *title;
- (void)setColoringWithColorScheme:(id)arg1;

@end

