//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class SKUISegmentedControlViewElementController;

__attribute__((visibility("hidden")))
@interface SKUINavigationBarSegmentsController
{
    SKUISegmentedControlViewElementController *_underlyingController;
}

- (void).cxx_destruct;
- (void)willAppearInNavigationBar;
- (id)view;
- (void)reloadAfterDocumentUpdateWithNavigationItem:(id)arg1;
- (id)initWithViewElement:(id)arg1;

@end

