//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface SKUISeparatorView : UIView
{
    UIColor *_color1;
    UIColor *_color2;
    long long _separatorStyle;
}

@property(nonatomic) long long separatorStyle; // @synthesize separatorStyle=_separatorStyle;
@property(copy, nonatomic) UIColor *color2; // @synthesize color2=_color2;
@property(copy, nonatomic) UIColor *color1; // @synthesize color1=_color1;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;

@end

