//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class UIImage, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface SKUIStarRatingView : UIView
{
    double _elementSpacing;
    UIImageView *_ratingStarsImageView;
    UILabel *_textLabel;
}

- (void).cxx_destruct;
@property(nonatomic) double elementSpacing; // @synthesize elementSpacing=_elementSpacing;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)layoutSubviews;
@property(readonly, nonatomic) UILabel *textLabel;
@property(retain, nonatomic) UIImage *ratingStarsImage;
- (id)initWithFrame:(struct CGRect)arg1;

@end

