//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

#import <SpringBoardHome/SBIconDragPreview-Protocol.h>

@class NSHashTable, SBIcon, SBIconView;

@interface SBHPageManagementCellDragPreview : UIView <SBIconDragPreview>
{
    NSHashTable *_cleanupDelayAssertions;
    _Bool flocked;
    _Bool iconAllowsLabelArea;
    _Bool iconAllowsAccessory;
    _Bool iconCanShowCloseBox;
    _Bool iconIsEditing;
    _Bool _delayingCleanup;
    unsigned long long _dragState;
    double iconContentScale;
    CDUnknownBlockType _cleanupHandler;
    SBIconView *_referenceIconView;
    SBIconView *_iconView;
}

- (void).cxx_destruct;
@property(nonatomic, getter=isDelayingCleanup) _Bool delayingCleanup; // @synthesize delayingCleanup=_delayingCleanup;
@property(retain, nonatomic) SBIconView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) SBIconView *referenceIconView; // @synthesize referenceIconView=_referenceIconView;
@property(copy, nonatomic) CDUnknownBlockType cleanUpHandler; // @synthesize cleanUpHandler=_cleanupHandler;
@property(nonatomic) _Bool iconIsEditing; // @synthesize iconIsEditing;
@property(nonatomic) double iconContentScale; // @synthesize iconContentScale;
@property(nonatomic) _Bool iconCanShowCloseBox; // @synthesize iconCanShowCloseBox;
@property(nonatomic) _Bool iconAllowsAccessory; // @synthesize iconAllowsAccessory;
@property(nonatomic) _Bool iconAllowsLabelArea; // @synthesize iconAllowsLabelArea;
@property(nonatomic, getter=isFlocked) _Bool flocked; // @synthesize flocked;
@property(nonatomic) unsigned long long dragState; // @synthesize dragState=_dragState;
- (void)_removeDelayCleanupAssertion:(id)arg1;
- (id)delayCleanUpForReason:(id)arg1;
- (void)setIconViewDelegate:(id)arg1;
- (void)dropDestinationAnimationCompleted;
- (void)draggingSourceCancelAnimationCompleted;
- (void)handleCleanup;
- (void)draggingSourceDroppedWithOperation:(unsigned long long)arg1;
- (void)setIconIsEditing:(_Bool)arg1 animated:(_Bool)arg2;
- (void)updateDestinationIconLocation:(id)arg1 allowsLabelArea:(_Bool)arg2 animated:(_Bool)arg3;
@property(retain, nonatomic) SBIcon *icon;
- (void)_configureIconViewWithReferenceIconView:(id)arg1;
- (id)_pageManagementCellView;
- (id)initWithReferenceIconView:(id)arg1;

@end

