//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIView.h>

#import <TextInputUI/_UIBarButtonItemViewOwner-Protocol.h>

@class NSArray, NSMutableArray, NSString, UIBarButtonItemGroup, _UIButtonBarButtonVisualProvider;
@protocol TUIButtonBarViewProvider;

@interface TUIAssistantButtonBarGroupView : UIView <_UIBarButtonItemViewOwner>
{
    NSMutableArray *_visibleButtons;
    _Bool _collapsed;
    UIBarButtonItemGroup *_barButtonItemGroup;
    double _itemSpacing;
    id <TUIButtonBarViewProvider> _buttonProvider;
    _UIButtonBarButtonVisualProvider *_visualProvider;
}

- (void).cxx_destruct;
@property(retain, nonatomic) _UIButtonBarButtonVisualProvider *visualProvider; // @synthesize visualProvider=_visualProvider;
@property(nonatomic) __weak id <TUIButtonBarViewProvider> buttonProvider; // @synthesize buttonProvider=_buttonProvider;
@property(nonatomic) double itemSpacing; // @synthesize itemSpacing=_itemSpacing;
@property(retain, nonatomic) UIBarButtonItemGroup *barButtonItemGroup; // @synthesize barButtonItemGroup=_barButtonItemGroup;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)_itemDidChangeHiddenState:(id)arg1;
- (void)_itemDidChangeWidth:(id)arg1;
- (void)_itemStandardViewNeedsUpdate:(id)arg1;
- (void)_itemCustomViewDidChange:(id)arg1 fromView:(id)arg2;
- (void)_itemDidChangeEnabledState:(id)arg1;
- (void)_itemDidChangeSelectionState:(id)arg1;
- (void)_updateViewForBarButtonItem:(id)arg1;
- (void)layoutSubviews;
- (id)_buttonBarItemViewForBarButtonItem:(id)arg1;
@property(readonly, nonatomic) NSArray *visibleButtons;
- (void)_ensureVisibleButtonsForVisibleItems;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)intrinsicContentSize;
- (struct CGSize)_preferredSizeForItems:(id)arg1 fittingWidth:(double)arg2;
@property(readonly, nonatomic) _Bool containsFlexibleItems;
- (id)_visibleItems;
- (id)_visibleItemsAllowingCollapse:(_Bool)arg1;
@property(nonatomic, getter=isCollapsed) _Bool collapsed;
- (_Bool)_canBeCollapsed;
- (id)initWithBarButtonItemGroup:(id)arg1 visualProvider:(id)arg2 buttonProvider:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

