//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface AVTAvatarPose : NSObject
{
    struct SCNVector3 _neckPosition;
    struct SCNVector4 _neckOrientation;
    NSMutableDictionary *_weights;
}

+ (id)friendlyPose;
+ (id)neutralPose;
@property(nonatomic) struct SCNVector4 neckOrientation; // @synthesize neckOrientation=_neckOrientation;
@property(nonatomic) struct SCNVector3 neckPosition; // @synthesize neckPosition=_neckPosition;
- (void).cxx_destruct;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (id)dictionaryRepresentation;
- (void)setWeight:(double)arg1 forBlendShapeNamed:(id)arg2;
- (double)weightForBlendShapeNamed:(id)arg1;

@end

