//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface AVTMorpherWeightThresholdState : NSObject
{
    _Bool _isAnimating;
    _Bool _isFadingOutAnimation;
    float _currentValue;
    float _target;
    double _t0;
}

@property(nonatomic) float target; // @synthesize target=_target;
@property(nonatomic) float currentValue; // @synthesize currentValue=_currentValue;
@property(nonatomic) double t0; // @synthesize t0=_t0;
@property(nonatomic) _Bool isFadingOutAnimation; // @synthesize isFadingOutAnimation=_isFadingOutAnimation;
@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;

@end

