//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface BOXFileVersionPromoteRequest
{
    NSString *_fileID;
    NSString *_versionID;
}

@property(retain, nonatomic) NSString *versionID; // @synthesize versionID=_versionID;
@property(retain, nonatomic) NSString *fileID; // @synthesize fileID=_fileID;
- (void).cxx_destruct;
- (void)performRequestWithCompletion:(CDUnknownBlockType)arg1;
- (id)createOperation;
- (id)initWithFileID:(id)arg1 targetVersionID:(id)arg2;

@end

