//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSNumber, NSString;

@interface EDAMUserException
{
    NSNumber *_errorCode;
    NSString *_parameter;
}

+ (id)structFields;
+ (id)structName;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *parameter; // @synthesize parameter=_parameter;
@property(retain, nonatomic) NSNumber *errorCode; // @synthesize errorCode=_errorCode;

@end

