//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSData, NSString;

@interface EDAMPushNotificationCredentials
{
    NSData *_iosDeviceToken;
    NSString *_gcmRegistrationId;
}

+ (id)structFields;
+ (id)structName;
@property(retain, nonatomic) NSString *gcmRegistrationId; // @synthesize gcmRegistrationId=_gcmRegistrationId;
@property(retain, nonatomic) NSData *iosDeviceToken; // @synthesize iosDeviceToken=_iosDeviceToken;
- (void).cxx_destruct;

@end

