//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <WorkflowKit/WFAction.h>

@interface WFStorageServiceInputAction : WFAction
{
}

- (void)runAsynchronouslyWithInput:(id)arg1 storageService:(id)arg2;
- (id)keywords;
- (id)inputContentClasses;
- (void)runAsynchronouslyWithInput:(id)arg1;

@end

