//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <WorkflowKit/WFAction.h>

#import <ActionKit/WFApplicationStateObserver-Protocol.h>

@interface WFWaitToReturnAction : WFAction <WFApplicationStateObserver>
{
}

- (void)applicationContext:(id)arg1 applicationStateDidChange:(long long)arg2;
- (void)finishRunningWithError:(id)arg1;
- (void)runAsynchronouslyWithInput:(id)arg1;

@end

