//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SLFacebookPermissionDescriptionRequest
{
}

- (id)_csvStringFromSet:(id)arg1;
- (id)initWithPermissions:(id)arg1 audience:(id)arg2;

@end

