//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <IBFoundation/NSObject-Protocol.h>

@class IBBinaryArchiver, IBBinaryUnarchiver;

@protocol IBBinaryArchiving <NSObject>

@optional
+ (id)decodeWithBinaryUnarchiver:(IBBinaryUnarchiver *)arg1;
- (const char *)cStringClassNameForBinaryArchiver:(IBBinaryArchiver *)arg1;
- (void)didFinishDecodingWithBinaryUnarchiver:(IBBinaryUnarchiver *)arg1;
- (void)didFinishEncodingWithBinaryArchiver:(IBBinaryArchiver *)arg1;
- (void)encodeWithBinaryArchiver:(IBBinaryArchiver *)arg1;
- (id)initWithBinaryUnarchiver:(IBBinaryUnarchiver *)arg1;
@end

