//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface _UIAlertControllerActionSheetRegularPresentationController
{
}

- (id)_alertControllerContainer;
- (id)_alertController;
- (id)_exceptionStringForNilSourceViewOrBarButtonItem;
- (void)dimmingViewWasTapped:(id)arg1;
- (id)_presentationControllerForTraitCollection:(id)arg1;
- (id)_compactPresentationController;

@end

