//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIFocusContainerGuide;

__attribute__((visibility("hidden")))
@interface _UIFocusContainerGuideMapEntry
{
    UIFocusContainerGuide *_focusContainerGuide;
    double _axisAlignedDistanceFromFocusedRect;
    struct CGRect _focusContainmentFrame;
}

- (void).cxx_destruct;
@property(nonatomic) double axisAlignedDistanceFromFocusedRect; // @synthesize axisAlignedDistanceFromFocusedRect=_axisAlignedDistanceFromFocusedRect;
@property(nonatomic) struct CGRect focusContainmentFrame; // @synthesize focusContainmentFrame=_focusContainmentFrame;
@property(nonatomic) __weak UIFocusContainerGuide *focusContainerGuide; // @synthesize focusContainerGuide=_focusContainerGuide;
- (id)description;
- (void)drawVisualRepresentationInContext:(struct CGContext *)arg1 imageFrame:(struct CGRect)arg2;
- (id)visualRepresentationColor;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

