//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _UIWorkIntervalProxy : NSObject
{
    struct work_interval_instance *_instance;
    _Bool _complex;
    _Bool _started;
    double _targetTimestamp;
    double _frameDuration;
}

- (void)dealloc;
- (id)init;

@end

