//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIView;

__attribute__((visibility("hidden")))
@interface UIKBCandidateView
{
    CDStruct_227bb23d _visualStyling;
    UIView *_candidateKey;
}

@property(retain, nonatomic) UIView *candidateKey; // @synthesize candidateKey=_candidateKey;
@property(nonatomic) CDStruct_227bb23d visualStyling; // @synthesize visualStyling=_visualStyling;
- (void).cxx_destruct;
- (void)clearCandidateKey;
- (void)updateCandidateKey;
- (_Bool)isTenKey;
- (id)candidateList;
- (void)displayLayer:(id)arg1;
- (void)updateForKeyplane:(id)arg1 key:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 keyplane:(id)arg2 key:(id)arg3;

@end

