//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "UIPresentationController.h"

__attribute__((visibility("hidden")))
@interface UIStickerPresentationController : UIPresentationController
{
}

- (struct CGRect)frameOfPresentedViewInContainerView;
- (void)presentationTransitionDidEnd:(_Bool)arg1;

@end

