//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <UIKitCore/NSCoding-Protocol.h>

@class UITableViewCell;

@interface UITableViewRow : NSObject <NSCoding>
{
    long long _indentationLevel;
    UITableViewCell *_cell;
    double _height;
}

+ (id)row;
@property(retain, nonatomic) UITableViewCell *cell; // @synthesize cell=_cell;
@property(nonatomic) double height; // @synthesize height=_height;
- (void).cxx_destruct;
- (long long)indentationLevel;
- (void)setIndentationLevel:(long long)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

