//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIPreviewItemController;

__attribute__((visibility("hidden")))
@interface UITextPreviewInteraction
{
    UIPreviewItemController *_previewItemController;
}

- (void).cxx_destruct;
- (void)_resetForLink;
- (_Bool)shouldAllowWithTouchTypes:(id)arg1 atPoint:(struct CGPoint)arg2 toBegin:(_Bool)arg3;
- (void)didMoveToView:(id)arg1;
- (_Bool)doesControlDelegate;

@end

