//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface UITextNonEditableInteraction
{
}

- (void)toggleSelectionCommands;
- (void)doubleTapInUneditable:(id)arg1;
- (void)oneFingerTapInUneditable:(id)arg1;
- (id)initWithMode:(long long)arg1;

@end

