//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CloudKit/CKXPCClient-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface CKContainerCallbackProxy <CKXPCClient>
{
}

- (void)handleSignificantIssueBehavior:(unsigned long long)arg1 reason:(id)arg2;
- (id)initWithContainer:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

