//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TPNumberPadDynamicButton
{
}

+ (_Bool)usesTelephonyGlyphsWhereAvailable;
+ (double)highlightedCircleViewAlpha;
+ (double)unhighlightedCircleViewAlpha;
+ (id)imageForCharacter:(unsigned int)arg1 highlighted:(_Bool)arg2;
+ (id)imageForCharacter:(unsigned int)arg1;
+ (long long)currentStyle;
- (void)updateCurrentStyleIfNecessaryFromStyle:(long long)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (id)buttonColor;
- (id)initForCharacter:(unsigned int)arg1;

@end

