//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable, NSString;
@protocol OS_dispatch_queue;

@interface CSRemoteAssetManager : NSObject
{
    NSString *_currentLanguageCode;
    NSString *_resourcePath;
    NSString *_configVersion;
    NSString *_assetHash;
    NSObject<OS_dispatch_queue> *_queue;
    NSHashTable *_observers;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)removeObserver:(id)arg1 forAssetType:(unsigned long long)arg2;
- (void)addObserver:(id)arg1 forAssetType:(unsigned long long)arg2;
- (id)resourcePathForAssetType:(unsigned long long)arg1;
- (id)assetHashForAssetType:(unsigned long long)arg1;
- (id)assetConfigVersionForAssetType:(unsigned long long)arg1;
- (id)languageCode;
- (void)setLanguageCode:(id)arg1 resourcePath:(id)arg2 configVersion:(id)arg3 assetHash:(id)arg4 assetType:(unsigned long long)arg5;
- (id)_loadJsonDataFromFile:(id)arg1;
- (void)_setAssetsInfoFromMetaData:(id)arg1;
- (_Bool)_loadFromJsonFile:(id)arg1;
- (_Bool)_writeToJsonFile:(id)arg1;
- (id)assetForCurrentLanguageOfType:(unsigned long long)arg1;
- (id)_remoteAssetMetaPath;
- (_Bool)_loadPreinstalledAssetMetaIfNeeded;
- (id)init;

@end

