//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSXPCConnection;
@protocol CSSiriAcousticFingerprinterDelegate, OS_dispatch_queue;

@interface CSSiriAcousticFingerprinter : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSXPCConnection *_asxConnection;
    id <CSSiriAcousticFingerprinterDelegate> _delegate;
    unsigned long long _totalSampleCount;
    unsigned long long _nextFingerprintSampleNumber;
    struct AudioStreamBasicDescription _sourceASBD;
    double _interval;
    struct OpaqueAudioConverter *_fingerprinterConverter;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <CSSiriAcousticFingerprinterDelegate> delegate; // @synthesize delegate=_delegate;
- (void)reset;
- (void)flush;
- (void)appendPCMData:(id)arg1;
- (id)_convertPCMDataForFingerprinting:(id)arg1;
- (_Bool)_needsConversion;
- (void)_configureWithCurrentASBD;
- (void)setASBD:(struct AudioStreamBasicDescription *)arg1;
- (void)setFingerprintInterval:(double)arg1;
- (unsigned long long)_samplesPerInterval;
- (id)_serviceWithErrorHandler:(CDUnknownBlockType)arg1;
- (id)_service;
- (void)_cleanUpConnection;
- (void)_connectionInvalidated;
- (void)_connectionInterrupted;
- (id)_connection;
- (void)dealloc;
- (id)init;

@end

