//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewCell.h>

@class CLKDevice, NTKPigmentEditOption, UIColor, UIImageView;

@interface _NTKPigmentAddCell : UICollectionViewCell
{
    CLKDevice *_device;
    UIColor *_primaryColor;
    NTKPigmentEditOption *_pigmentEditOption;
    UIImageView *_swatch;
    UIImageView *_check;
}

+ (id)reuseIdentifier;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIImageView *check; // @synthesize check=_check;
@property(readonly, nonatomic) UIImageView *swatch; // @synthesize swatch=_swatch;
@property(retain, nonatomic) NTKPigmentEditOption *pigmentEditOption; // @synthesize pigmentEditOption=_pigmentEditOption;
@property(retain, nonatomic) UIColor *primaryColor; // @synthesize primaryColor=_primaryColor;
@property(retain, nonatomic) CLKDevice *device; // @synthesize device=_device;
- (void)setImage:(id)arg1;
- (void)setSelected:(_Bool)arg1;
- (void)layoutSubviews;
- (void)_updateCheck;
- (id)initWithFrame:(struct CGRect)arg1;

@end

