//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <NanoTimeKitCompanion/NSObject-Protocol.h>

@class NTKCompanionApp, NTKCompanionFeaturedComplicationsAppLibrary;

@protocol NTKCompanionFeaturedComplicationsAppLibraryObserver <NSObject>

@optional
- (void)appLibrary:(NTKCompanionFeaturedComplicationsAppLibrary *)arg1 didUpdateAppIcon:(NTKCompanionApp *)arg2;
- (void)appLibrary:(NTKCompanionFeaturedComplicationsAppLibrary *)arg1 didRemoveApp:(NTKCompanionApp *)arg2;
- (void)appLibrary:(NTKCompanionFeaturedComplicationsAppLibrary *)arg1 didUpdateApp:(NTKCompanionApp *)arg2;
- (void)appLibrary:(NTKCompanionFeaturedComplicationsAppLibrary *)arg1 didAddApp:(NTKCompanionApp *)arg2;
@end

