//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <NanoTimeKitCompanion/NSObject-Protocol.h>

@class NTKZeusColorPalette;

@protocol NTKZeusComplicationDisplay <NSObject>
@property(nonatomic) _Bool legibilityEnabled;
@property(readonly, nonatomic) NTKZeusColorPalette *palette;
@property(nonatomic) unsigned long long style;
- (void)applyTransitionFraction:(double)arg1 fromPalette:(NTKZeusColorPalette *)arg2 toPalette:(NTKZeusColorPalette *)arg3;
- (void)applyPalette:(NTKZeusColorPalette *)arg1;
@end

