//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC11ActivityKitP33_D074D31B035C9B27F4F7807A7D21110D9Singleton : NSObject
{
    MISSING_TYPE *queue;
    MISSING_TYPE *connection;
    MISSING_TYPE *serverStartupToken;
    MISSING_TYPE *activities;
    MISSING_TYPE *activityDiffPublisher;
}

- (void).cxx_destruct;
- (id)init;
- (void)activityDidUnsubscribeForIdentifier:(id)arg1;
- (void)activityDidExceedReducedPushBudgetForIdentifier:(id)arg1;

@end

