//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface SFPrivacyReportGridRowLayoutInfo : NSObject
{
    long long _row;
    double _height;
    struct _NSRange _itemRange;
}

@property(nonatomic) double height; // @synthesize height=_height;
@property(readonly, nonatomic) struct _NSRange itemRange; // @synthesize itemRange=_itemRange;
@property(readonly, nonatomic) long long row; // @synthesize row=_row;
- (id)initWithRow:(long long)arg1 itemRange:(struct _NSRange)arg2;

@end

