//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <CopresenceCore/CPConnectionProviding-Protocol.h>
#import <CopresenceCore/CPCoreService-Protocol.h>
#import <CopresenceCore/CPCoreServiceObserver-Protocol.h>
#import <CopresenceCore/CPLinkDelegate-Protocol.h>
#import <CopresenceCore/CPParticipantDelegate-Protocol.h>

@class CPBroadcastLink, CPParticipant, NSMutableDictionary, NSString, NSXPCConnection;
@protocol CPCoreService, CPCoreServiceObserver, OS_dispatch_queue, OS_dispatch_source;

@interface CPCoreXPCServiceClient : NSObject <CPConnectionProviding, CPParticipantDelegate, CPLinkDelegate, CPCoreService, CPCoreServiceObserver>
{
    NSXPCConnection *_connection;
    NSMutableDictionary *_participantControllers;
    struct os_unfair_lock_s _participantsLock;
    unsigned long long _connectionRetryCount;
    NSObject<OS_dispatch_source> *_timer;
    CPParticipant *_cachedLocalParticipant;
    CPBroadcastLink *_broadcastLink;
    unsigned int _reliableLinkPriority;
    unsigned int _unreliableLinkPriority;
    NSObject<OS_dispatch_queue> *_networkQueue;
    id <CPCoreServiceObserver> _observer;
}

+ (_Bool)_hasEntitlements;
+ (CDUnknownBlockType)xpcConnectionInterfaceConfigurator;
+ (void)setXpcConnectionInterfaceConfigurator:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
@property(nonatomic) unsigned int unreliableLinkPriority; // @synthesize unreliableLinkPriority=_unreliableLinkPriority;
@property(nonatomic) unsigned int reliableLinkPriority; // @synthesize reliableLinkPriority=_reliableLinkPriority;
@property(nonatomic) __weak id <CPCoreServiceObserver> observer; // @synthesize observer=_observer;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *networkQueue; // @synthesize networkQueue=_networkQueue;
- (void)didFailWithError:(id)arg1;
- (void)participantDidLeaveSession:(id)arg1;
- (void)participantDidJoinSession:(id)arg1;
- (void)willInitiateAppSharingRequest:(id)arg1 sharingHandler:(CDUnknownBlockType)arg2;
- (void)didInitiateAppSharingRequest:(id)arg1;
- (void)didReceiveAppSharingRequestFrom:(id)arg1 sharingRequest:(id)arg2;
- (void)participantDidLaunchSharedApp:(id)arg1 appBundleId:(id)arg2;
- (void)sessionDidChange:(id)arg1;
- (void)sessionDidEnd:(id)arg1;
- (void)sessionDidStart:(id)arg1;
- (oneway void)sendAppSharingRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (oneway void)requestConnectionObjectForRemoteParticipant:(id)arg1 linkType:(unsigned char)arg2 completion:(CDUnknownBlockType)arg3;
- (oneway void)isConnectedToSession:(CDUnknownBlockType)arg1;
- (oneway void)getConnectedParticipantsWithReply:(CDUnknownBlockType)arg1;
- (oneway void)currentlySharedAppsWithReply:(CDUnknownBlockType)arg1;
- (oneway void)activeSharingRequestsWithReply:(CDUnknownBlockType)arg1;
- (oneway void)activeSession:(CDUnknownBlockType)arg1;
- (oneway void)activeSceneSharingRequestsWithReply:(CDUnknownBlockType)arg1;
- (oneway void)localAccountName:(CDUnknownBlockType)arg1;
- (void)sendUnicastData:(id)arg1 ofType:(unsigned char)arg2 toParticipants:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)broadcastUnreliableData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)removeSessionObserver:(id)arg1;
- (id)reservedLinkForRemoteParticipant:(id)arg1 ofType:(unsigned char)arg2;
- (id)connectedParticipants;
- (id)allParticipants;
- (_Bool)isLoggedIn;
- (void)_closeBroadcastLink;
- (void)_setupBroadcastLink;
- (void)_tearDownTimer;
- (id)_createDispatchTimer:(double)arg1 queue:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)_retryConnection;
- (void)_tearDownParticipants;
- (id)_connectedParticipantsUnsafe;
- (void)_getConnectedParticipantsWithReply:(CDUnknownBlockType)arg1;
- (void)requestBroadcastConnectionForService:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestConnectionObjectForRemoteParticipantSync:(id)arg1 linkType:(unsigned char)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_participantDidLeaveSession:(id)arg1;
- (void)_participantDidJoinSession:(id)arg1;
- (void)_participantProcessConnectedFrom:(id)arg1;
- (void)_participantProcessDisconnectedFrom:(id)arg1;
- (id)_synchronousRemoteObjectProxyWithErrorHandler:(CDUnknownBlockType)arg1;
- (void)didReceiveData:(id)arg1 ofType:(unsigned char)arg2 from:(id)arg3;
- (void)participant:(id)arg1 didBecomeAvailable:(_Bool)arg2;
- (void)didReceiveBroadcastData:(id)arg1 from:(id)arg2;
@property(readonly, nonatomic) CPParticipant *localParticipant;
- (id)remoteObjectProxyWithErrorHandler:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) id <CPCoreService> remoteObjectProxy;
- (void)dealloc;
- (void)resetPriorityForUnreliableLink:(unsigned int)arg1;
- (void)resetPriorityForReliableLink:(unsigned int)arg1;
- (id)reLinkForRemoteParticipant:(id)arg1 ofType:(unsigned char)arg2;
- (void)prefetchParticipants;
- (id)serverXPCInterface;
- (id)clientXPCInterface;
- (id)machServiceName;
@property(readonly, nonatomic) NSXPCConnection *xpcConnection;
- (id)initWithObserver:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

