//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BKSProcessAssertion, NSString;

@interface CPProcessAssertion : NSObject
{
    NSString *_bundleIdentifier;
    BKSProcessAssertion *_processAssertion;
}

+ (id)processAssertionNameForBundleIdentifier:(id)arg1;
+ (id)processAssertionWithBundleIdentifier:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) BKSProcessAssertion *processAssertion; // @synthesize processAssertion=_processAssertion;
@property(readonly, copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)name;
- (void)acquireWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithBundleIdentifier:(id)arg1;

@end

