//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <BiomePubSub/BPSSubscriber-Protocol.h>

@class NSDate, NSString;
@protocol BPSSubscriber;

@interface _BPSDebounceInner : NSObject <BPSSubscriber>
{
    struct os_unfair_lock_s _lock;
    CDUnknownBlockType _getTimestamp;
    id <BPSSubscriber> _downstream;
    double _dueTime;
    id _lastEvent;
    NSDate *_lastArrivalTimestamp;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDate *lastArrivalTimestamp; // @synthesize lastArrivalTimestamp=_lastArrivalTimestamp;
@property(retain, nonatomic) id lastEvent; // @synthesize lastEvent=_lastEvent;
@property(nonatomic) double dueTime; // @synthesize dueTime=_dueTime;
@property(retain, nonatomic) id <BPSSubscriber> downstream; // @synthesize downstream=_downstream;
- (void)receiveSubscription:(id)arg1;
- (long long)receiveInput:(id)arg1;
- (void)receiveCompletion:(id)arg1;
- (void)cancel;
- (id)initWithDownstream:(id)arg1 for:(double)arg2 getTimestamp:(CDUnknownBlockType)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

