//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class BPSCorrelateHandler, BPSCorrelateOrderedMerge;
@protocol BPSPublisher;

@interface BPSCorrelate
{
    BPSCorrelateOrderedMerge *_merger;
    id <BPSPublisher> _prior;
    id <BPSPublisher> _current;
    BPSCorrelateHandler *_correlateHandler;
}

+ (id)publisherWithPublisher:(id)arg1 upstreams:(id)arg2 bookmarkState:(id)arg3;
+ (long long)correlateSourceForIndex:(long long)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) BPSCorrelateHandler *correlateHandler; // @synthesize correlateHandler=_correlateHandler;
@property(readonly, nonatomic) id <BPSPublisher> current; // @synthesize current=_current;
@property(readonly, nonatomic) id <BPSPublisher> prior; // @synthesize prior=_prior;
- (_Bool)canStoreInternalStateInBookmark;
- (id)bookmarkableUpstreams;
- (void)subscribe:(id)arg1;
- (id)initWithPrior:(id)arg1 current:(id)arg2 comparator:(CDUnknownBlockType)arg3 correlateHandler:(id)arg4;
- (id)initWithPrior:(id)arg1 current:(id)arg2 comparator:(CDUnknownBlockType)arg3 updatedInitialContext:(id)arg4 correlateHandler:(id)arg5;
- (id)init;

@end

