//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Silex/NSObject-Protocol.h>

@class NSError, SXPlaybackCoordinator;

@protocol SXVideoPlaybackObserver <NSObject>

@optional
- (void)mediaSelectionOptionsAvailabilityChangedForPlaybackCoordinator:(SXPlaybackCoordinator *)arg1;
- (void)playbackCoordinatorStateChanged:(SXPlaybackCoordinator *)arg1;
- (void)playbackCoordinator:(SXPlaybackCoordinator *)arg1 loadingProgressed:(double)arg2;
- (void)playbackCoordinator:(SXPlaybackCoordinator *)arg1 timeElapsed:(double)arg2 duration:(double)arg3;
- (void)playbackCoordinator:(SXPlaybackCoordinator *)arg1 playbackFailedWithError:(NSError *)arg2;
- (void)playbackCoordinatorFinishedPlayback:(SXPlaybackCoordinator *)arg1;
- (void)playbackCoordinatorPausedPlayback:(SXPlaybackCoordinator *)arg1;
- (void)playbackCoordinatorResumedPlayback:(SXPlaybackCoordinator *)arg1;
- (void)playbackCoordinatorStartedPlayback:(SXPlaybackCoordinator *)arg1;
@end

