//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <PhotosGraph/PGGraphLocalizable-Protocol.h>

@class NSString, PGGraphBusinessCategoryNodeCollection;

@interface PGGraphBusinessCategoryNode <PGGraphLocalizable>
{
    NSString *_label;
}

+ (id)filterWithCategory:(id)arg1;
+ (id)filterWithCategories:(id)arg1;
+ (id)filter;
+ (id)businessOfCategory;
- (void).cxx_destruct;
- (id)label;
@property(readonly, nonatomic) PGGraphBusinessCategoryNodeCollection *collection;
@property(readonly, nonatomic) NSString *localizedName;
- (unsigned short)domain;
- (id)initWithLabel:(id)arg1 domain:(unsigned short)arg2 weight:(float)arg3 properties:(id)arg4;
- (id)initWithLabel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

