//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC9AACClientP33_5888192FE4890FBCEE84B63B946F5CEA26AECAssessmentModeAssertion : _TtCs12_SwiftObject
{
    MISSING_TYPE *conduit;
    MISSING_TYPE *initialState;
    MISSING_TYPE *invalidationHandler;
    MISSING_TYPE *stateAntiphony;
    MISSING_TYPE *antiphonyMembership;
    MISSING_TYPE *stateSubscription;
}

@end

