//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <LocalSpeechRecognitionBridge/NSCopying-Protocol.h>
#import <LocalSpeechRecognitionBridge/NSSecureCoding-Protocol.h>

@class CLLocation, NSArray, NSString;

@interface LBLocalSpeechRecognitionSettings : NSObject <NSCopying, NSSecureCoding>
{
    NSString *_requestId;
    NSString *_inputOrigin;
    unsigned long long _speechRecognitionTask;
    CLLocation *_location;
    NSArray *_jitGrammar;
    NSString *_overrideModelPath;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *overrideModelPath; // @synthesize overrideModelPath=_overrideModelPath;
@property(readonly, nonatomic) NSArray *jitGrammar; // @synthesize jitGrammar=_jitGrammar;
@property(readonly, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(readonly, nonatomic) unsigned long long speechRecognitionTask; // @synthesize speechRecognitionTask=_speechRecognitionTask;
@property(readonly, nonatomic) NSString *inputOrigin; // @synthesize inputOrigin=_inputOrigin;
@property(readonly, nonatomic) NSString *requestId; // @synthesize requestId=_requestId;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)initWithRequestId:(id)arg1 inputOrigin:(id)arg2 speechRecognitionTaskName:(unsigned long long)arg3 location:(id)arg4 jitGrammar:(id)arg5 overrideModelPath:(id)arg6;
- (id)initWithRequestId:(id)arg1 inputOrigin:(id)arg2 speechRecognitionTaskName:(unsigned long long)arg3 location:(id)arg4 jitGrammar:(id)arg5;

@end

