//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <DoNotDisturbServer/NSObject-Protocol.h>

@class NSDictionary;

@protocol DNDSBackingStoreRecord <NSObject>
+ (id)newWithDictionaryRepresentation:(NSDictionary *)arg1;
- (NSDictionary *)dictionaryRepresentation;
@end

