//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC7NewsUI231AudioFeedBlueprintLayoutBuilder : _TtCs12_SwiftObject
{
    MISSING_TYPE *feedLayoutSolver;
    MISSING_TYPE *audioFeedTitleViewLayoutAttributesFactory;
    MISSING_TYPE *feedLayoutContextFactory;
    MISSING_TYPE *sectionDecorationFactory;
    MISSING_TYPE *bundleSubscriptionManager;
    MISSING_TYPE *audioFeedPlacardLayoutAttributesFactory;
}

@end

