//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC7NewsUI221PDFReplicaCoordinator : _TtCs12_SwiftObject
{
    MISSING_TYPE *delegate;
    MISSING_TYPE *pages;
    MISSING_TYPE *issue;
    MISSING_TYPE *tracker;
}

@end

