//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <MobileTimer/MTSyncChangeStore-Protocol.h>

@class NSString;
@protocol NAScheduler;

@interface MTPersistentSyncChangeStore : NSObject <MTSyncChangeStore>
{
    id <NAScheduler> _archiverScheduler;
    NSString *_syncDataPath;
    NSString *_syncDataFile;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *syncDataFile; // @synthesize syncDataFile=_syncDataFile;
@property(copy, nonatomic) NSString *syncDataPath; // @synthesize syncDataPath=_syncDataPath;
@property(readonly, nonatomic) id <NAScheduler> archiverScheduler; // @synthesize archiverScheduler=_archiverScheduler;
- (void)_removeSyncDataFile;
- (id)loadChanges;
- (void)persistChanges:(id)arg1;
- (void)setupSyncDataFileForDataModel:(id)arg1;
- (id)initWithDataModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

