//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <TelephonyUtilities/NSSecureCoding-Protocol.h>

@class NSNumber;

@interface TUConversationParticipantPresentationContext : NSObject <NSSecureCoding>
{
    unsigned long long _participantIdentifier;
    unsigned long long _videoQuality;
    NSNumber *_visibility;
    NSNumber *_prominence;
    struct CGRect _spatialPosition;
}

+ (_Bool)supportsSecureCoding;
@property(readonly, nonatomic) struct CGRect spatialPosition; // @synthesize spatialPosition=_spatialPosition;
@property(readonly, nonatomic) NSNumber *prominence; // @synthesize prominence=_prominence;
@property(readonly, nonatomic) NSNumber *visibility; // @synthesize visibility=_visibility;
@property(readonly, nonatomic) unsigned long long videoQuality; // @synthesize videoQuality=_videoQuality;
@property(readonly, nonatomic) unsigned long long participantIdentifier; // @synthesize participantIdentifier=_participantIdentifier;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (id)initWithParticipantIdentifier:(unsigned long long)arg1 videoQuality:(unsigned long long)arg2 visibility:(id)arg3 prominence:(id)arg4 spatialPosition:(struct CGRect)arg5;

@end

