//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSURL, SAHAAction;

@interface SAHASceneAction
{
}

+ (id)sceneActionWithDictionary:(id)arg1 context:(id)arg2;
+ (id)sceneAction;
@property(copy, nonatomic) NSURL *entityId;
@property(retain, nonatomic) SAHAAction *action;
- (id)encodedClassName;
- (id)groupIdentifier;

@end

