//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSNumber, NSString, SAReminderRecurrence, SAReminderTrigger;

@interface SAReminderListObject
{
}

+ (id)listObjectWithDictionary:(id)arg1 context:(id)arg2;
+ (id)listObject;
@property(copy, nonatomic) NSNumber *totalNumOfReminders;
@property(copy, nonatomic) NSArray *remindersToCreate;
@property(copy, nonatomic) NSArray *reminders;
@property(retain, nonatomic) SAReminderTrigger *reminderTrigger;
@property(retain, nonatomic) SAReminderRecurrence *recurrence;
@property(copy, nonatomic) NSString *name;
@property(copy, nonatomic) NSString *accountName;
- (id)encodedClassName;
- (id)groupIdentifier;

@end

