//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSString;

@interface NWKUIAQILinearModel
{
    NSArray *_colorIndices;
    NSString *_index;
    double _percentage;
}

- (void).cxx_destruct;
@property(readonly) double percentage; // @synthesize percentage=_percentage;
@property(readonly) NSString *index; // @synthesize index=_index;
@property(readonly) NSArray *colorIndices; // @synthesize colorIndices=_colorIndices;
- (id)initWithName:(id)arg1 label:(id)arg2 categoryDescription:(id)arg3 color:(id)arg4 date:(id)arg5 expiration:(id)arg6 colorIndices:(id)arg7 index:(id)arg8 percentage:(double)arg9;
- (id)initWithAirQualityConditions:(id)arg1;

@end

