//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TSPersistence/NSObject-Protocol.h>
#import <TSPersistence/TSPAllDataProviding-Protocol.h>

@class NSArray, NSDictionary, NSIndexSet;

@protocol TSPDataManaging <TSPAllDataProviding, NSObject>
@property(readonly, nonatomic) NSDictionary *digestToDataMap;
@property(readonly, nonatomic) NSDictionary *identifierToDataMap;
@property(readonly, nonatomic) NSIndexSet *allDataIdentifiers;
@property(readonly, nonatomic) NSArray *allData;
@end

