//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC8StocksUI15StockViewStyler : _TtCs12_SwiftObject
{
    MISSING_TYPE *cachedSymbolFont;
    MISSING_TYPE *cachedCompanyFont;
    MISSING_TYPE *cachedPriceFont;
    MISSING_TYPE *cachedPriceDisplayFont;
    MISSING_TYPE *cachedExchangeFont;
    MISSING_TYPE *cachedCurrencyFont;
    MISSING_TYPE *baseStyler;
}

@end

