//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

#import <ExtensionKit/_EXConnectionCreating-Protocol.h>
#import <ExtensionKit/_EXHostSessionDelegate-Protocol.h>

@class NSString, _EXHostSession, _EXHostViewControllerConfiguration;
@protocol _EXHostViewControllerDelegate;

@interface _EXHostViewController : UIViewController <_EXHostSessionDelegate, _EXConnectionCreating>
{
    UIViewController<_EXHostViewControllerDelegate> *_placeholderViewController;
    id <_EXHostViewControllerDelegate> _delegate;
    _EXHostSession *_session;
    UIViewController *_embededViewController;
}

- (void).cxx_destruct;
@property(retain) UIViewController *embededViewController; // @synthesize embededViewController=_embededViewController;
@property(retain) _EXHostSession *session; // @synthesize session=_session;
@property(nonatomic) __weak id <_EXHostViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIViewController<_EXHostViewControllerDelegate> *placeholderViewController; // @synthesize placeholderViewController=_placeholderViewController;
- (id)makeXPCConnectionWithError:(id *)arg1;
- (void)embedViewController:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)hostSessionDidInvalidate:(id)arg1;
- (void)hostSessionViewControllerReady:(id)arg1;
- (void)hostSessionDidPrepareForHosting:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
@property(copy, nonatomic) _EXHostViewControllerConfiguration *configuration; // @dynamic configuration;
- (void)dealloc;
- (id)initWithConfiguration:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

