//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CLSilo;
@protocol GEOMapServiceTicket, OS_dispatch_queue;

@interface CLGeocoderInternal : NSObject
{
    CDUnknownBlockType _geocodeCompletionHandler;
    id <GEOMapServiceTicket> _ticket;
    NSObject<OS_dispatch_queue> *_queue;
    CLSilo *_responseSilo;
}

@property(retain) CLSilo *responseSilo; // @synthesize responseSilo=_responseSilo;
- (void)dealloc;
- (id)init;

@end

