//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <AppStoreDaemon/NSCopying-Protocol.h>
#import <AppStoreDaemon/NSSecureCoding-Protocol.h>

@class NSDate, NSDictionary, NSNumber, NSString;

@interface ASDSoftwareUpdate : NSObject <NSCopying, NSSecureCoding>
{
    NSDate *_installDate;
    NSDictionary *_rawUpdateDictionary;
    NSDate *_timestamp;
    long long _updateState;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) long long updateState; // @synthesize updateState=_updateState;
@property(copy, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, nonatomic) NSDictionary *rawUpdateDictionary; // @synthesize rawUpdateDictionary=_rawUpdateDictionary;
@property(copy, nonatomic) NSDate *installDate; // @synthesize installDate=_installDate;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) NSDictionary *updateDictionary;
@property(readonly, nonatomic) long long storeItemIdentifier;
- (id)releaseDate;
@property(readonly, nonatomic) long long parentalControlsRank;
@property(readonly, nonatomic) NSNumber *externalVersionIdentifier;
@property(readonly, nonatomic) NSString *buyParams;
@property(readonly, nonatomic) NSString *bundleIdentifier;
- (id)initWithUpdateDictionary:(id)arg1;

@end

