//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MCTouchInput
{
    double _radius;
    double _timestamp;
    struct CGPoint _touchPoint;
}

@property(readonly, nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, nonatomic) double radius; // @synthesize radius=_radius;
@property(readonly, nonatomic) struct CGPoint touchPoint; // @synthesize touchPoint=_touchPoint;
- (id)description;
- (_Bool)canComposeNew:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTouchPoint:(struct CGPoint)arg1 radius:(double)arg2 timestamp:(double)arg3;

@end

