//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TIGeocodeCompletionHandlerHolder : NSObject
{
    CDUnknownBlockType _geocodeCompletionHandler;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType geocodeCompletionHandler; // @synthesize geocodeCompletionHandler=_geocodeCompletionHandler;

@end

