//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface TIKeyboardActivityContext : NSObject
{
    unsigned long long _fromState;
    unsigned long long _toState;
    unsigned long long _excessMemoryInBytes;
}

+ (id)contextFromState:(unsigned long long)arg1 toState:(unsigned long long)arg2;
@property(nonatomic) unsigned long long excessMemoryInBytes; // @synthesize excessMemoryInBytes=_excessMemoryInBytes;
@property(nonatomic) unsigned long long toState; // @synthesize toState=_toState;
@property(nonatomic) unsigned long long fromState; // @synthesize fromState=_fromState;

@end

