//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <EmailDaemon/EDPersistenceDatabaseProtectedSchemaProvider-Protocol.h>
#import <EmailDaemon/EDPersistenceDatabaseSchemaProvider-Protocol.h>
#import <EmailDaemon/EFContentProtectionObserver-Protocol.h>

@class EDPersistenceDatabase, NSBackgroundActivityScheduler, NSString;
@protocol OS_dispatch_queue;

@interface EDRemoteContentPersistence : NSObject <EFContentProtectionObserver, EDPersistenceDatabaseSchemaProvider, EDPersistenceDatabaseProtectedSchemaProvider>
{
    long long _currentRowCount;
    long long _protectedRowCount;
    _Bool _useAdditionalTable;
    EDPersistenceDatabase *_database;
    NSObject<OS_dispatch_queue> *_contentProtectionQueue;
    NSBackgroundActivityScheduler *_analyticsScheduler;
    unsigned long long _maximumRemoteContentLinks;
    unsigned long long _pruneThreshold;
}

+ (id)_remoteContentLinksTableSchemaWithName:(id)arg1;
+ (id)protectedTablesAndForeignKeysToResolve:(id *)arg1;
+ (id)tablesAndForeignKeysToResolve:(id *)arg1 associationsToResolve:(id *)arg2;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long pruneThreshold; // @synthesize pruneThreshold=_pruneThreshold;
@property(nonatomic) unsigned long long maximumRemoteContentLinks; // @synthesize maximumRemoteContentLinks=_maximumRemoteContentLinks;
@property(readonly, nonatomic) NSBackgroundActivityScheduler *analyticsScheduler; // @synthesize analyticsScheduler=_analyticsScheduler;
@property(readonly, nonatomic) _Bool useAdditionalTable; // @synthesize useAdditionalTable=_useAdditionalTable;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *contentProtectionQueue; // @synthesize contentProtectionQueue=_contentProtectionQueue;
@property(readonly, nonatomic) EDPersistenceDatabase *database; // @synthesize database=_database;
- (void)test_tearDown;
- (id)_getRemoteContentURLInfoForTable:(id)arg1 orderedBy:(long long)arg2 inReverseOrder:(_Bool)arg3 limit:(long long)arg4 connection:(id)arg5 error:(id *)arg6;
- (id)getRemoteContentURLInfoOrderedBy:(long long)arg1 inReverseOrder:(_Bool)arg2 limit:(long long)arg3 error:(id *)arg4;
- (void)contentProtectionStateChanged:(int)arg1 previousState:(int)arg2;
- (void)_refillFromAdditionalTable;
- (_Bool)pruneAllRemoteContentLinksWithMinimumCount:(unsigned long long)arg1;
- (unsigned long long)countOfUnrequestedLinks;
- (unsigned long long)countOfLinksLastSeenSince:(id)arg1;
- (id)remoteContentLinksBelowCount:(unsigned long long)arg1 limit:(unsigned long long)arg2;
- (_Bool)updateRequestCountForRemoteContentLinks:(id)arg1 updateLastSeen:(_Bool)arg2;
- (_Bool)_addRemoteContentLinks:(id)arg1 withDate:(id)arg2 toTable:(id)arg3 withConnection:(id)arg4 newLinks:(id *)arg5;
- (_Bool)addRemoteContentLinks:(id)arg1 newLinks:(id *)arg2;
- (long long)_rowCountForTable:(id)arg1;
- (void)_initializeProtectedRowCount;
- (void)_initializeCurrentRowCount;
- (void)_decrementProtectedRowCountBy:(unsigned long long)arg1;
- (void)_incrementProtectedRowCountBy:(unsigned long long)arg1;
- (void)_decrementCurrentRowCountBy:(unsigned long long)arg1;
- (void)_incrementCurrentRowCountBy:(unsigned long long)arg1;
- (unsigned long long)_protectedRowCount;
- (unsigned long long)_currentRowCount;
- (void)dealloc;
- (id)initWithDatabase:(id)arg1 useAdditionalTable:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

