//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSArray.h>

@interface NSArray (BacklightServices)
- (id)bls_boundedDescriptionWithMax:(long long)arg1 transformer:(CDUnknownBlockType)arg2;
- (id)bls_boundedDescriptionWithMax:(long long)arg1;
- (id)bls_boundedDescriptionWithTransformer:(CDUnknownBlockType)arg1;
- (id)bls_boundedDescription;
@end

