//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class UIView;

__attribute__((visibility("hidden")))
@interface VKCQuickActionLayoutInfo : NSObject
{
    _Bool _hidden;
    UIView *_view;
    struct CGRect _frame;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(retain, nonatomic) UIView *view; // @synthesize view=_view;

@end

