//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MTEventHandler, NSArray, NSString;

__attribute__((visibility("hidden")))
@interface MTEventHandlerRegistration
{
    NSString *_registeredName;
    Class _eventHandlerClass;
    NSArray *_eventData;
    MTEventHandler *_eventHandler;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MTEventHandler *eventHandler; // @synthesize eventHandler=_eventHandler;
@property(retain, nonatomic) NSArray *eventData; // @synthesize eventData=_eventData;
@property(retain, nonatomic) Class eventHandlerClass; // @synthesize eventHandlerClass=_eventHandlerClass;
@property(retain, nonatomic) NSString *registeredName; // @synthesize registeredName=_registeredName;
- (id)initWithMetricsKit:(id)arg1 name:(id)arg2 class:(Class)arg3 eventData:(id)arg4;

@end

