//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <AppleMediaServicesUI/NSSecureCoding-Protocol.h>

@class NSData;

@interface AMSPaymentVerificationTokenResult : NSObject <NSSecureCoding>
{
    NSData *_tokenData;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSData *tokenData; // @synthesize tokenData=_tokenData;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithTokenData:(id)arg1;

@end

