//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <Navigation/NSSecureCoding-Protocol.h>

@class NSArray, NSDictionary, NSUUID;

@interface MNGuidanceLaneInfo : NSObject <NSSecureCoding>
{
    _Bool _isForManeuver;
    NSUUID *_uniqueID;
    NSArray *_lanes;
    NSDictionary *_variableOverrides;
    long long _distanceDetailLevel;
    NSArray *_instructions;
}

+ (_Bool)supportsSecureCoding;
@property(readonly, nonatomic) NSArray *instructions; // @synthesize instructions=_instructions;
@property(readonly, nonatomic) long long distanceDetailLevel; // @synthesize distanceDetailLevel=_distanceDetailLevel;
@property(readonly, nonatomic) NSDictionary *variableOverrides; // @synthesize variableOverrides=_variableOverrides;
@property(readonly, nonatomic) NSArray *lanes; // @synthesize lanes=_lanes;
@property(readonly, nonatomic) _Bool isForManeuver; // @synthesize isForManeuver=_isForManeuver;
@property(readonly, nonatomic) NSUUID *uniqueID; // @synthesize uniqueID=_uniqueID;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (id)initWithID:(id)arg1 isForManeuver:(_Bool)arg2 lanes:(id)arg3 instructions:(id)arg4 variableOverrides:(id)arg5 distanceDetailLevel:(long long)arg6;

@end

