//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC17KnowledgeGraphKit17GraphStoreManager : _TtCs12_SwiftObject
{
    MISSING_TYPE *$defaultActor;
    MISSING_TYPE *url;
    MISSING_TYPE *readRunningCount;
    MISSING_TYPE *readFeeding;
    MISSING_TYPE *closed;
    MISSING_TYPE *readStoreBooking;
    MISSING_TYPE *readOnlyStores;
    MISSING_TYPE *readWriteStore;
    MISSING_TYPE *executionQueue;
    MISSING_TYPE *readFeederQueue;
    MISSING_TYPE *writeFeederQueue;
}

@end

