//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class KGNodeFilter, MARelation;

@interface MANodeFilter
{
}

+ (_Bool)scanInstance:(out id *)arg1 withScanner:(id)arg2;
@property(readonly, nonatomic) MARelation *relation;
- (void)appendVisualStringToString:(id)arg1;
@property(readonly, nonatomic) KGNodeFilter *kgNodeFilter;
- (_Bool)matchesNode:(id)arg1;

@end

