//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC11SessionCore14ProcessMonitor : _TtCs12_SwiftObject
{
    MISSING_TYPE *_lock_monitor;
    MISSING_TYPE *_lock_monitoredBundleIdentifiers;
    MISSING_TYPE *_lock_pidsByBundleIdentifier;
    MISSING_TYPE *_lock_statesByPid;
    MISSING_TYPE *lock;
}

@end

