//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface CDPDXPCEventObserver : NSObject
{
    NSMutableArray *_eventListeners;
}

+ (id)sharedObserver;
- (void).cxx_destruct;
- (void)_setupDistributedListener;
- (void)_setupDarwinListener;
- (void)start;
- (void)registerListener:(id)arg1;

@end

