//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSData.h>

@interface NSData (Encryption)
- (id)_randomDataGeneratorWithNumberOfBytes:(unsigned long long)arg1;
- (id)AESGCM256DecryptedDataWithSymmetricKey:(id)arg1;
- (id)AESGCM256EncryptedDataWithSymmetricKey:(id)arg1;
- (id)cdp_unarchivedRoot;
@end

