//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface (null) (NewsArticles5)
- (void)resetZoom;
- (_Bool)canResetZoom;
- (void)zoomOut;
- (void)zoomIn;
- (_Bool)canZoomOut;
- (_Bool)canZoomIn;
- (void)decreaseTextSize;
- (void)increaseTextSize;
- (_Bool)canDecreaseTextSize;
- (_Bool)canIncreaseTextSize;
@end

