//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <NewsCore/FCCommand.h>

@class MISSING_TYPE;

@interface _TtC12NewsArticles20ReportConcernCommand : FCCommand
{
    MISSING_TYPE *concern;
    MISSING_TYPE *headline;
    MISSING_TYPE *comments;
}

- (void).cxx_destruct;
- (id)init;
- (void)executeWithContext:(id)arg1 delegate:(id)arg2 qualityOfService:(long long)arg3;
- (id)initWithCoder:(id)arg1;

@end

