//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC20FaceTimeMessageStore20CoreDataMessageStore : _TtCs12_SwiftObject
{
    MISSING_TYPE *config;
    MISSING_TYPE *storeType;
    MISSING_TYPE *userDefaults;
    MISSING_TYPE *accountStatus;
    MISSING_TYPE *migrationStatus;
    MISSING_TYPE *notificationCenter;
    MISSING_TYPE *storeManager;
    MISSING_TYPE *delegate;
}

- (void)didSave:(id)arg1;
- (void)didResetSync:(id)arg1;
- (void)willResetSync:(id)arg1;

@end

