//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TSCH3DGetBoundsRenderProcessor
{
    int _mode;
    struct ObjectBounds _bounds;
}

- (id).cxx_construct;
- (void).cxx_destruct;
@property(nonatomic) int mode; // @synthesize mode=_mode;
- (void)submit:(id)arg1;
- (void)extend2DProjectedBounds:(void *)arg1;
- (void)resetBounds;
@property(readonly, nonatomic) const void *bounds;
- (id)init;

@end

