//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <TSText/TSWPParagraphStyle.h>

@interface TSWPParagraphStyle (TSCH3DGetAndCacheAscent)
+ (id)presetStyleDescriptorForOrdinal:(unsigned long long)arg1;
- (double)ascent;
@end

