//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CarPlaySupport/NSObject-Protocol.h>

@class CPSTemplateInstance;

@protocol CPSTemplateInstanceDelegate <NSObject>
- (void)didDisconnectTemplateInstance:(CPSTemplateInstance *)arg1;
@end

