//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface NWOSAddressEndpoint
{
    struct sockaddr_storage address;
    struct ether_addr ethernet_address;
    char *hostname;
    int original_fd;
    unsigned short priority;
    unsigned int calculated_hostname:1;
}

- (void)setPriority:(unsigned short)arg1;
- (unsigned short)priority;
- (unsigned long long)getHash;
- (id)copyEndpoint;
- (_Bool)isEqualToEndpoint:(id)arg1 matchInterface:(_Bool)arg2 matchParent:(_Bool)arg3;
- (char *)createDescription:(_Bool)arg1;
- (const char *)hostname;
- (unsigned short)port;
- (id)copyDictionary;
- (unsigned int)type;
- (void)dealloc;

@end

