//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <System/OS_object.h>

@interface OS_network_proxy : OS_object
{
}

- (void)_dispose;

@end

