//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CKComposition, NSArray, NSIndexPath, NSSet;
@protocol CKCommunicationSafetyEDUScreenProtocol;

__attribute__((visibility("hidden")))
@interface CKCommunicationSafetyEDUScreenTwo
{
    _Bool _isYoungAgeGroup;
    _Bool _isSending;
    id <CKCommunicationSafetyEDUScreenProtocol> _delegate;
    NSIndexPath *_indexPath;
    CKComposition *_composition;
    NSSet *_sensitiveMediaObjects;
    NSArray *_identifiersOfShelvedImages;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *identifiersOfShelvedImages; // @synthesize identifiersOfShelvedImages=_identifiersOfShelvedImages;
@property(readonly, nonatomic) NSSet *sensitiveMediaObjects; // @synthesize sensitiveMediaObjects=_sensitiveMediaObjects;
@property(readonly, nonatomic) CKComposition *composition; // @synthesize composition=_composition;
@property(readonly, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(readonly, nonatomic) _Bool isSending; // @synthesize isSending=_isSending;
@property(readonly, nonatomic) _Bool isYoungAgeGroup; // @synthesize isYoungAgeGroup=_isYoungAgeGroup;
@property(nonatomic) __weak id <CKCommunicationSafetyEDUScreenProtocol> delegate; // @synthesize delegate=_delegate;
- (void)_notNowButtonPressed;
- (void)_acceptButtonPressed;
- (void)_messageButtonPressed;
- (void)addButtonsToTray;
- (void)configureSecondReceiveScreen;
- (void)configureSecondSendScreen;
- (id)initSecondReceivingEDUScreenWithItemIndexPath:(id)arg1;
- (id)initSecondSendingEDUScreenWithComposition:(id)arg1 withSensitiveMediaObjects:(id)arg2 withIdentifiersOfShelvedImages:(id)arg3;

@end

