//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray;
@protocol OS_dispatch_group;

__attribute__((visibility("hidden")))
@interface CKSendMenuPopoverAnimation : NSObject
{
    CDUnknownBlockType _completion;
    NSArray *_animators;
    NSObject<OS_dispatch_group> *_group;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSObject<OS_dispatch_group> *group; // @synthesize group=_group;
@property(copy, nonatomic) NSArray *animators; // @synthesize animators=_animators;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void)addCompletion:(CDUnknownBlockType)arg1;
- (void)startAnimation;
- (id)initWithAnimators:(id)arg1;

@end

