//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIView;

__attribute__((visibility("hidden")))
@interface CKUnreadCountLabelCell
{
    UIView *_leftSeparator;
    UIView *_rightSeparator;
}

@property(retain, nonatomic) UIView *rightSeparator; // @synthesize rightSeparator=_rightSeparator;
@property(retain, nonatomic) UIView *leftSeparator; // @synthesize leftSeparator=_leftSeparator;
- (void).cxx_destruct;
- (void)layoutSubviewsForContents;
- (id)initWithFrame:(struct CGRect)arg1;

@end

