//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreData/NSManagedObject.h>

@class NSData, NSString;

@interface AMDWorkflowInFlight : NSManagedObject
{
}

+ (id)fetchAllModelIds:(id *)arg1;
+ (id)fetchAllWorkflows:(id *)arg1;
+ (id)fetchAllWorkflowEntries:(id *)arg1;
+ (id)moveInflightWorkflowsToWorkflows:(id)arg1 forModelId:(id)arg2 withDomain:(long long)arg3 error:(id *)arg4;
+ (id)deleteAllInflightWorkflows:(id *)arg1;
+ (void)saveWorkflow:(id)arg1 forDomain:(long long)arg2 withCallUUID:(id)arg3 error:(id *)arg4;
+ (id)deleteWorkflowsForDomain:(long long)arg1 withModelId:(id)arg2 error:(id *)arg3;
+ (id)deleteWithPredicates:(id)arg1 error:(id *)arg2;
+ (id)getAllWorkflowsForDomain:(long long)arg1 withModelId:(id)arg2 error:(id *)arg3;
+ (id)fetchRequest;

// Remaining properties
@property(copy, nonatomic) NSString *callUUID; // @dynamic callUUID;
@property(nonatomic) long long creationTime; // @dynamic creationTime;
@property(nonatomic) short domain; // @dynamic domain;
@property(nonatomic) long long endTime; // @dynamic endTime;
@property(copy, nonatomic) NSString *modelId; // @dynamic modelId;
@property(nonatomic) long long startTime; // @dynamic startTime;
@property(copy, nonatomic) NSString *treatmentId; // @dynamic treatmentId;
@property(copy, nonatomic) NSString *useCaseId; // @dynamic useCaseId;
@property(retain, nonatomic) NSData *workflow; // @dynamic workflow;

@end

