//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSData, NSDate, NSDictionary;

@interface ICSuzeLeaseResponse : NSObject
{
    NSDate *_requestDate;
    NSDictionary *_responseDictionary;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDate *leaseExpirationDate;
@property(readonly, copy, nonatomic) NSData *clientData;
- (id)initWithResponseDictionary:(id)arg1 requestDate:(id)arg2;

@end

