//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <OnBoardingKit/OBWelcomeController.h>

@class MISSING_TYPE;

@interface _TtC28HealthExposureNotificationUI40OnboardingAddRegionWelcomeViewController : OBWelcomeController
{
    MISSING_TYPE *flow;
    MISSING_TYPE *primaryButton;
    MISSING_TYPE *secondaryButton;
}

- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 detailText:(id)arg2 icon:(id)arg3 contentLayout:(long long)arg4;
- (void)didTapSecondaryButton;
- (void)didTapPrimaryButton;
- (void)didTapHowExposureNotificationsWork;
- (void)viewDidLoad;

@end

