//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MPSNeuralNetwork/MPSNNTrainableNode-Protocol.h>

@class NSString;
@protocol MPSCNNConvolutionDataSource;

@interface MPSCNNConvolutionGradientNode <MPSNNTrainableNode>
{
    id <MPSCNNConvolutionDataSource> _weights;
    unsigned long long _trainingStyle;
}

+ (id)nodeWithSourceGradient:(id)arg1 sourceImage:(id)arg2 convolutionGradientState:(id)arg3 weights:(id)arg4;
@property(readonly, nonatomic) id <MPSCNNConvolutionDataSource> weights; // @synthesize weights=_weights;
@property(nonatomic) unsigned long long trainingStyle; // @synthesize trainingStyle=_trainingStyle;
@property(readonly, copy) NSString *debugDescription;
- (void)dealloc;
- (struct FilterGraphNode *)newFilterNode;
- (id)initWithGradientImages:(id)arg1 forwardFilter:(id)arg2;
- (id)initWithSourceGradient:(id)arg1 sourceImage:(id)arg2 convolutionGradientState:(id)arg3 weights:(id)arg4;
- (id)initWithSourceGradient:(id)arg1 sourceImage:(id)arg2 gradientState:(id)arg3 weights:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

