//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class WBSPasswordPatternMatch;

__attribute__((visibility("hidden")))
@interface WBSPasswordPatternPartialSolution : NSObject
{
    WBSPasswordPatternMatch *_patternMatch;
    double _guessesRequiredWithoutPatternCountPenalty;
    double _guessesRequiredWithPatternCountPenalty;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) double guessesRequiredWithPatternCountPenalty; // @synthesize guessesRequiredWithPatternCountPenalty=_guessesRequiredWithPatternCountPenalty;
@property(readonly, nonatomic) double guessesRequiredWithoutPatternCountPenalty; // @synthesize guessesRequiredWithoutPatternCountPenalty=_guessesRequiredWithoutPatternCountPenalty;
@property(readonly, nonatomic) WBSPasswordPatternMatch *patternMatch; // @synthesize patternMatch=_patternMatch;
- (id)initWithPatternMatch:(id)arg1 guessesRequiredWithoutPatternCountPenalty:(double)arg2 withPatternCountPenalty:(double)arg3;

@end

