//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSFileManager, NSURL;

@interface CHSScreenshotManager : NSObject
{
    NSURL *_baseURL;
    NSFileManager *_fileManager;
}

+ (id)sharedManager;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSFileManager *fileManager; // @synthesize fileManager=_fileManager;
@property(readonly, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
- (id)URLForWidget:(id)arg1 metrics:(id)arg2 inColorScheme:(long long)arg3 createIntermediateDirectories:(_Bool)arg4;
- (id)snapshotContextForWidget:(id)arg1 metrics:(id)arg2 inColorScheme:(long long)arg3;
- (void)deleteAllCachedScreenshots;
- (id)initWithDirectory:(id)arg1 fileManager:(id)arg2;

@end

