//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MXAverage;

@interface MXFramerateMetric
{
    MXAverage *_averageFramerate;
}

+ (_Bool)supportsSecureCoding;
@property(readonly) MXAverage *averageFramerate; // @synthesize averageFramerate=_averageFramerate;
- (void).cxx_destruct;
- (id)toDictionary;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithAverageFramerate:(id)arg1;

@end

