//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface UITableViewIndexAccessibility
{
}

+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (id)_accessibilityKeyCommands;
- (long long)_accessibilitySortPriority;
- (_Bool)isAccessibilityElement;
- (unsigned long long)accessibilityTraits;
- (id)accessibilityLabel;
- (_Bool)_updateSectionForTouch:(id)arg1 withEvent:(id)arg2;
- (id)accessibilityFlowToElements;
- (id)_accessibilityValueToPost:(id)arg1;
- (struct CGPoint)accessibilityActivationPoint;
- (void)accessibilityDecrement;
- (void)accessibilityIncrement;
- (void)_accessibilityMoveToIndexAtPosition:(long long)arg1;
- (void)_accessibilityBumpValue:(_Bool)arg1;
- (void)_accessibilityJumpToTableIndex:(id)arg1;
- (long long)_accessibilityTableIndexAdjustment;
- (id)_accessibilityIndexData;

@end

