//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class SBSwitcherModifier;

@interface SBAddModifierSwitcherEventResponse
{
    SBSwitcherModifier *_modifier;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) SBSwitcherModifier *modifier; // @synthesize modifier=_modifier;
- (long long)type;
- (id)initWithModifier:(id)arg1;

@end

