//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableSet;
@protocol FBSServiceFacilityClientHandle;

@interface SBButtonConsumerClient : NSObject
{
    _Bool _entitledToConsumeButtonsInBackground;
    _Bool _application;
    _Bool _runningVisible;
    _Bool _suspended;
    id <FBSServiceFacilityClientHandle> _systemServiceClient;
    NSMutableSet *_registrations;
}

@property(retain, nonatomic) NSMutableSet *registrations; // @synthesize registrations=_registrations;
@property(nonatomic, getter=isSuspended) _Bool suspended; // @synthesize suspended=_suspended;
@property(nonatomic, getter=isRunningVisible) _Bool runningVisible; // @synthesize runningVisible=_runningVisible;
@property(nonatomic, getter=isApplication) _Bool application; // @synthesize application=_application;
@property(nonatomic, getter=isEntitledToConsumeButtonsInBackground) _Bool entitledToConsumeButtonsInBackground; // @synthesize entitledToConsumeButtonsInBackground=_entitledToConsumeButtonsInBackground;
@property(retain, nonatomic) id <FBSServiceFacilityClientHandle> systemServiceClient; // @synthesize systemServiceClient=_systemServiceClient;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool canReceiveEvents;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;

@end

