//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSHashTable;
@protocol BSInvalidatable;

@interface SBDeviceOrientationUpdateManager : NSObject
{
    NSHashTable *_deferralAssertions;
    _Bool _deviceOrientationIsDirty;
    id <BSInvalidatable> _stateCaptureHandle;
    long long _lastUpdatedDeviceOrientation;
}

- (void).cxx_destruct;
@property(nonatomic) long long lastUpdatedDeviceOrientation; // @synthesize lastUpdatedDeviceOrientation=_lastUpdatedDeviceOrientation;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)succinctDescriptionBuilder;
- (id)succinctDescription;
- (id)description;
- (void)_enqueueOrientationUpdateToDeviceOrientation:(long long)arg1;
- (_Bool)_deviceOrientationUpdateNeededForOrientation:(long long)arg1;
- (void)_endDeferringOrientationUpdatesForAssertion:(id)arg1;
- (id)deviceOrientationUpdateDeferralAssertionWithReason:(id)arg1;
@property(readonly, nonatomic, getter=isCurrentlyDeferringOrientationUpdates) _Bool currentlyDeferringOrientationUpdates;
- (void)dealloc;
- (id)init;

@end

