//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class PETDistributionEventTracker, PETGoalConversionEventTracker;

@interface SBInteractionAfterWakeMetric
{
    PETGoalConversionEventTracker *_unlockTracker;
    PETDistributionEventTracker *_sessionTimeTracker;
    double _screenOnTimestamp;
    struct {
        _Bool usedQuickActionButton;
        _Bool scrolledInNotifications;
        _Bool longLookedNotification;
        _Bool interactedNotifcation;
        _Bool clearedNotifcations;
        _Bool activatedCamera;
        _Bool prewarmedCameraFalsePositive;
        _Bool cameraSwipeFailed;
        _Bool activatedControlCenter;
        _Bool activatedSpotlight;
        _Bool unlockDismissed;
    } _sessionInteractions;
    _Bool _shouldReport;
}

- (void).cxx_destruct;
- (id)init;
- (void)_trackSessionWithDuration:(double)arg1;
- (void)_trackUnlockConversion:(_Bool)arg1;
- (void)_trackUnlockOpportunity;
- (_Bool)_determineIfShouldReport;

@end

