//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface SBLockStateAggregator : NSObject
{
    unsigned long long _lockState;
}

+ (id)sharedInstance;
- (void)_updateLockState;
- (_Bool)hasAnyLockState;
- (unsigned long long)lockState;
- (id)description;
- (id)_descriptionForLockState:(unsigned long long)arg1;
- (void)dealloc;
- (id)init;

@end

