//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SpringBoardFoundation/SBFTouchPassThroughView.h>

@class SBMicroPIPTetheringMirrorContentPlaceholderView, UIView;

@interface SBMicroPIPTetheringMirrorView : SBFTouchPassThroughView
{
    SBMicroPIPTetheringMirrorContentPlaceholderView *_contentPlaceholderView;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIView *contentPlaceholderView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

