//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBAlertItemsControllerObserver-Protocol.h>
#import <SpringBoard/SBAssistantObserver-Protocol.h>
#import <SpringBoard/SBIdleTimerProviding-Protocol.h>
#import <SpringBoard/SBLayoutStateTransitionObserver-Protocol.h>
#import <SpringBoard/SBPIPContainerViewControllerObserver-Protocol.h>
#import <SpringBoard/SBPIPControllerAdapterContextProviding-Protocol.h>
#import <SpringBoard/SBPIPMorphAnimatorControllerDelegate-Protocol.h>
#import <SpringBoard/SBSensorActivityObserver-Protocol.h>
#import <SpringBoard/SBWorkspaceKeyboardFocusControllerObserver-Protocol.h>

@class BSCompoundAssertion, FBSDisplayLayoutMonitor, NSHashTable, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, SBIdleTimerCoordinatorHelper, SBPIPInteractionSettings, SBPIPInterruptionDebouncingTimer, SBPIPStashAssertion, SBPIPWindow, UIView;
@protocol BSInvalidatable, SBIdleTimerCoordinating, SBPIPControllerAdapter;

@interface SBPIPController : NSObject <SBPIPContainerViewControllerObserver, SBAlertItemsControllerObserver, SBAssistantObserver, SBSensorActivityObserver, SBWorkspaceKeyboardFocusControllerObserver, SBPIPControllerAdapterContextProviding, SBLayoutStateTransitionObserver, SBIdleTimerProviding, SBPIPMorphAnimatorControllerDelegate>
{
    id <BSInvalidatable> _stateCaptureInvalidatable;
    SBPIPInteractionSettings *_interactionSettings;
    double _windowLevel;
    _Bool _hasIdleTimerBehaviors;
    id <SBIdleTimerCoordinating> _idleTimerCoordinator;
    SBIdleTimerCoordinatorHelper *_idleTimerCoordinatorHelper;
    NSMutableArray *_windowLevelOverrideAssertions;
    NSMutableSet *_pictureInPictureWindowHiddenReasons;
    SBPIPWindow *_pictureInPictureWindow;
    struct UIEdgeInsets _pictureInPictureWindowMargin;
    NSMutableDictionary *_pictureInPictureInsetsForSource;
    _Bool _expectKeyboardVisible;
    NSMutableArray *_stashAssertions;
    NSHashTable *_interruptionAssertions;
    BSCompoundAssertion *_insetsOverrideAssertions;
    NSMutableDictionary *_cameraInterruptionAssertions;
    id <BSInvalidatable> _fullscreenModalElementInsetOverrideAssertion;
    SBPIPStashAssertion *_stashForInterruptionAssertion;
    SBPIPStashAssertion *_transitionStashAssertion;
    SBPIPInterruptionDebouncingTimer *_interruptionEndDebouncingTimer;
    _Bool _defaultToStashed;
    NSMutableSet *_pictureInPictureMorphAnimatorControllers;
    UIView *_keyboardInsetsVisualizerView;
    long long _unlockedEnvironmentModeWhenKeyboardFocusChanged;
    FBSDisplayLayoutMonitor *_displayLayoutMonitor;
    _Bool _isReducingResourcesUsage;
    NSHashTable *_weakObservers;
    id <BSInvalidatable> _keyboardFocusObserver;
    id <SBPIPControllerAdapter> _adapter;
    unsigned int _adapterWants_didAddContainerViewController:1;
    unsigned int _adapterWants_willRemoveContainerViewController:1;
    unsigned int _adapterWants_willBeginPIPInterruptionForAssertion:1;
    unsigned int _adapterWants_willEndPIPInterruptionForAssertion:1;
    unsigned int _adapterWants_didStartPictureInPictureCallback:1;
    unsigned int _adapterWants_didCancelPictureInPictureCallback:1;
    unsigned int _adapterWants_morphAnimatorDataSourceForTargetProcessIdentifier:1;
    unsigned int _adapterWants_willStartPictureInPictureTestActionForApplication:1;
    unsigned int _adapterWants_willRestorePictureInPictureForTestForApplication:1;
    unsigned int _adapterWants_windowLevelChanged:1;
    unsigned int _adapterWants_windowVisibilityChanged:1;
    unsigned int _adapterWants_preventStashAssertions:1;
    struct UIEdgeInsets _minimumStashedPadding;
}

+ (_Bool)_layoutState:(id)arg1 hasMeaningfullyChangedFromOldLayoutState:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic) struct UIEdgeInsets minimumStashedPadding; // @synthesize minimumStashedPadding=_minimumStashedPadding;
- (id)coordinatorRequestedIdleTimerBehavior:(id)arg1;
@property(readonly, nonatomic) _Bool hasIdleTimerBehaviors;
- (void)invalidateIdleTimerBehaviors;
- (id)morphAnimatorController:(id)arg1 dataSourceWithTargetProcessIdentifier:(int)arg2 scenePersistenceIdentifier:(id)arg3 gestureInitiated:(_Bool)arg4;
- (void)morphAnimatorControllerDidTerminate:(id)arg1;
- (void)keyboardFocusController:(id)arg1 externalSceneDidAcquireFocus:(id)arg2;
- (id)anyPresentedContentView;
- (struct CGRect)homeScreenInitialPIPFrame:(struct CGRect)arg1 withContentViewSize:(struct CGSize)arg2 position:(unsigned long long)arg3 padding:(double)arg4 fromOrientation:(long long)arg5 toOrientation:(long long)arg6 shouldUpdate:(_Bool)arg7 gestureInitiated:(_Bool)arg8;
- (_Bool)_isContentViewAlignedTopWithPosition:(unsigned long long)arg1 orientation:(long long)arg2;
- (_Bool)_isContentViewAlignedLeftWithPosition:(unsigned long long)arg1 orientation:(long long)arg2;
- (struct UIEdgeInsets)_pictureInPictureWindowMargins;
- (void)updateContentPaddingForContainerViewController:(id)arg1;
- (void)_updateContainerViewControllersContentPadding;
- (void)_setPictureInPictureWindowMargin:(struct UIEdgeInsets)arg1;
- (id)_currentLayoutState;
- (struct UIEdgeInsets)_updatePictureInPictureOverlayInsetsWithCurrentLayoutState:(_Bool)arg1 shouldUpdate:(_Bool)arg2;
- (struct UIEdgeInsets)_updatePictureInPictureOverlayInsetsWithCurrentLayoutState:(_Bool)arg1;
- (void)_shelfHeightDidChange:(id)arg1;
- (void)_floatingDockHeightWillChange:(id)arg1;
- (void)_updateFloatingDockInsetsWithHeight:(double)arg1;
- (void)_updateFloatingDockInsets;
- (struct CGRect)_keyboardFrameInScreenSpaceFromNotification:(id)arg1;
- (void)_visualizeKeyboardFrameIfNeeded:(id)arg1;
- (void)_keyboardWillShowOrHide:(id)arg1;
- (void)_keyboardWillRotate:(id)arg1;
- (void)_keyboardWillChangeFrame:(id)arg1;
- (void)_adjustPIPInsetsForKeyboardFrameChangeNotification:(id)arg1;
- (void)_enumerateObserversRespondingToSelector:(SEL)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (void)_removePictureInPictureMorphAnimatorController:(id)arg1;
- (id)pictureInPictureMorphAnimatorControllerForProcessIdentifier:(int)arg1 scenePersistenceIdentifier:(id)arg2;
- (void)_addPictureInPictureMorphAnimatorController:(id)arg1;
- (id)createAndRegisterPictureInPictureMorphAnimatorControllerWithTargetProcessIdentifier:(int)arg1 uuid:(id)arg2 scenePersistenceIdentifier:(id)arg3 direction:(long long)arg4 gestureInitiated:(_Bool)arg5;
- (_Bool)_pointInside:(struct CGPoint)arg1;
- (id)_pipWindow;
- (void)_lockStateDidChange:(id)arg1;
- (void)_setContainersStashed:(_Bool)arg1;
- (void)_managePictureInPictureWindowLevel;
- (void)_managePictureInPictureWindowVisibilityAnimated:(_Bool)arg1;
- (void)_destroyWindowAndRootViewControllerIfPossible;
- (void)_createWindowAndRootViewControllerIfNeeded;
- (void)assistantDidDisappear:(id)arg1;
- (void)assistantWillAppear:(id)arg1;
- (void)alertItemsController:(id)arg1 didDeactivateAlertItem:(id)arg2 forReason:(int)arg3;
- (void)alertItemsController:(id)arg1 didActivateAlertItem:(id)arg2;
- (void)alertItemsController:(id)arg1 willActivateAlertItem:(id)arg2;
- (void)_restorePictureInPictureForTestForApplicationWithBundleIdentifier:(id)arg1;
- (void)_startPictureInPictureTestActionForApplicationWithBundleIdentifier:(id)arg1;
@property(readonly, nonatomic) double windowLevel;
- (void)handleDestructionRequestForSceneHandles:(id)arg1;
- (long long)interfaceOrientationForContainerViewController:(id)arg1;
- (void)updatePictureInPictureWindowLevel;
- (void)applyPictureInPictureInsets:(struct UIEdgeInsets)arg1 forSource:(long long)arg2;
- (void)endPIPInterruptionForAssertion:(id)arg1;
- (void)cancelPictureInPictureForApplicationWithProcessIdentifierEnteringBackground:(int)arg1 scenePersistenceIdentifier:(id)arg2;
- (void)startPictureInPictureForApplicationWithProcessIdentifierEnteringBackground:(int)arg1 scenePersistenceIdentifier:(id)arg2 animated:(_Bool)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (long long)tetheringModeForScenePersistenceIdentifier:(id)arg1;
- (_Bool)isStoppingOrCancellingPictureInPictureForApplicationWithBundleIdentifier:(id)arg1 scenePersistenceIdentifier:(id)arg2;
- (_Bool)shouldStartPictureInPictureForApplicationWithProcessIdentifierEnteringBackground:(int)arg1 scenePersistenceIdentifier:(id)arg2;
- (_Bool)isPictureInPictureWindowVisible;
- (id)acquirePictureInPictureWindowLevelOverrideAssertionForWindowLevel:(unsigned long long)arg1 withReason:(long long)arg2 identifier:(id)arg3;
- (void)_cancelInterruptionDebouncingTimer;
- (id)acquireInterruptionAssertionForReason:(long long)arg1 identifier:(id)arg2 cameraSensorBundleIdentifier:(id)arg3;
- (id)acquireInterruptionAssertionForReason:(long long)arg1 identifier:(id)arg2;
- (id)_acquireStashAssertionForReason:(long long)arg1 identifier:(id)arg2 customAllowedEnvironmentModes:(id)arg3;
- (id)acquireStashAssertionForReason:(long long)arg1 identifier:(id)arg2;
- (void)setPictureInPictureWindowHidden:(_Bool)arg1 withReason:(id)arg2;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)restoreContentViewController:(id)arg1 appSceneEntity:(id)arg2 morphAnimatorConfigurationBlock:(CDUnknownBlockType)arg3;
- (void)prepareContainerViewControllerForHidingContentViewController:(id)arg1;
- (void)removeContainerViewController:(id)arg1;
- (id)containerViewControllerForContentViewController:(id)arg1;
- (_Bool)isPresentingPictureInPictureRequiringMedusaKeyboard;
- (id)hostedAppSceneHandles;
- (id)allContainerViewControllers;
- (void)addContainerViewController:(id)arg1 dataSource:(id)arg2;
- (void)activityDidChangeForSensorActivityDataProvider:(id)arg1;
- (void)containerViewController:(id)arg1 didFinishStartAnimationWithInitialInterfaceOrientation:(long long)arg2;
- (void)containerViewControllerUserMayUpdateStashState:(id)arg1;
- (void)containerViewController:(id)arg1 userDidUpdateStashState:(_Bool)arg2;
- (void)_relinquishPIPStashAssertionIfNecessaryForTransitionContext:(id)arg1;
- (_Bool)_shouldStashForTransitionContext:(id)arg1;
- (_Bool)_acquirePIPStashAssertionIfNecessaryForTransitionContext:(id)arg1;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionDidEndWithTransitionContext:(id)arg2;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionDidBeginWithTransitionContext:(id)arg2;
- (id)_overrideInsetsForReason:(id)arg1 withIdentifier:(id)arg2;
- (void)displayLayoutMonitor:(id)arg1 didUpdateDisplayLayout:(id)arg2 withContext:(id)arg3;
- (void)_setAdapter:(id)arg1;
- (long long)contentType;
- (void)dealloc;
- (id)initWithIdleTimerCoordinator:(id)arg1 windowLevel:(double)arg2 interactionSettings:(id)arg3 adapter:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

