//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SBStatusBarStyleOverridesSettings
{
    _Bool _exclusive;
    _Bool _showsWhenForeground;
    int _styleOverride;
}

+ (id)settingsControllerModule;
@property(nonatomic) _Bool showsWhenForeground; // @synthesize showsWhenForeground=_showsWhenForeground;
@property(nonatomic) _Bool exclusive; // @synthesize exclusive=_exclusive;
@property(nonatomic) int styleOverride; // @synthesize styleOverride=_styleOverride;
- (void)setDefaultValues;

@end

