//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <SpringBoard/SBUIAnimationControllerTransitionContextProvider-Protocol.h>

@class NSSet, NSString, SBApplicationSceneEntity;

@interface SBUIAnimationControllerActivatingAndDeactivatingAppTransitionContextProvider : NSObject <SBUIAnimationControllerTransitionContextProvider>
{
    SBApplicationSceneEntity *_toAppSceneEntity;
    SBApplicationSceneEntity *_fromAppSceneEntity;
    SBApplicationSceneEntity *_toApplicationSceneEntity;
    SBApplicationSceneEntity *_fromApplicationSceneEntity;
}

+ (id)transitionContextProviderWithToApplicationSceneEntity:(id)arg1 fromApplicationSceneEntity:(id)arg2;
@property(readonly, nonatomic) SBApplicationSceneEntity *fromApplicationSceneEntity; // @synthesize fromApplicationSceneEntity=_fromApplicationSceneEntity;
@property(readonly, nonatomic) SBApplicationSceneEntity *toApplicationSceneEntity; // @synthesize toApplicationSceneEntity=_toApplicationSceneEntity;
@property(retain, nonatomic) SBApplicationSceneEntity *deactivatingAppSceneEntity; // @synthesize deactivatingAppSceneEntity=_fromAppSceneEntity;
@property(retain, nonatomic) SBApplicationSceneEntity *activatingAppSceneEntity; // @synthesize activatingAppSceneEntity=_toAppSceneEntity;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSSet *fromApplicationSceneEntities;
@property(readonly, copy, nonatomic) NSSet *toApplicationSceneEntities;
- (id)initWithToApplicationSceneEntity:(id)arg1 fromApplicationSceneEntity:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

