//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <MediaRemote/NSCopying-Protocol.h>

@class NSData, NSSet, NSString;

@interface MRPlayer : NSObject <NSCopying>
{
    unsigned int _audioSessionID;
    NSString *_identifier;
    NSString *_displayName;
    long long _audioSessionType;
    NSSet *_mxSessionIDs;
}

+ (id)defaultPlayer;
+ (id)anyPlayer;
- (void).cxx_destruct;
@property(nonatomic) unsigned int audioSessionID; // @synthesize audioSessionID=_audioSessionID;
@property(copy, nonatomic) NSSet *mxSessionIDs; // @synthesize mxSessionIDs=_mxSessionIDs;
@property(nonatomic) long long audioSessionType; // @synthesize audioSessionType=_audioSessionType;
@property(copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)mergeFrom:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic, getter=isDefaultPlayer) _Bool defaultPlayer;
@property(readonly, nonatomic) _Bool hasAuxiliaryProperties;
@property(readonly, nonatomic) MRPlayer *skeleton;
@property(readonly, copy, nonatomic) NSData *data;
- (id)initWithData:(id)arg1;
- (id)initWithIdentifier:(id)arg1 displayName:(id)arg2;

@end

