//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSObject.h>

@class MRVirtualVoiceInputDeviceDescriptor, NSData;

@interface MRVirtualVoiceInputDevice : NSObject
{
    unsigned int _deviceID;
    unsigned int _recordingState;
    MRVirtualVoiceInputDeviceDescriptor *_descriptor;
}

@property(nonatomic) unsigned int recordingState; // @synthesize recordingState=_recordingState;
@property(copy, nonatomic) MRVirtualVoiceInputDeviceDescriptor *descriptor; // @synthesize descriptor=_descriptor;
@property(readonly, nonatomic) unsigned int deviceID; // @synthesize deviceID=_deviceID;
@property(readonly, nonatomic) NSData *data;
- (void)dealloc;
- (id)description;
- (id)initWithData:(id)arg1;
- (id)initWithDeviceID:(unsigned int)arg1;

@end

