//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <OnBoardingKit/OBWelcomeController.h>

@class HKAudiogramSample, HKHealthStore;
@protocol AIAudiogramConfirmResultsViewControllerDelegate;

@interface AIAudiogramConfirmResultsViewController : OBWelcomeController
{
    _Bool _analyticsDidMakeAdjustments;
    _Bool _analyticsDidCompleteIngestion;
    id <AIAudiogramConfirmResultsViewControllerDelegate> _delegate;
    HKAudiogramSample *_audiogram;
    HKHealthStore *_healthStore;
}

- (void).cxx_destruct;
@property(retain, nonatomic) HKHealthStore *healthStore; // @synthesize healthStore=_healthStore;
@property(retain, nonatomic) HKAudiogramSample *audiogram; // @synthesize audiogram=_audiogram;
@property(nonatomic) __weak id <AIAudiogramConfirmResultsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool analyticsDidCompleteIngestion; // @synthesize analyticsDidCompleteIngestion=_analyticsDidCompleteIngestion;
@property(nonatomic) _Bool analyticsDidMakeAdjustments; // @synthesize analyticsDidMakeAdjustments=_analyticsDidMakeAdjustments;
- (void)_saveToHealth:(id)arg1;
- (void)viewDidLoad;
- (id)initWithDelegate:(id)arg1 audiogram:(id)arg2;

@end

