//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

#import <FocusUI/FCUIContentSizeCategoryAdjusting-Protocol.h>

@class NSString, UILabel, _FCUIAddActivityControl;

@interface FCUIAddActivityFooterView : UIView <FCUIContentSizeCategoryAdjusting>
{
    _FCUIAddActivityControl *_addActivityControl;
    UILabel *_titleLabel;
    _Bool _adjustsFontForContentSizeCategory;
    NSString *_preferredContentSizeCategory;
}

+ (id)_preferredFont:(_Bool)arg1 textStyle:(id)arg2 weight:(double)arg3;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *preferredContentSizeCategory; // @synthesize preferredContentSizeCategory=_preferredContentSizeCategory;
@property(nonatomic) _Bool adjustsFontForContentSizeCategory; // @synthesize adjustsFontForContentSizeCategory=_adjustsFontForContentSizeCategory;
- (void)_configureActivityTitleLabelIfNecessaryWithTitle:(id)arg1;
- (void)_updateTextAttributesIfNecessary;
- (void)_updateTextAttributes;
- (void)_setNeedsTextAttributesUpdate;
- (_Bool)_needsTextAttributesUpdate;
- (void)_updateTextAttributesForTitleLabel;
- (void)_configureAddActivityControlIfNecessaryWithAction:(id)arg1;
- (void)_layoutSubviewsInBounds:(struct CGRect)arg1 measuringOnly:(out struct CGSize *)arg2;
- (_Bool)adjustForContentSizeCategoryChange;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithAction:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

