//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface NFLGenericCellImageOnSideAccessibilityProperties
{
}

- (_Bool)allowsExcerptWithFeedSettings:(id)arg1;
- (double)excerptLineHeightWithTemplate:(id)arg1;
- (id)excerptFontColorWithTemplate:(id)arg1;
- (id)excerptFontWithTemplate:(id)arg1;
- (double)excerptToAccessorySpacingWithTemplate:(id)arg1;
- (double)titleToExcerptSpacingWithTemplate:(id)arg1;
- (double)imageToTextSpacing;
- (double)imageHeight;

@end

