//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface UNSNotificationServiceExtensionManager : NSObject
{
    id _matchingContext;
    NSDictionary *_extensionIdentifierByContainingAppIdentifier;
}

@property(copy) NSDictionary *extensionIdentifierByContainingAppIdentifier; // @synthesize extensionIdentifierByContainingAppIdentifier=_extensionIdentifierByContainingAppIdentifier;
- (void).cxx_destruct;
- (void)_stopMonitoringExtensions;
- (void)_startMonitoringExtensions;
- (id)extensionForNotificationSourceDescription:(id)arg1 error:(id *)arg2;
- (void)dealloc;
- (id)init;

@end

