//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDictionary, NSObject;
@protocol PLAlbumContainer, PLAssetContainerList;

@interface PLAssetContainerListChangeNotification
{
    NSDictionary *_userInfo;
}

+ (id)notificationWithContainerList:(id)arg1 snapshot:(id)arg2 changedContainers:(id)arg3;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSObject<PLAlbumContainer> *albumList;
@property(readonly, nonatomic) id <PLAssetContainerList> assetContainerList;
- (id)description;
- (id)userInfo;
- (id)name;
- (id)_contentRelationshipName;

@end

