//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <PhotoLibraryServices/NSObject-Protocol.h>

@class NSArray, NSManagedObjectID, PLPhotoLibrary;

@protocol PLBackgroundJobWorkerProtocol <NSObject>
+ (id)workerWithLibrary:(PLPhotoLibrary *)arg1;
- (void)performWorkOnManagedObjectID:(NSManagedObjectID *)arg1 completion:(void (^)(NSError *))arg2;
- (NSArray *)managedObjectIDsNeedingProcessing;
- (_Bool)hasPendingJobs;

@optional
- (void)stopWorkingOnManagedObjectID:(NSManagedObjectID *)arg1;
- (_Bool)isInterruptible;
@end

