//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSKnownKeysMappingStrategy;

@interface PLInterest : NSObject
{
    NSKnownKeysMappingStrategy *_allKeysMappingStrategy;
    unsigned long long _indexesOfInterest;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long indexesOfInterest; // @synthesize indexesOfInterest=_indexesOfInterest;
@property(retain, nonatomic) NSKnownKeysMappingStrategy *allKeysMappingStrategy; // @synthesize allKeysMappingStrategy=_allKeysMappingStrategy;

@end

