//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSData, PLAdditionalAssetAttributes;

@interface PLSceneprint
{
}

+ (id)entityName;

// Remaining properties
@property(retain, nonatomic) PLAdditionalAssetAttributes *additionalAssetAttributes; // @dynamic additionalAssetAttributes;
@property(retain, nonatomic) NSData *data; // @dynamic data;

@end

