//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CNFAuditToken : NSObject
{
    CDStruct_4c969caf _audit_token;
}

@property(readonly, nonatomic) CDStruct_4c969caf audit_token; // @synthesize audit_token=_audit_token;
- (id)initWithAuditToken:(CDStruct_4c969caf)arg1;

@end

