//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableSet, NSURLSessionDataTask;

@interface PKFileDownload : NSObject
{
    NSMutableSet *_completionHandlers;
    NSURLSessionDataTask *_task;
}

@property(copy, nonatomic) NSURLSessionDataTask *task; // @synthesize task=_task;
@property(retain, nonatomic) NSMutableSet *completionHandlers; // @synthesize completionHandlers=_completionHandlers;
- (void).cxx_destruct;
- (id)init;

@end

