//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDecimalNumber, NSString;

@interface PKNumericSuggestion : NSObject
{
    _Bool _usedMaximumSuggestion;
    NSDecimalNumber *_value;
    NSString *_displayValue;
}

+ (id)suggestionWithValue:(id)arg1 currencyCode:(id)arg2;
@property(nonatomic) _Bool usedMaximumSuggestion; // @synthesize usedMaximumSuggestion=_usedMaximumSuggestion;
@property(copy, nonatomic) NSString *displayValue; // @synthesize displayValue=_displayValue;
@property(readonly, copy, nonatomic) NSDecimalNumber *value; // @synthesize value=_value;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithValue:(id)arg1 currencyCode:(id)arg2;

@end

