//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <PassKitCore/PKCancelable-Protocol.h>

@class NSString, PKPaymentProvisioningController;

@interface PKPaymentProvisioningTracker : NSObject <PKCancelable>
{
    PKPaymentProvisioningController *_controller;
}

- (void).cxx_destruct;
@property(readonly, nonatomic, getter=isCanceled) _Bool canceled;
- (void)cancel;
- (void)dealloc;
- (id)initWithPaymentProvisioningController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

