//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PKRecurringPaymentSummaryItemValidator
{
}

+ (Class)validatedClass;
+ (id)validatorWithObject:(id)arg1;
- (_Bool)isValidWithAPIType:(unsigned long long)arg1 withError:(id *)arg2;
- (_Bool)isValidWithError:(id *)arg1;
- (id)initWithRecurringPaymentSummaryItem:(id)arg1;

@end

