//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface CHBString : NSObject
{
}

+ (id)nsStringWithHandlingMultilevelCategoryDataFromOCText:(const struct OcText *)arg1 chdFormula:(id)arg2 state:(id)arg3;
+ (unsigned long long)edFontIndexForXlChartTextFrame:(struct XlChartTextFrame *)arg1 state:(id)arg2;
+ (id)edStringFromXlChartTextFrame:(const struct XlChartTextFrame *)arg1 state:(id)arg2;
+ (id)edRunsFromXlChartTextFrame:(const struct XlChartTextFrame *)arg1 state:(id)arg2;

@end

