//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface WBShading : NSObject
{
}

+ (void)write:(id)arg1 to:(struct WrdShading *)arg2;
+ (struct CsColour)fixedUpVersionOfColor:(struct CsColour)arg1;
+ (void)readFrom:(struct WrdShading *)arg1 to:(id)arg2;
+ (void)setToSolidWhite:(id)arg1;

@end

