//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface MUPunchoutViewModel : NSObject
{
    NSString *_vendorString;
    NSString *_moreText;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *moreText; // @synthesize moreText=_moreText;
@property(retain, nonatomic) NSString *vendorString; // @synthesize vendorString=_vendorString;

@end

