//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class FCInterestToken, NSString, NTPBChannelMembershipRecord;

@interface FCChannelMembership : NSObject
{
    _Bool _isAllowedToSeeDrafts;
    NSString *_channelID;
    NSString *_draftListID;
    NTPBChannelMembershipRecord *_record;
    FCInterestToken *_interestToken;
}

@property(retain, nonatomic) FCInterestToken *interestToken; // @synthesize interestToken=_interestToken;
@property(retain, nonatomic) NTPBChannelMembershipRecord *record; // @synthesize record=_record;
@property(retain, nonatomic) NSString *draftListID; // @synthesize draftListID=_draftListID;
@property(nonatomic) _Bool isAllowedToSeeDrafts; // @synthesize isAllowedToSeeDrafts=_isAllowedToSeeDrafts;
@property(retain, nonatomic) NSString *channelID; // @synthesize channelID=_channelID;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithRecord:(id)arg1 interestToken:(id)arg2;

@end

