//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <NewsCore/FCCoreConfigurationObserving-Protocol.h>

@class FCAsyncSerialQueue, FCEndpointConnection, NSString, NSURL;
@protocol FCCoreConfigurationManager;

@interface FCClientEndpointConnection : NSObject <FCCoreConfigurationObserving>
{
    NSURL *_baseURL;
    FCEndpointConnection *_endpointConnection;
    id <FCCoreConfigurationManager> _configurationManager;
    FCAsyncSerialQueue *_serialQueue;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FCAsyncSerialQueue *serialQueue; // @synthesize serialQueue=_serialQueue;
@property(retain, nonatomic) id <FCCoreConfigurationManager> configurationManager; // @synthesize configurationManager=_configurationManager;
@property(retain, nonatomic) FCEndpointConnection *endpointConnection; // @synthesize endpointConnection=_endpointConnection;
@property(retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
- (void)configurationManager:(id)arg1 configurationDidChange:(id)arg2;
- (void)updateBaseURLWith:(id)arg1;
- (void)submitWebAccessWithTagID:(id)arg1 purchaseID:(id)arg2 emailAddress:(id)arg3 purchaseReceipt:(id)arg4 countryCode:(id)arg5 languageCode:(id)arg6 callbackQueue:(id)arg7 completion:(CDUnknownBlockType)arg8;
- (void)reportConcern:(id)arg1 callbackQueue:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithEndpointConnection:(id)arg1 configurationManager:(id)arg2;
- (id)initWithConfigurationManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

