//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <NewsCore/FCMutableTodayPrivateData-Protocol.h>

@class FCBundleSubscription, NSArray, NSDictionary, NSMutableDictionary, NSNumber, NSSet, NSString;
@protocol FCDerivedPersonalizationData><NSCoding;

@interface FCMutableTodayPrivateData <FCMutableTodayPrivateData>
{
}

- (void)_deleteObjectsForOldKeys;
@property(copy, nonatomic) FCBundleSubscription *bundleSubscription;
@property(copy, nonatomic) NSNumber *onboardingVersion;
@property(copy, nonatomic) NSArray *recentlySeenHistoryItems;
@property(copy, nonatomic) NSDictionary *recentlyReadHistoryItems;
@property(copy, nonatomic) NSArray *rankedAllSubscribedTagIDs;
@property(copy, nonatomic) NSSet *purchasedTagIDs;
@property(copy, nonatomic) NSArray *autoFavoriteTagIDs;
@property(copy, nonatomic) NSSet *mutedTagIDs;
@property(copy, nonatomic) id <FCDerivedPersonalizationData><NSCoding> derivedPersonalizationData;
- (id)initWithDictionary:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSMutableDictionary *dictionary; // @dynamic dictionary;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

