//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface NUResetScaleNode
{
    CDStruct_1e2b2e48 _scale;
}

@property(readonly, nonatomic) CDStruct_912cb5d2 scale; // @synthesize scale=_scale;
- (id)nodeByReplayingAgainstCache:(id)arg1 pipelineState:(id)arg2 error:(out id *)arg3;
- (id)initWithInput:(id)arg1 scale:(CDStruct_912cb5d2)arg2;
- (id)initWithInput:(id)arg1 settings:(id)arg2;

@end

