//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SettingsTableViewControllerAccessibility
{
}

+ (id)weatherAttributionButtonWithDelegate:(id)arg1;
+ (void)_accessibilityPerformValidations:(id)arg1;
+ (Class)safeCategoryBaseClass;
+ (id)safeCategoryTargetClassName;
- (id)_switchCellWithText:(id)arg1 enabled:(_Bool)arg2 selected:(_Bool)arg3 target:(id)arg4 action:(SEL)arg5;

@end

