//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface ISIconFactory
{
}

- (id)_initGenericApp;
- (id)_initWithIcon:(id)arg1 decorations:(id)arg2;
- (id)initWithImages:(id)arg1;
- (id)_initTransparent;
- (id)initWithResourceProxy:(id)arg1;
- (id)initWithType:(id)arg1;
- (id)initWithBundleIdentifier:(id)arg1;
- (id)initWithURL:(id)arg1;
- (id)_init;

@end

