//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC13CoreKnowledge17CKSQLBackingStore : _TtCs12_SwiftObject
{
    MISSING_TYPE *name;
    MISSING_TYPE *connection;
}

+ (void)setDirectory:(id)arg1;
+ (id)directory;
- (id)initWithName:(id)arg1;

@end

