//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CLSHolidayCalendarEventRulesFactory : NSObject
{
}

+ (id)_baseURL;
+ (id)_eventRulesDictionariesForURL:(id)arg1;
+ (id)_allEventRulesForEventRulesDictionaries:(id)arg1;
+ (id)allSupportedCountryCodes;
+ (id)eventRulesURLForSourceURL:(id)arg1;
+ (id)eventRulesForSourcesURL:(id)arg1;
+ (id)eventRules;
+ (id)eventRulesSourcesURL:(id)arg1;

@end

