//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray;

@interface VNRecognizedObjectObservation
{
    NSArray *_labels;
}

@property(readonly, copy, nonatomic) NSArray *labels; // @synthesize labels=_labels;
- (void).cxx_destruct;
- (id)initWithRequestRevision:(unsigned long long)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithRequestRevision:(unsigned long long)arg1 boundingBox:(struct CGRect)arg2 confidence:(float)arg3 labels:(id)arg4;

@end

