//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewCell.h>

@class UILabel;
@protocol AVTAvatarAttributeEditorSectionItem;

@interface AVTAvatarAttributeEditorMulticolorPickerPlaceholderCell : UICollectionViewCell
{
    id <AVTAvatarAttributeEditorSectionItem> _item;
    UILabel *_label;
}

+ (double)estimatedTitleSpaceForWidth:(double)arg1;
+ (double)estimatedWidthForLabelSize:(struct CGSize)arg1;
+ (id)labelFont;
+ (id)cellIdentifier;
- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) id <AVTAvatarAttributeEditorSectionItem> item; // @synthesize item=_item;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

