//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSXPCInterface.h>

@interface NSXPCInterface (EXService)
+ (id)_EX_queryResultsInterface;
+ (id)_EX_combinedServiceInterface;
+ (id)_EX_launchServiceInterface;
+ (id)_EX_discoveryServiceInterface;
@end

