//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol CATIDSServiceConnectionInvitationInboxDelegate, CATNetworkPowerPrimitives, CATTimerSource, OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface CATIDSServiceConnectionInvitationInbox : NSObject
{
    id <CATTimerSource> mTimerSource;
    id <CATNetworkPowerPrimitives> mNetworkPowerPrimitives;
    NSObject<OS_dispatch_queue> *mWorkQueue;
    double mAcknowledgeTimeout;
    NSMutableDictionary *mInvitationsByInvitationID;
    NSMutableDictionary *mAcknowledgeTimersByInvitationID;
    id <CATIDSServiceConnectionInvitationInboxDelegate> _delegate;
}

+ (id)acknowledgeTimerIdentifier;
- (void).cxx_destruct;
@property(nonatomic) __weak id <CATIDSServiceConnectionInvitationInboxDelegate> delegate; // @synthesize delegate=_delegate;
- (void)acknowledgeTimerFiredWithInvitationIdentifier:(id)arg1;
- (void)receiveAcknowledgeForInvitationIdentifier:(id)arg1 connectionIdentifier:(id)arg2;
- (void)receiveInvitationWithIdentifier:(id)arg1 senderAppleID:(id)arg2 senderAddress:(id)arg3 messagingVersion:(unsigned long long)arg4 userInfo:(id)arg5;
- (id)initWithTimerSource:(id)arg1 networkPowerPrimitives:(id)arg2 workQueue:(id)arg3 acknowledgeTimeout:(double)arg4;
- (void)dealloc;

@end

