//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSObject.h>

@interface CHPatternGraph : NSObject
{
    struct PatternGraph *_graph;
}

+ (struct PatternGraph *)sharedRootCursor;
+ (struct PatternGraph *)sharedCursorByAdvancingWithCharacterTypes:(unsigned int *)arg1 withLength:(unsigned long long)arg2 fromCursor:(struct PatternGraph *)arg3;
+ (id)sharedPatternGraph;
@property(nonatomic) struct PatternGraph *graph; // @synthesize graph=_graph;
- (id)init;
- (void)dealloc;

@end

