//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray;

@interface WBSPhishingConfigurationDomain : NSObject
{
    NSArray *_expressions;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSArray *expressions; // @synthesize expressions=_expressions;
- (_Bool)matchesURL:(id)arg1;
- (id)dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1 error:(id *)arg2;
- (id)initWithExpressions:(id)arg1 error:(id *)arg2;

@end

