//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SafariSharedUI/WBSJSCallbackHandlerErrorReporter-Protocol.h>

@class JSValue, NSString, WBSWebExtensionAPIEventObjC;

@interface WBSWebExtensionAPIRuntimeObjC <WBSJSCallbackHandlerErrorReporter>
{
    WBSWebExtensionAPIEventObjC *_onConnect;
    WBSWebExtensionAPIEventObjC *_onMessage;
    WBSWebExtensionAPIEventObjC *_onMessageExternal;
    WBSWebExtensionAPIEventObjC *_onStartup;
    WBSWebExtensionAPIEventObjC *_onInstalled;
    JSValue *_lastError;
    _Bool _lastErrorAccessed;
    _Bool _processingUserGesture;
}

+ (id)runtimeWithExtensionIdentifier:(id)arg1 isForMainWorld:(_Bool)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *runtimeIdentifier;
@property(readonly, nonatomic) const struct OpaqueJSValue *lastError;
- (void)getPlatformInfoWithCompletionHandler:(id)arg1;
- (void)reloadExtensionWithBrowserContextController:(id)arg1;
- (void)openOptionsPageWithBrowserContextController:(id)arg1 completionHandler:(id)arg2;
- (void)setUninstallURL:(id)arg1 completionHandler:(id)arg2;
@property(readonly, nonatomic) WBSWebExtensionAPIEventObjC *onInstalled;
@property(readonly, nonatomic) WBSWebExtensionAPIEventObjC *onStartup;
@property(readonly, nonatomic) WBSWebExtensionAPIEventObjC *onMessageExternal;
@property(readonly, nonatomic) WBSWebExtensionAPIEventObjC *onMessage;
@property(readonly, nonatomic) WBSWebExtensionAPIEventObjC *onConnect;
- (Ref_da50d33d)connectNativeWithApplicationID:(id)arg1 browserContextController:(id)arg2;
- (void)sendNativeMessageWithApplicationID:(id)arg1 message:(id)arg2 browserContextController:(id)arg3 completionHandler:(id)arg4;
- (Ref_da50d33d)connectToExtensionWithID:(id)arg1 connectInfo:(id)arg2 frame:(id)arg3;
- (void)sendMessageToExtensionWithID:(id)arg1 message:(id)arg2 options:(id)arg3 frame:(id)arg4 completionHandler:(id)arg5 outExceptionString:(id *)arg6;
- (id)rawSenderInfoForFrame:(id)arg1;
- (id)getManifest;
- (void)getBackgroundPageWithBrowserContextController:(id)arg1 completionHandler:(id)arg2;
- (id)getURLWithResourcePath:(id)arg1;
- (void)reportErrorForCallbackHandler:(id)arg1 withMessage:(id)arg2 context:(struct OpaqueJSContext *)arg3;
@property(nonatomic, getter=isProcessingUserGesture) _Bool processingUserGesture;
- (_Bool)isPropertyAllowed:(id)arg1;
@property(readonly, nonatomic) void *cpp;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

