//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIViewController.h>

#import <SIMSetupSupport/AVCaptureMetadataOutputObjectsDelegate-Protocol.h>
#import <SIMSetupSupport/TSSetupFlowItem-Protocol.h>
#import <SIMSetupSupport/UINavigationControllerDelegate-Protocol.h>

@class CAShapeLayer, NSDate, NSString, TSCellularPlanQRCodeScannerView, UIButton, UILabel, UIView;
@protocol TSSIMSetupFlowDelegate;

@interface TSCellularPlanScanViewController : UIViewController <AVCaptureMetadataOutputObjectsDelegate, UINavigationControllerDelegate, TSSetupFlowItem>
{
    _Bool _withBackButton;
    NSDate *_nextTimeToAcceptScan;
    CAShapeLayer *_fillWithHoleLayer;
    CAShapeLayer *_holeOutlineLayer;
    TSCellularPlanQRCodeScannerView *_scannerView;
    _Bool _confirmationCodeRequired;
    _Bool _manualCardInfoEntry;
    id <TSSIMSetupFlowDelegate> _delegate;
    NSString *_fauxCardData;
    UIView *_scanView;
    UIView *_cutoutView;
    UIButton *_enterDetailsManuallyButton;
    UILabel *_scanQRCodeLabel;
    UILabel *_positionQRCodeLabel;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UILabel *positionQRCodeLabel; // @synthesize positionQRCodeLabel=_positionQRCodeLabel;
@property(nonatomic) __weak UILabel *scanQRCodeLabel; // @synthesize scanQRCodeLabel=_scanQRCodeLabel;
@property(nonatomic) __weak UIButton *enterDetailsManuallyButton; // @synthesize enterDetailsManuallyButton=_enterDetailsManuallyButton;
@property(nonatomic) __weak UIView *cutoutView; // @synthesize cutoutView=_cutoutView;
@property(nonatomic) __weak UIView *scanView; // @synthesize scanView=_scanView;
@property(readonly) _Bool manualCardInfoEntry; // @synthesize manualCardInfoEntry=_manualCardInfoEntry;
@property(readonly) _Bool confirmationCodeRequired; // @synthesize confirmationCodeRequired=_confirmationCodeRequired;
@property(readonly) NSString *fauxCardData; // @synthesize fauxCardData=_fauxCardData;
@property __weak id <TSSIMSetupFlowDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)canBeShownFromSuspendedState;
- (void)didChangeValueForKey:(id)arg1;
- (void)_addNewPlanWithCardData:(id)arg1 confirmationCode:(id)arg2;
- (void)enterFauxCardDataManually:(id)arg1;
- (void)captureOutput:(id)arg1 didOutputMetadataObjects:(id)arg2 fromConnection:(id)arg3;
- (void)presentViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithBackButton:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

