//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, OTConfigurationContext;

@interface OTClique : NSObject
{
    OTConfigurationContext *_ctx;
    NSString *_cliqueMemberIdentifier;
}

+ (id)resetProtectedData:(id)arg1 error:(id *)arg2;
+ (long long)getCDPStatus:(id)arg1 error:(id *)arg2;
+ (_Bool)setCDPEnabled:(id)arg1 error:(id *)arg2;
+ (void)removeInheritanceKey:(id)arg1 inheritanceKeyUUID:(id)arg2 reply:(CDUnknownBlockType)arg3;
+ (void)preflightRecoverOctagonUsingInheritanceKey:(id)arg1 inheritanceKey:(id)arg2 reply:(CDUnknownBlockType)arg3;
+ (void)recoverOctagonUsingInheritanceKey:(id)arg1 inheritanceKey:(id)arg2 reply:(CDUnknownBlockType)arg3;
+ (void)createInheritanceKey:(id)arg1 uuid:(id)arg2 reply:(CDUnknownBlockType)arg3;
+ (void)removeCustodianRecoveryKey:(id)arg1 custodianRecoveryKeyUUID:(id)arg2 reply:(CDUnknownBlockType)arg3;
+ (void)preflightRecoverOctagonUsingCustodianRecoveryKey:(id)arg1 custodianRecoveryKey:(id)arg2 reply:(CDUnknownBlockType)arg3;
+ (void)recoverOctagonUsingCustodianRecoveryKey:(id)arg1 custodianRecoveryKey:(id)arg2 reply:(CDUnknownBlockType)arg3;
+ (void)createCustodianRecoveryKey:(id)arg1 uuid:(id)arg2 reply:(CDUnknownBlockType)arg3;
+ (void)recoverOctagonUsingData:(id)arg1 recoveryKey:(id)arg2 reply:(CDUnknownBlockType)arg3;
+ (void)setNewRecoveryKeyWithData:(id)arg1 recoveryKey:(id)arg2 reply:(CDUnknownBlockType)arg3;
+ (id)recoverWithContextData:(id)arg1 bottleID:(id)arg2 escrowedEntropy:(id)arg3 error:(id *)arg4;
+ (id)findOptimalBottleIDsWithContextData:(id)arg1 error:(id *)arg2;
+ (id)fetchEscrowRecordsInternal:(id)arg1 error:(id *)arg2;
+ (id)performEscrowRecoveryWithContextData:(id)arg1 escrowArguments:(id)arg2 error:(id *)arg3;
+ (_Bool)isCloudServicesAvailable;
+ (id)newFriendsWithContextData:(id)arg1 resetReason:(long long)arg2 error:(id *)arg3;
+ (id)newFriendsWithContextData:(id)arg1 error:(id *)arg2;
+ (_Bool)platformSupportsSOS;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *cliqueMemberIdentifier; // @synthesize cliqueMemberIdentifier=_cliqueMemberIdentifier;
@property(readonly, nonatomic) OTConfigurationContext *ctx; // @synthesize ctx=_ctx;
- (void)performedSuccessfulCDPStateMachineRun:(id)arg1 reply:(CDUnknownBlockType)arg2;
- (void)performedFailureCDPStateMachineRun:(id)arg1 error:(id)arg2 reply:(CDUnknownBlockType)arg3;
- (_Bool)waitForOctagonUpgrade:(id *)arg1;
- (void)performedCDPStateMachineRun:(id)arg1 success:(_Bool)arg2 error:(id)arg3 reply:(CDUnknownBlockType)arg4;
- (void)fetchEscrowContents:(CDUnknownBlockType)arg1;
- (_Bool)accountUserKeyAvailable;
- (_Bool)requestToJoinCircle:(id *)arg1;
- (_Bool)peersHaveViewsEnabled:(id)arg1 error:(id *)arg2;
- (id)copyPeerPeerInfo:(id *)arg1;
- (_Bool)tryUserCredentialsAndDSID:(id)arg1 password:(id)arg2 error:(id *)arg3;
- (_Bool)setUserCredentialsAndDSID:(id)arg1 password:(id)arg2 error:(id *)arg3;
- (_Bool)sosViewSet:(id)arg1 disabledViews:(id)arg2;
- (_Bool)viewSet:(id)arg1 disabledViews:(id)arg2;
- (id)copyViewUnawarePeerInfo:(id *)arg1;
- (_Bool)waitForInitialSync:(id *)arg1;
- (_Bool)isLastFriend:(id *)arg1;
- (_Bool)fetchUserControllableViewsSyncingEnabled:(id *)arg1;
- (_Bool)setOctagonUserControllableViewsSyncEnabled:(_Bool)arg1 error:(id *)arg2;
- (_Bool)setUserControllableViewsSyncStatus:(_Bool)arg1 error:(id *)arg2;
- (_Bool)sosSafariPasswordSyncingEnabled:(id *)arg1;
- (_Bool)safariPasswordSyncingEnabled:(id *)arg1;
- (_Bool)joinAfterRestore:(id *)arg1;
- (id)peerDeviceNamesByPeerID:(id *)arg1;
- (_Bool)leaveClique:(id *)arg1;
- (_Bool)removeFriendsInClique:(id)arg1 error:(id *)arg2;
- (long long)cachedCliqueStatus:(_Bool)arg1 error:(id *)arg2;
- (long long)fetchCliqueStatus:(id *)arg1;
- (long long)fetchCliqueStatus:(id)arg1 error:(id *)arg2;
- (long long)_fetchCliqueStatus:(id)arg1 error:(id *)arg2;
- (id)setupPairingChannelAsAcceptor:(id)arg1 error:(id *)arg2;
- (id)setupPairingChannelAsAcceptor:(id)arg1;
- (id)setupPairingChannelAsInitator:(id)arg1 error:(id *)arg2;
- (id)setupPairingChannelAsInitiator:(id)arg1;
- (_Bool)resetAndEstablish:(long long)arg1 error:(id *)arg2;
- (_Bool)establish:(id *)arg1;
- (id)makeOTControl:(id *)arg1;
- (id)initWithContextData:(id)arg1;

@end

