//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <BookDataStore/BCCloudData-Protocol.h>
#import <BookDataStore/NSSecureCoding-Protocol.h>

@class CKRecord, NSData, NSDate, NSString;
@protocol BCCloudDataPrivacyDelegate;

@interface BCMutableCloudData : NSObject <BCCloudData, NSSecureCoding>
{
    _Bool _deletedFlag;
    long long _editGeneration;
    long long _syncGeneration;
    NSDate *_modificationDate;
    CKRecord *_systemFields;
    id <BCCloudDataPrivacyDelegate> _privacyDelegate;
    NSString *_localRecordID;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *localRecordID; // @synthesize localRecordID=_localRecordID;
@property(nonatomic) __weak id <BCCloudDataPrivacyDelegate> privacyDelegate; // @synthesize privacyDelegate=_privacyDelegate;
@property(copy, nonatomic) CKRecord *systemFields; // @synthesize systemFields=_systemFields;
@property(copy, nonatomic) NSDate *modificationDate; // @synthesize modificationDate=_modificationDate;
@property(nonatomic) long long syncGeneration; // @synthesize syncGeneration=_syncGeneration;
@property(nonatomic) long long editGeneration; // @synthesize editGeneration=_editGeneration;
@property(nonatomic) _Bool deletedFlag; // @synthesize deletedFlag=_deletedFlag;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (id)configuredRecordFromAttributes;
- (void)incrementEditGeneration;
- (id)zoneName;
- (id)identifier;
- (id)recordType;
@property(readonly, copy, nonatomic) NSData *ckSystemFields; // @dynamic ckSystemFields;
- (id)initWithRecord:(id)arg1;
- (id)initWithCloudData:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

