//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface EKCalendarItemCalendarEditItem
{
    unsigned long long _entityType;
}

- (id)popupMenu:(id)arg1;
- (id)eligibleCalendars;
- (id)cellForSubitemAtIndex:(unsigned long long)arg1;
- (_Bool)requiresReconfigurationOnSave;
- (_Bool)shouldAppearWithVisibility:(int)arg1;
- (_Bool)canBeConfiguredForCalendarConstraints:(id)arg1;
- (id)init;
- (id)initWithEntityType:(unsigned long long)arg1;

@end

