//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, UIFont;

@interface AKFontListController : NSObject
{
    NSArray *_fonts;
    UIFont *_defaultFont;
}

+ (id)attributedStringForFont:(id)arg1;
- (void).cxx_destruct;
@property(retain) UIFont *defaultFont; // @synthesize defaultFont=_defaultFont;
@property(retain) NSArray *fonts; // @synthesize fonts=_fonts;
- (id)_createFontsList;
- (id)initWithController:(id)arg1;

@end

