//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSTopHitSearchQuery, NSArray;

@interface EMSearchableIndexTopHitsQueryResult : NSObject
{
    CSTopHitSearchQuery *_topHitSearchQuery;
    NSArray *_foundItems;
    NSArray *_searchableItemIdentifiers;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *searchableItemIdentifiers; // @synthesize searchableItemIdentifiers=_searchableItemIdentifiers;
@property(copy, nonatomic) NSArray *foundItems; // @synthesize foundItems=_foundItems;
@property(retain, nonatomic) CSTopHitSearchQuery *topHitSearchQuery; // @synthesize topHitSearchQuery=_topHitSearchQuery;
- (long long)rankingIndexForConversationID:(id)arg1;
- (void)userDidInteractWithConversationID:(id)arg1;
- (long long)rankingIndexForMessageLibraryID:(id)arg1;
- (void)userDidInteractWithLibraryIdentifier:(id)arg1;
- (id)initWithTopHitSearchQuery:(id)arg1 foundItems:(id)arg2;

@end

