//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class UIViewController;

__attribute__((visibility("hidden")))
@interface SharedWithYouLibraryItemController
{
    UIViewController *_viewController;
}

- (void).cxx_destruct;
- (id)viewController;
- (_Bool)isSelected;
- (void)didSelectItem;
- (void)updateListContentConfiguration:(id)arg1;

@end

