//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSAttributedString, NSString, UIImage;

__attribute__((visibility("hidden")))
@interface ToolbarItemConfiguration : NSObject
{
    id _title;
    _Bool _showsIndicator;
    _Bool _emphasized;
    UIImage *_image;
}

+ (id)configurationForTabGroup:(id)arg1 inProfile:(id)arg2;
+ (id)configurationForProfile:(id)arg1;
+ (id)configurationForTabGroup:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic, getter=isEmphasized) _Bool emphasized; // @synthesize emphasized=_emphasized;
@property(nonatomic) _Bool showsIndicator; // @synthesize showsIndicator=_showsIndicator;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
- (id)buttonConfigurationWithStyle:(long long)arg1;
@property(copy, nonatomic) NSAttributedString *attributedTitle;
@property(copy, nonatomic) NSString *title;
- (id)init;

@end

