//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface KNObjectPlaceholderLayout
{
}

- (id)instructionalStorageForContainedStorage:(id)arg1 storageKind:(unsigned char)arg2;
- (_Bool)supportsRotation;
- (_Bool)canFlip;

@end

