//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class UIVisualEffectView;

@interface TUBackdropView : UIView
{
    UIVisualEffectView *_backdropView;
}

@property(readonly, nonatomic) UIVisualEffectView *backdropView; // @synthesize backdropView=_backdropView;
- (void).cxx_destruct;
- (void)layoutSubviews;
@property(readonly, nonatomic) UIView *contentView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

