//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIColor.h>

@interface UIColor (Bridge)
+ (id)ts_dynamicColor:(id)arg1 withDarkStyleVariant:(id)arg2;
+ (id)ts_activityIndicatorColor;
+ (id)ts_tableCellDefaultSelectionTintColor;
+ (id)ts_systemDarkTealColor;
- (double)ts_luminance;
@end

