//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface GEOPlatform : NSObject
{
}

+ (id)sharedPlatform;
+ (void)setIsRunningInGeod:(_Bool)arg1;
- (double)deviceScreenScale;
- (long long)deviceScreenHeightInPixels;
- (long long)deviceScreenWidthInPixels;
- (id)clientCapabilities;
- (_Bool)supportsForceTouch;
- (_Bool)supportsNewiOS9Features;
- (_Bool)supportsNavigation;
- (_Bool)supportsRealisticTiles;
- (_Bool)mapsFeatureFreedomEnabled;
- (_Bool)_deviceSupportsNavigation;
- (id)hardwareModel;
- (id)hardwareIdentifier;
- (id)buildVersion;
- (id)osVersion;
- (id)productName;
- (_Bool)isInternalInstall;

@end

