//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ClassKit/CLSRelationable-Protocol.h>

@class CLSArchivedAnswerFormat, NSString;

@interface CLSArchivedQuestionStep <CLSRelationable>
{
    NSString *_questionText;
    long long _displayOrder;
    long long _questionType;
}

+ (_Bool)supportsSecureCoding;
+ (id)relations;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *questionText;
@property(nonatomic) long long displayOrder;
- (void)setQuestionType:(long long)arg1;
@property(readonly, nonatomic) long long questionType;
@property(retain, nonatomic) CLSArchivedAnswerFormat *archivedAnswerFormat;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithQuestionText:(id)arg1 answerFormat:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

