//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SiriUIHelpButton
{
    _Bool _animatingEmphasis;
    _Bool _emphasized;
}

+ (id)buttonWithHelpImageMask;
- (double)_targetAlpha;
- (void)pulse;
- (void)setEmphasized:(_Bool)arg1;

@end

