//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MPModelGenericObject, NSArray;

@interface MPCSharedListeningQueueEventContentPlayedNow : NSObject
{
    MPModelGenericObject *_container;
    NSArray *_items;
    MPModelGenericObject *_startItem;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) MPModelGenericObject *startItem; // @synthesize startItem=_startItem;
@property(readonly, copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(readonly, nonatomic) MPModelGenericObject *container; // @synthesize container=_container;
- (id)description;
- (id)initWithItems:(id)arg1 container:(id)arg2 startItem:(id)arg3;

@end

