//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SUScriptDialogNativeObject
{
}

- (void)_tearDownForDismissWithButtonIndex:(long long)arg1;
- (void)_showSheetInView:(id)arg1 fromViewController:(id)arg2;
- (id)_makeAlertControllerForDialog:(id)arg1 style:(long long)arg2;
- (void)showSheetInViewController:(id)arg1;
- (void)showSheet;
- (void)showFromRect:(struct CGRect)arg1 inView:(id)arg2;
- (void)show;
- (void)dismiss;

@end

