//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, SUScriptViewController;

@interface SUScriptSection
{
    NSString *_badgeValue;
    NSString *_identifier;
    _Bool _transient;
    SUScriptViewController *_viewController;
}

+ (void)initialize;
+ (id)webScriptNameForSelector:(SEL)arg1;
+ (id)webScriptNameForKeyName:(id)arg1;
- (id)scriptAttributeKeys;
- (id)attributeKeys;
@property(readonly) SUScriptViewController *viewController;
@property(readonly) _Bool transient;
@property(retain) NSString *badgeValue;
@property(readonly) NSString *identifier;
- (id)_className;
- (void)setBadgeValue:(id)arg1 animated:(_Bool)arg2 blink:(_Bool)arg3;
- (void)dealloc;
- (id)initWithNativeSection:(id)arg1;

@end

