//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <iTunesStore/ISOperation.h>

@class SSURLRequestProperties;

@interface SUXMLHTTPRequestOperation : ISOperation
{
    CDUnknownBlockType _outputBlock;
    SSURLRequestProperties *_requestProperties;
}

- (void).cxx_destruct;
- (_Bool)_isAllowedURL:(id)arg1 withURLBag:(id)arg2;
- (void)run;
@property(copy) CDUnknownBlockType outputBlock;
- (id)initWithRequestProperties:(id)arg1;

@end

