//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CDMRepetitionDetectionServiceUtils : NSObject
{
}

+ (id)asrHypothesis2QRUtterance:(id)arg1;
+ (id)asrToken2QRToken:(id)arg1;
+ (id)buildRDRequestWithPrevTurn:(id)arg1 curTurn:(id)arg2 nluRequestId:(id)arg3 resultCandidateId:(id)arg4;

@end

