//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface PSUIVoiceAndDataDrillDownSwitchSpecifiersFactory : NSObject
{
}

+ (_Bool)shouldShow5GSASwitchForSpecifier:(id)arg1 RATMode:(int)arg2;
+ (_Bool)isVoLTESwitchTurnedOnByDefaultAndHidden:(id)arg1;
+ (_Bool)shouldShowVoLTESwitchForSubscriptionContext:(id)arg1 RATMode:(int)arg2;
- (id)create5GSASwitchSpecifierWithHostController:(id)arg1 parentSpecifier:(id)arg2;
- (id)createVoLTESwitchSpecifierWithHostController:(id)arg1 parentSpecifier:(id)arg2;

@end

