//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSDate;

@interface PGBestOfPastMemoryGenerator
{
    NSDate *_localStartDate;
    NSDate *_localEndDate;
}

@property(nonatomic) NSDate *localEndDate; // @synthesize localEndDate=_localEndDate;
@property(nonatomic) NSDate *localStartDate; // @synthesize localStartDate=_localStartDate;
- (id)_potentialMemoriesForDryTesting;
- (void)_postProcessMemory:(id)arg1 withPotentialMemory:(id)arg2;
- (void)_enumeratePotentialMemoriesUsingBlock:(CDUnknownBlockType)arg1;

@end

