//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <AppleAccountUI/AAUIInviteControllerDelegate-Protocol.h>

@class AAMessagesInviteContext, AAUIMessagesInviteConfigurationController, AAUISpinnerManager, NSString, UINavigationController;
@protocol AAUIInviteMessageFlowControllerDelegate, AAUIOBWelcomeControllerViewModelProtocol;

@interface AAUIInviteMessageFlowController : NSObject <AAUIInviteControllerDelegate>
{
    unsigned long long _flow;
    AAMessagesInviteContext *_context;
    NSString *_recipientHandle;
    id <AAUIOBWelcomeControllerViewModelProtocol> _defaultMessageViewModel;
    id <AAUIOBWelcomeControllerViewModelProtocol> _messageSentViewModel;
    AAUIMessagesInviteConfigurationController *_messageComposer;
    AAUISpinnerManager *_spinnerManager;
    _Bool _hideCancel;
    UINavigationController *_navigationController;
    id <AAUIInviteMessageFlowControllerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool hideCancel; // @synthesize hideCancel=_hideCancel;
@property(nonatomic) __weak id <AAUIInviteMessageFlowControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
- (void)inviteController:(id)arg1 didFinishWithStatus:(unsigned long long)arg2 recipients:(id)arg3 userInfo:(id)arg4 error:(id)arg5;
- (id)_bubbleImageForFlow:(unsigned long long)arg1;
- (void)_sendDefaultMessage;
- (void)_messageSentSecondaryActionTapped;
- (void)_finishMessageInvitationFlow;
- (void)_cancelMessageInvitationFlow;
- (void)_invitationWasSent;
- (void)_showInvitationSent;
- (void)_showMessagesComposeController;
- (void)_showDefaultMessageView;
- (void)_hideActivitySpinnerInNavigationBar;
- (void)_showActivitySpinnerInNavigationBar;
- (void)start;
- (id)initWithContext:(id)arg1 flow:(unsigned long long)arg2 navigationController:(id)arg3 defaultMessageViewModel:(id)arg4 messageSentViewModel:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

