//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CallFingerprint : NSObject
{
}

+ (id)matchCallWithFingerprint:(id)arg1 withDatabase:(id)arg2;
+ (_Bool)match:(id)arg1:(id)arg2;
+ (_Bool)doesCallTypesMatch:(id)arg1:(id)arg2;

@end

