//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSObject.h>

@interface PKDefaults : NSObject
{
}

+ (void)addLastUsedPrinter:(id)arg1 duplexMode:(id)arg2 lastUsedSize:(struct CGSize)arg3 forPhoto:(_Bool)arg4;
+ (void)addLastUsedPrinter:(id)arg1 duplexMode:(id)arg2 lastUsedSize:(struct CGSize)arg3;
+ (id)lastUsedPrintersForPhoto:(_Bool)arg1;
+ (id)lastUsedPrinters;
+ (long long)printerLookupWithArray:(id)arg1 withTimeout:(double)arg2 completionHandler:(CDUnknownBlockType)arg3;

@end

