//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface IMAttachment : NSObject
{
    NSString *_guid;
    NSString *_path;
    _Bool _isSticker;
    NSDate *_createdDate;
}

- (void).cxx_destruct;
- (id)fileTransfer;
- (_Bool)isSticker;
- (id)createdDate;
- (id)path;
- (id)guid;
- (id)description;
- (id)initWithPath:(id)arg1 guid:(id)arg2 createdDate:(id)arg3 isSticker:(_Bool)arg4;
- (id)initWithPath:(id)arg1 guid:(id)arg2;

@end

