//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppSupportUI/NUIContainerView.h>

@class MISSING_TYPE;

@interface _TtC15RemindersUICore24TTRContainerWrappingView : NUIContainerView
{
    MISSING_TYPE *horizontalSpacing;
    MISSING_TYPE *verticalSpacing;
    MISSING_TYPE *maxRowCount;
    MISSING_TYPE *lastLayoutResult;
    MISSING_TYPE *viewsRequiringNewRows;
    MISSING_TYPE *customSpacingByView;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithArrangedSubviews:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (_Bool)isLayoutSizeDependentOnPerpendicularAxis;
- (void)layoutArrangedSubviewsInBounds:(struct CGRect)arg1;
- (struct CGSize)calculateArrangedSizeFittingSize:(struct CGSize)arg1;

@end

