//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray;

@interface SGQuickResponsesReplyModel : NSObject
{
    _Bool _dynamicLabel;
    unsigned long long _semanticClassIndex;
    NSArray *_semanticClasses;
    NSArray *_selectedPseudocounts;
    double _scoreWeight;
    unsigned long long _category;
}

+ (id)semanticClassesForArray:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool dynamicLabel; // @synthesize dynamicLabel=_dynamicLabel;
@property(readonly, nonatomic) unsigned long long category; // @synthesize category=_category;
@property(readonly, nonatomic) double scoreWeight; // @synthesize scoreWeight=_scoreWeight;
@property(readonly, nonatomic) NSArray *selectedPseudocounts; // @synthesize selectedPseudocounts=_selectedPseudocounts;
@property(readonly, nonatomic) NSArray *semanticClasses; // @synthesize semanticClasses=_semanticClasses;
@property(readonly, nonatomic) unsigned long long semanticClassIndex; // @synthesize semanticClassIndex=_semanticClassIndex;
- (id)initWithDictionary:(id)arg1 index:(unsigned long long)arg2;

@end

