//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <CloudDocsDaemon/BRCReachabilityDelegate-Protocol.h>
#import <CloudDocsDaemon/NSXPCListenerDelegate-Protocol.h>

@class NSDate, NSMutableDictionary, NSOperationQueue, NSString, NSXPCListener, NSXPCListenerEndpoint;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface BRCDaemon : NSObject <BRCReachabilityDelegate, NSXPCListenerDelegate>
{
    NSObject<OS_dispatch_source> *_sigIntSrc;
    NSObject<OS_dispatch_source> *_sigQuitSrc;
    NSObject<OS_dispatch_source> *_sigTermSrc;
    NSXPCListener *_xpcListener;
    NSXPCListener *_tokenListener;
    _Bool _unitTestMode;
    _Bool _resumed;
    NSObject<OS_dispatch_queue> *_xpcListenersReadyQueue;
    NSObject<OS_dispatch_queue> *_accountReadyQueue;
    NSObject<OS_dispatch_queue> *_accountResumedQueue;
    NSObject<OS_dispatch_queue> *_startupQueue;
    int _serverAvailabilityNotifyToken;
    NSObject<OS_dispatch_queue> *_accountLoaderQueue;
    NSMutableDictionary *_shareAcceptOperationsByToken;
    NSMutableDictionary *_shareAcceptWaitersByToken;
    NSObject<OS_dispatch_source> *_acceptWaiterTimer;
    NSOperationQueue *_shareAcceptQueue;
    _Bool _disableAccountChangesHandling;
    _Bool _disableAppsChangesHandling;
    Class _containerClass;
    unsigned long long _forceIsGreedyState;
    NSDate *_startupDate;
}

+ (id)UTIForExtension:(id)arg1;
+ (_Bool)isDaemonRunning;
+ (id)daemon;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDate *startupDate; // @synthesize startupDate=_startupDate;
@property(nonatomic) unsigned long long forceIsGreedyState; // @synthesize forceIsGreedyState=_forceIsGreedyState;
@property(nonatomic) _Bool disableAppsChangesHandling; // @synthesize disableAppsChangesHandling=_disableAppsChangesHandling;
@property(nonatomic) _Bool disableAccountChangesHandling; // @synthesize disableAccountChangesHandling=_disableAccountChangesHandling;
@property(retain, nonatomic) Class containerClass; // @synthesize containerClass=_containerClass;
- (void)resumeIPCAcceptation;
- (void)suspendIPCAcceptation;
- (void)exitWithCode:(int)arg1;
- (void)handleExitSignal:(int)arg1;
- (void)networkReachabilityFlagsChanged:(unsigned int)arg1;
- (void)networkReachabilityChanged:(_Bool)arg1;
- (_Bool)selfCheck:(struct __sFILE *)arg1;
@property(readonly, nonatomic) NSXPCListenerEndpoint *endpoint;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)waitOnAccountResumedQueue;
- (void)localeDidChange;
- (void)dumpToContext:(id)arg1;
- (void)registerWaiterBlock:(CDUnknownBlockType)arg1 forShareURL:(id)arg2;
- (id)registerShareAcceptOperation:(id)arg1 forURL:(id)arg2;
- (void)restart;
- (void)start;
- (void)_finishStartup;
- (void)_startupAndLoadAccount;
- (void)_startXPCListeners;
- (void)_setDoneXpcActivity:(id)arg1 description:(id)arg2;
- (void)_setupCacheDelete;
- (void)performWithSessionForVolume:(id)arg1 action:(CDUnknownBlockType)arg2;
- (id)currentSession;
- (id)currentAccountHandler;
- (unsigned long long)nonPurgeableSizeForSession:(id)arg1 givenPurgeableSize:(unsigned long long)arg2;
- (void)setUpSandbox;
- (_Bool)_haveRequiredKernelFeatures;
- (void)setUpAnonymousListener;
- (void)waitForConfiguration;
- (id)init;
- (void)_setupVNodeRapidAging;
- (void)_initSignals;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

