//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <RemoteManagement/NSObject-Protocol.h>

@class NSNumber, NSString, NSUUID, RMAskForTimeRequest;

@protocol RMAskForTimeInterface <NSObject>
- (void)handleAnswer:(long long)arg1 requestIdentifier:(NSUUID *)arg2 timeApproved:(NSNumber *)arg3 completionHandler:(void (^)(void))arg4;
- (void)fetchLastResponseForRequestedResourceIdentifier:(NSString *)arg1 usageType:(long long)arg2 withCompletionHandler:(void (^)(long long, NSNumber *, NSError *))arg3;
- (void)approveExceptionForRequest:(RMAskForTimeRequest *)arg1 completionHandler:(void (^)(NSError *))arg2;
- (void)sendAskForTimeRequest:(RMAskForTimeRequest *)arg1 completionHandler:(void (^)(NSError *))arg2;
@end

