//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface QLBasePreviewParts
{
}

+ (CDUnknownFunctionPointerType)dataCallbackForUTI:(id)arg1 andSize:(unsigned long long)arg2;
+ (CDUnknownFunctionPointerType)urlCallbackForUTI:(id)arg1;
+ (_Bool)isBundleURL:(id)arg1;
+ (_Bool)canConvertDocumentType:(id)arg1;
- (void)computePreview;

@end

