//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface ACUIUtils : NSObject
{
}

+ (id)sortedDataclassesFrom:(id)arg1;
+ (id)sortedAccountsFromAccounts:(id)arg1;
+ (id)_accountGroupIdentifier:(id)arg1 ignoringGroups:(id)arg2;
+ (void)filterAccounts:(id)arg1 toTopLevel:(id)arg2 grouped:(id)arg3 ignoringGroups:(id)arg4;

@end

