//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <NotesShared/ICAttachmentModel.h>

#import <NotesUI/QLPreviewItem-Protocol.h>

@class NSArray, NSString, NSURL;

@interface ICAttachmentModel (UI) <QLPreviewItem>
+ (struct UIImage *)fileIconForURL:(id)arg1 withPreferredSize:(struct CGSize)arg2 uti:(id)arg3;
+ (struct UIImage *)fileIconForURL:(id)arg1 withPreferredSize:(struct CGSize)arg2;
- (struct UIImage *)fileIconWithPreferredSize:(struct CGSize)arg1;
- (id)activityItems;
@property(readonly, nonatomic) NSArray *quicklookPreviewItems;
@property(readonly, nonatomic) CDUnknownBlockType genericBrickThumbnailCreator;
@property(readonly, nonatomic) CDUnknownBlockType genericListThumbnailCreator;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *previewItemTitle;
@property(readonly, nonatomic) NSURL *previewItemURL;
@property(readonly) Class superclass;
@end

