//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

#import <NanoSystemSettings/NSCopying-Protocol.h>

@interface NSSUsageSize : PBCodable <NSCopying>
{
    unsigned long long _docsAndData;
    unsigned long long _fixed;
    unsigned long long _purgeable;
    struct {
        unsigned int docsAndData:1;
        unsigned int fixed:1;
        unsigned int purgeable:1;
    } _has;
}

@property(nonatomic) unsigned long long purgeable; // @synthesize purgeable=_purgeable;
@property(nonatomic) unsigned long long docsAndData; // @synthesize docsAndData=_docsAndData;
@property(nonatomic) unsigned long long fixed; // @synthesize fixed=_fixed;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasPurgeable;
@property(nonatomic) _Bool hasDocsAndData;
@property(nonatomic) _Bool hasFixed;

@end

