//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UISearchBar.h>

@protocol STSSearchBarDelegate;

@interface STSSearchBar : UISearchBar
{
    _Bool _clickBeganInSearchBar;
    id <STSSearchBarDelegate> _stsDelegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <STSSearchBarDelegate> stsDelegate; // @synthesize stsDelegate=_stsDelegate;

@end

