//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface USKObjectPath : NSObject
{
    struct SdfPath _path;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)propertyName;
- (_Bool)isPropertyPath;
- (id)nodePath;
- (_Bool)isNodePath;
- (id)tokenValue;
- (id)pathByAppendingPropertyComponent:(id)arg1;
- (id)stringValue;
- (id)initWithToken:(id)arg1;
- (id)initWithString:(id)arg1;
- (id)initWithSdfPath:(struct SdfPath)arg1;
- (id)init;
- (struct SdfPath)path;

@end

