//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSArray.h>

@interface NSArray (ParsecExtras)
- (id)parsec_mapAndFilterObjectsUsingBlock:(CDUnknownBlockType)arg1;
- (id)parsec_mapAndFilterObjectsWithOptions:(unsigned long long)arg1 usingBlock:(CDUnknownBlockType)arg2;
- (id)parsec_mapObjectsUsingBlock:(CDUnknownBlockType)arg1;
- (id)parsec_filterObjectsUsingBlock:(CDUnknownBlockType)arg1;
- (id)parsec_numberAtIndex:(unsigned long long)arg1;
@end

