//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ComponentKit/CKComponentController.h>

@class UISwitch;

@interface WFSwitchParameterComponentController : CKComponentController
{
    UISwitch *_toggleSwitch;
}

- (void).cxx_destruct;
- (void)didUnmount;
- (void)willUnmount;

@end

