//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SleepDaemon/NSObject-Protocol.h>

@class DNDModeAssertionDetails;
@protocol HDSPDNDModeAssertion;

@protocol HDSPDNDModeAssertionService <NSObject>
- (id <HDSPDNDModeAssertion>)activeModeAssertionWithError:(id *)arg1;
- (id)invalidateActiveModeAssertionWithError:(id *)arg1;
- (id <HDSPDNDModeAssertion>)takeModeAssertionWithDetails:(DNDModeAssertionDetails *)arg1 error:(id *)arg2;
@end

