//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtCV9Coherence19Google_Protobuf_ApiP33_B181C30CD4E44ADC4F4E3B748C13C06E13_StorageClass : _TtCs12_SwiftObject
{
    MISSING_TYPE *_name;
    MISSING_TYPE *_methods;
    MISSING_TYPE *_options;
    MISSING_TYPE *_version;
    MISSING_TYPE *_sourceContext;
    MISSING_TYPE *_mixins;
    MISSING_TYPE *_syntax;
}

@end

