//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewCell.h>

@class PKDiscoveryShelfView;

@interface PKDiscoveryArticleLayoutCell : UICollectionViewCell
{
    PKDiscoveryShelfView *_shelfView;
}

@property(retain, nonatomic) PKDiscoveryShelfView *shelfView; // @synthesize shelfView=_shelfView;
- (void).cxx_destruct;
- (id)preferredLayoutAttributesFittingAttributes:(id)arg1;
- (void)prepareForReuse;
- (void)layoutSubviews;

@end

