//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <HomeAI/NSObject-Protocol.h>

@class AVAssetWriter, AVFragmentedMediaDataReport, NSData;

@protocol AVAssetWriterDelegate <NSObject>

@optional
- (void)assetWriter:(AVAssetWriter *)arg1 didProduceFragmentedMediaData:(NSData *)arg2 fragmentedMediaDataReport:(AVFragmentedMediaDataReport *)arg3;
- (void)assetWriter:(AVAssetWriter *)arg1 didProduceFragmentedHeaderData:(NSData *)arg2;
@end

