//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMutableArray, NSMutableDictionary, NSString, XCTestConfiguration;

@interface _XCTestSuiteImplementation
{
    NSString *_name;
    NSMutableArray *_tests;
    XCTestConfiguration *_testConfiguration;
    NSMutableDictionary *_activityAggregateStatistics;
}

@property(readonly) NSMutableDictionary *activityAggregateStatistics; // @synthesize activityAggregateStatistics=_activityAggregateStatistics;
@property(retain) XCTestConfiguration *testConfiguration; // @synthesize testConfiguration=_testConfiguration;
@property(retain) NSMutableArray *tests; // @synthesize tests=_tests;
@property(copy) NSString *name; // @synthesize name=_name;
- (void)dealloc;
- (id)initWithName:(id)arg1;

@end

