//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, NSUUID;

@interface XCUIInterruptionHandler : NSObject
{
    CDUnknownBlockType _block;
    NSString *_handlerDescription;
    NSUUID *_identifier;
}

- (void).cxx_destruct;
@property(readonly, copy) NSUUID *identifier; // @synthesize identifier=_identifier;
@property(readonly, copy) NSString *handlerDescription; // @synthesize handlerDescription=_handlerDescription;
@property(readonly, copy) CDUnknownBlockType block; // @synthesize block=_block;
- (id)initWithBlock:(CDUnknownBlockType)arg1 description:(id)arg2;

@end

