//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class VCMetricCheckIn, WFMetricStatusEvent;
@protocol VCDatabaseProvider;

@interface VCMetricSubmitter : NSObject
{
    WFMetricStatusEvent *_event;
    VCMetricCheckIn *_checkIn;
    id <VCDatabaseProvider> _databaseProvider;
}

+ (void)performWithDatabaseProvider:(id)arg1;
+ (void)scheduleWithScheduler:(id)arg1 databaseProvider:(id)arg2;
+ (void)scheduleWithDatabaseProvider:(id)arg1;
+ (id)activityIdentifier;
- (void).cxx_destruct;
@property(readonly, nonatomic) id <VCDatabaseProvider> databaseProvider; // @synthesize databaseProvider=_databaseProvider;
@property(readonly, nonatomic) VCMetricCheckIn *checkIn; // @synthesize checkIn=_checkIn;
@property(readonly, nonatomic) WFMetricStatusEvent *event; // @synthesize event=_event;
- (unsigned int)numberOfPersonalAutomationsFromSuggestionsEnabled:(id *)arg1;
- (unsigned int)numberOfPersonalAutomationsEnabled:(id *)arg1;
- (unsigned int)folderCount:(id)arg1;
- (unsigned int)uncategorizedShortcutCount:(id)arg1;
- (unsigned int)shortcutsCount:(id)arg1;
- (unsigned int)averageShortcutCountPerFolder:(id)arg1;
- (_Bool)homeAutomationsPresent:(id *)arg1;
- (_Bool)personalAutomationsPresent:(id *)arg1;
- (_Bool)isSharingEnabled;
- (_Bool)isAppInstalled;
- (void)perform;
- (id)initWithCheckIn:(id)arg1 event:(id)arg2 databaseProvider:(id)arg3;
- (id)initWithDatabaseProvider:(id)arg1;

@end

