//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <Proximity/NSCopying-Protocol.h>
#import <Proximity/NSSecureCoding-Protocol.h>

@interface PRAngleMeasurement : NSObject <NSCopying, NSSecureCoding>
{
    double _measurement;
    double _uncertainty;
}

+ (_Bool)supportsSecureCoding;
+ (id)measurementWithAngle:(double)arg1 uncertainty:(double)arg2;
@property(readonly, nonatomic) double uncertainty; // @synthesize uncertainty=_uncertainty;
@property(readonly, nonatomic) double measurement; // @synthesize measurement=_measurement;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAngle:(double)arg1 uncertainty:(double)arg2;

@end

