//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface GQDArcPath
{
    struct CGSize mSize;
    double mHeadAngle;
    double mArcWidth;
    double mArrowWidth;
    double mArrowLength;
}

- (struct CGPath *)createBezierPath;
- (double)arrowLength;
- (double)arrowWidth;
- (double)arcWidth;
- (double)headAngle;
- (struct CGSize)size;
- (int)readAttributesFromReader:(struct _xmlTextReader *)arg1 processor:(id)arg2;

@end

