//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class GQDTCell;

@interface GQDTPopupCell
{
    GQDTCell *mResultCell;
}

- (id)resultCell;
- (void)dealloc;

@end

