//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface TSTTableSortRowTag : NSObject
{
    unsigned int _rowIndex;
    NSMutableArray *_reorganizeValues;
}

@property(retain, nonatomic) NSMutableArray *reorganizeValues; // @synthesize reorganizeValues=_reorganizeValues;
@property(nonatomic) unsigned int rowIndex; // @synthesize rowIndex=_rowIndex;
- (void).cxx_destruct;
- (id)reorganizeValueAtIndex:(unsigned long long)arg1;
- (void)setReorganizeValue:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)initWithNumberOfSortRules:(unsigned long long)arg1;

@end

