//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSObject.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface TSUUIImageAutoreleasePoolGuard : NSObject
{
    UIImage *mImage;
}

- (void)dealloc;
- (id)initWithUIImage:(id)arg1;

@end

