//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ASOOverlayTransitionContext;

@interface SKOverlayTransitionContext : NSObject
{
    ASOOverlayTransitionContext *_backing;
}

- (void).cxx_destruct;
@property(retain, nonatomic) ASOOverlayTransitionContext *backing; // @synthesize backing=_backing;
- (void)addAnimationBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) struct CGRect endFrame;
@property(readonly, nonatomic) struct CGRect startFrame;
- (id)initWithASOOverlayTransitionContext:(id)arg1;

@end

