//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <PhotosUICore/PXGadgetUIViewController.h>

#import <PhotosUI/UISearchControllerDelegate-Protocol.h>

@class NSString, PUSearchHomeGadgetDataSourceManager, PXProgrammaticNavigationDestination;
@protocol PXViewControllerEventTracker;

@interface PUSearchHomeViewController : PXGadgetUIViewController <UISearchControllerDelegate>
{
    PXProgrammaticNavigationDestination *_px_navigationDestination;
    PUSearchHomeGadgetDataSourceManager *_searchHomeDataSourceManager;
    id <PXViewControllerEventTracker> _searchControllerEventTracker;
}

+ (Class)gadgetSpecClass;
- (void).cxx_destruct;
@property(retain, nonatomic) id <PXViewControllerEventTracker> searchControllerEventTracker; // @synthesize searchControllerEventTracker=_searchControllerEventTracker;
@property(retain, nonatomic) PUSearchHomeGadgetDataSourceManager *searchHomeDataSourceManager; // @synthesize searchHomeDataSourceManager=_searchHomeDataSourceManager;
- (void)didDismissSearchController:(id)arg1;
- (void)didPresentSearchController:(id)arg1;
- (void)ppt_dismissKeyboard;
- (void)ppt_prepareForSearchTest:(CDUnknownBlockType)arg1;
- (void)ppt_prepareForSearchScrollingTestWithSearchText:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)ppt_prepareZeroKeywordRequest:(CDUnknownBlockType)arg1;
- (long long)scrollAnimationIdentifier;
- (void)_notifyAnalyticsSearchAction:(unsigned long long)arg1;
- (void)gadget:(id)arg1 didChange:(unsigned long long)arg2;
- (id)px_navigationDestination;
- (id)nextExistingParticipantOnRouteToDestination:(id)arg1;
- (void)navigateToDestination:(id)arg1 options:(unsigned long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (unsigned long long)routingOptionsForDestination:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)pu_scrollToInitialPositionAnimated:(_Bool)arg1;
- (void)presentSearchWithText:(id)arg1 searchCategory:(unsigned long long)arg2;
- (void)presentForSearchHashtag:(id)arg1;
- (void)presentOneYearAgo;
- (void)presentSpotlightSearch:(id)arg1;
- (void)presentSiriSearchRequest:(id)arg1 resultCount:(unsigned long long)arg2;
- (void)performRecentSearch:(id)arg1;
- (void)selectZeroKeyword:(id)arg1;
- (void)_clearSearchField;
- (void)activateSearchField;
- (void)_configureSearchNavigationBar;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)shouldPreventPlaceholder;
- (void)viewDidLoad;
- (id)init;
- (id)px_gridPresentation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

