//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <HealthHearingDaemon/HDDataObserver-Protocol.h>
#import <HealthHearingDaemon/HDDatabaseProtectedDataObserver-Protocol.h>
#import <HealthHearingDaemon/HDHealthDaemonReadyObserver-Protocol.h>
#import <HealthHearingDaemon/HDQuantitySeriesObserver-Protocol.h>

@class HDHeadphoneAudioExposureCalculatorCache, HDHeadphoneDoseMetadataStore, HDProfile, HKObserverSet, HKSynchronousObserverSet, NSMutableArray, NSString, _HKDelayedOperation;
@protocol OS_dispatch_queue;

@interface HDHeadphoneAudioExposureStatisticsManager : NSObject <HDHealthDaemonReadyObserver, HDDataObserver, HDQuantitySeriesObserver, HDDatabaseProtectedDataObserver>
{
    HDProfile *_profile;
    HDHeadphoneDoseMetadataStore *_keyValueStore;
    struct os_unfair_lock_s _lock;
    NSObject<OS_dispatch_queue> *_queue;
    _Bool _setupInitiated;
    _Bool _enabled;
    _Bool _needsRebuild;
    HDHeadphoneAudioExposureCalculatorCache *_memoryCache;
    HKSynchronousObserverSet *_synchronousObservers;
    HKObserverSet *_observers;
    HDHeadphoneDoseMetadataStore *_metadataStore;
    _HKDelayedOperation *_rebuildCacheOperation;
    NSMutableArray *_pendingSamples;
    CDUnknownBlockType _unitTesting_daemonDidBecomeReady;
    CDUnknownBlockType _unitTesting_didUpdatePreviousSevenDayNotificationFireDate;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType unitTesting_didUpdatePreviousSevenDayNotificationFireDate; // @synthesize unitTesting_didUpdatePreviousSevenDayNotificationFireDate=_unitTesting_didUpdatePreviousSevenDayNotificationFireDate;
@property(copy, nonatomic) CDUnknownBlockType unitTesting_daemonDidBecomeReady; // @synthesize unitTesting_daemonDidBecomeReady=_unitTesting_daemonDidBecomeReady;
- (void)_lock_notifyObserversThatCacheDidUpdate:(id)arg1 suppressUserNotification:(_Bool)arg2 reason:(id)arg3;
- (void)_lock_setNeedsRebuild:(_Bool)arg1;
- (void)_lock_dispatchRebuildIfNeeded;
- (void)_lock_dispatchRebuildImmediatelyIfPossible;
- (void)_lock_setNeedsRebuild;
- (void)_lock_clearNeedsRebuild;
- (_Bool)_lock_updateCacheWithSampleBatch:(id)arg1 error:(id *)arg2;
- (_Bool)_lock_flushPendingSamplesWithError:(id *)arg1;
- (_Bool)_lock_loadCacheWithError:(id *)arg1;
- (id)_lock_loadBucketsFromProfile:(id)arg1 needsRebuild:(_Bool *)arg2 error:(id *)arg3;
- (_Bool)_lock_rebuildWithAssertion:(id)arg1 notifyObservers:(_Bool)arg2 allowInitialQueriesToFail:(_Bool)arg3 resetDoseToZero:(_Bool)arg4 error:(id *)arg5;
- (void)_unitTesting_setNeedsRebuild;
- (void)_unitTesting_lock_clearNeedsRebuild;
- (void)_unitTesting_clearNeedsRebuild;
- (_Bool)_unitTesting_lock_needsRebuild;
- (_Bool)_unitTesting_needsRebuild;
- (id)_unitTesting_pendingSamples;
- (id)_unitTesting_snapshotBuckets;
- (void)_lock_updatePreviousSevenDayNotificationFireDateWithSamplesInserted:(id)arg1 anchor:(id)arg2 assertion:(id)arg3;
- (void)_updatePreviousSevenDayNotificationFireDateWithSamplesInserted:(id)arg1 anchor:(id)arg2;
- (void)_updateCacheWithSampleBatch:(id)arg1;
- (void)_lock_rebuildIfNeededWithAssertion:(id)arg1;
- (void)_rebuildIfNeededWithAssertion:(id)arg1;
- (_Bool)_lock_maintenanceSetupWithAssertion:(id)arg1 error:(id *)arg2;
- (void)_lock_setupIfNeededWithAssertion:(id)arg1;
- (void)_lock_dispatchRebuildForRecentNotificationWithAssertion:(id)arg1 resetDoseToZero:(_Bool)arg2;
- (void)_queue_lock_handleIsEnabledDidChangeWithAssertionAssertion:(id)arg1 initialSetup:(_Bool)arg2;
- (void)_headphoneExposureNotificationsEnabledDidChange:(id)arg1;
- (id)_takeAccessibilityAssertion;
- (void)_dispatchRebuildImmediatelyIfPossible;
- (id)_pruneWithNowDate:(id)arg1 limit:(unsigned long long)arg2 error:(id *)arg3;
- (id)_rebuildWithError:(id *)arg1;
- (CDUnknownBlockType)transactionalQuantityInsertHandlerForProfile:(id)arg1 journaled:(_Bool)arg2 count:(long long)arg3;
- (void)profile:(id)arg1 didDiscardSeriesOfType:(id)arg2;
- (void)samplesOfTypesWereRemoved:(id)arg1 anchor:(id)arg2;
- (void)samplesJournaled:(id)arg1 type:(id)arg2;
- (void)samplesAdded:(id)arg1 anchor:(id)arg2;
- (void)database:(id)arg1 protectedDataDidBecomeAvailable:(_Bool)arg2;
- (void)daemonReady:(id)arg1;
- (void)unregisterSyncronousObserver:(id)arg1;
- (void)registerSynchronousObserver:(id)arg1;
- (void)unregisterObserver:(id)arg1;
- (void)registerObserver:(id)arg1 queue:(id)arg2;
- (void)dealloc;
- (id)_initWithProfile:(id)arg1 keyValueStore:(id)arg2 rebuildDelay:(double)arg3 observers:(id)arg4 synchronousObservers:(id)arg5 daemonDidBecomeReadyHandler:(CDUnknownBlockType)arg6;
- (id)initWithProfile:(id)arg1 keyValueStore:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

