//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <EquationKit/EQKitMathMLNode-Protocol.h>

@interface EQKitMathMLMAlignMark <EQKitMathMLNode>
{
}

- (struct Schemata)layoutSchemata;
- (const void *)mathMLAttributes;
- (id)initFromXMLNode:(struct _xmlNode *)arg1 parser:(id)arg2;

@end

