//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <AssistantServices/AFDictionaryConvertible-Protocol.h>
#import <AssistantServices/NSCopying-Protocol.h>
#import <AssistantServices/NSSecureCoding-Protocol.h>

@class NSString;

@interface AFRequestHandlingContext : NSObject <NSCopying, NSSecureCoding, AFDictionaryConvertible>
{
    NSString *_requestID;
    NSString *_inputDeviceID;
    NSString *_inputAssistantID;
}

+ (_Bool)supportsSecureCoding;
+ (id)newWithBuilder:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *inputAssistantID; // @synthesize inputAssistantID=_inputAssistantID;
@property(readonly, copy, nonatomic) NSString *inputDeviceID; // @synthesize inputDeviceID=_inputDeviceID;
@property(readonly, copy, nonatomic) NSString *requestID; // @synthesize requestID=_requestID;
- (id)buildDictionaryRepresentation;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)_descriptionWithIndent:(unsigned long long)arg1;
@property(readonly, copy) NSString *description;
- (id)initWithRequestID:(id)arg1 inputDeviceID:(id)arg2 inputAssistantID:(id)arg3;
- (id)mutatedCopyWithMutator:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

