//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SAObjects/SASSpeechRecognized.h>

@interface SASSpeechRecognized (AFUserUtteranceAdditions)
- (id)af_bestTextInterpretation;
- (id)af_userUtteranceValue;
@end

