//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <ARKit/ARPassiveSensor-Protocol.h>

@class ARDeviceOrientationData, CMMotionManager, NSString;
@protocol ARSensorDelegate;

@interface ARDeviceOrientationSensor : NSObject <ARPassiveSensor>
{
    CMMotionManager *_motionManager;
    ARDeviceOrientationData *_currentOrientationData;
    id <ARSensorDelegate> _delegate;
    long long _worldAlignment;
}

@property(readonly, nonatomic) long long worldAlignment; // @synthesize worldAlignment=_worldAlignment;
@property(nonatomic) __weak id <ARSensorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)stop;
- (id)currentData;
- (void)start;
- (unsigned long long)providedDataTypes;
- (void)dealloc;
- (id)initWithMotionManager:(id)arg1 alignment:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) unsigned long long powerUsage;
@property(readonly) Class superclass;

@end

