//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIButton.h>

@interface MFComposeSendAccessoryButton : UIButton
{
}

+ (id)buttonWithType:(long long)arg1;
- (void)setEnabled:(_Bool)arg1;

@end

