//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class SASSystemState;

@interface SASRequestOptionsBuilder : NSObject
{
    SASSystemState *_systemState;
    long long _presentationIdentifier;
}

- (void).cxx_destruct;
@property(nonatomic) long long presentationIdentifier; // @synthesize presentationIdentifier=_presentationIdentifier;
@property(retain, nonatomic) SASSystemState *systemState; // @synthesize systemState=_systemState;
- (_Bool)_siriIsEnabled;
- (id)_createRequestOptionsForRequest:(id)arg1 withDataSource:(id)arg2;
- (id)buildOptionsWithRequest:(id)arg1 presentationIdentifier:(long long)arg2 dataSource:(id)arg3;

@end

