//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <HealthRecordServices/NSCopying-Protocol.h>
#import <HealthRecordServices/NSSecureCoding-Protocol.h>

@class HKFHIRVersion, NSData, NSURL;

@interface HDFHIRResourceData : NSObject <NSSecureCoding, NSCopying>
{
    NSData *_data;
    NSURL *_sourceURL;
    HKFHIRVersion *_FHIRVersion;
}

+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
@property(copy, nonatomic) HKFHIRVersion *FHIRVersion; // @synthesize FHIRVersion=_FHIRVersion;
@property(copy, nonatomic) NSURL *sourceURL; // @synthesize sourceURL=_sourceURL;
@property(copy, nonatomic) NSData *data; // @synthesize data=_data;
- (id)debugDescription;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)JSONDictionaryWithError:(id *)arg1;
- (id)initWithData:(id)arg1 sourceURL:(id)arg2 FHIRVersion:(id)arg3;
- (id)init;

@end

