//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <HealthRecordServices/NSCopying-Protocol.h>
#import <HealthRecordServices/NSSecureCoding-Protocol.h>

@class NSString;

@interface HKSignedClinicalDataQRSegment : NSObject <NSCopying, NSSecureCoding>
{
    NSString *_dataValue;
    long long _position;
    long long _numberOfExpectedSiblings;
}

+ (_Bool)supportsSecureCoding;
+ (id)segmentFromQRCodeValue:(id)arg1 error:(id *)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long numberOfExpectedSiblings; // @synthesize numberOfExpectedSiblings=_numberOfExpectedSiblings;
@property(readonly, nonatomic) long long position; // @synthesize position=_position;
@property(readonly, copy, nonatomic) NSString *dataValue; // @synthesize dataValue=_dataValue;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)initWithDataValue:(id)arg1 position:(long long)arg2 numberOfExpectedSiblings:(long long)arg3;
- (id)init;

@end

