//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <SiriVOX/AFDeviceContextConnectionDelegate-Protocol.h>
#import <SiriVOX/SVXModuleInstance-Protocol.h>
#import <SiriVOX/SVXSessionActivityListening-Protocol.h>

@class AFDeviceContextConnection, NSString, SVXDeviceContextAnnouncer, SVXModule;

__attribute__((visibility("hidden")))
@interface SVXSystemObserver : NSObject <SVXModuleInstance, SVXSessionActivityListening, AFDeviceContextConnectionDelegate>
{
    SVXModule *_module;
    SVXDeviceContextAnnouncer *_deviceContextAnnouncer;
    AFDeviceContextConnection *_deviceContextConnection;
}

- (void).cxx_destruct;
- (void)deviceContextConnection:(id)arg1 didUpdateLocalDeviceContext:(id)arg2;
- (void)deviceContextConnectionDidInvalidate:(id)arg1;
- (void)_stopObservingDeviceContext;
- (void)_startObservingDeviceContext;
- (void)_logSnapshot;
- (void)_stopObservingInfo;
- (void)_startObservingInfo;
- (void)audioSessionDidBecomeActive:(_Bool)arg1 activationContext:(id)arg2 deactivationContext:(id)arg3;
- (void)audioSessionWillBecomeActive:(_Bool)arg1 activationContext:(id)arg2 deactivationContext:(id)arg3;
- (void)sessionDidResignActiveWithDeactivationContext:(id)arg1;
- (void)sessionWillResignActiveWithOptions:(unsigned long long)arg1 duration:(double)arg2;
- (void)sessionDidBecomeActiveWithActivationContext:(id)arg1;
- (void)sessionWillBecomeActiveWithActivationContext:(id)arg1;
- (void)sessionDidStopSoundWithID:(long long)arg1 error:(id)arg2;
- (void)sessionDidStartSoundWithID:(long long)arg1;
- (void)sessionWillStartSoundWithID:(long long)arg1;
- (void)sessionWillPresentFeedbackWithDialogIdentifier:(id)arg1;
- (void)sessionDidChangeFromState:(long long)arg1 toState:(long long)arg2;
- (void)sessionWillChangeFromState:(long long)arg1 toState:(long long)arg2;
- (void)stopWithModuleInstanceProvider:(id)arg1;
- (void)startWithModuleInstanceProvider:(id)arg1 platformDependencies:(id)arg2;
- (void)dealloc;
- (id)initWithModule:(id)arg1;
- (void)getLocalDeviceContextWithCompletion:(CDUnknownBlockType)arg1;
- (void)removeDeviceContextListener:(id)arg1;
- (void)addDeviceContextListener:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

