//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MediaControls/CCUIContentModuleContentViewController-Protocol.h>
#import <MediaControls/MPAVRoutingViewControllerDelegate-Protocol.h>
#import <MediaControls/MediaControlsPanelViewControllerDelegate-Protocol.h>

@class MPMediaControlsConfiguration, NSString, _MediaControlsEndpointsDataSource;

@interface MediaControlsEndpointsViewController <MPAVRoutingViewControllerDelegate, MediaControlsPanelViewControllerDelegate, CCUIContentModuleContentViewController>
{
    _Bool _dismissing;
    MPMediaControlsConfiguration *_configuration;
    CDUnknownBlockType _launchNowPlayingAppBlock;
    CDUnknownBlockType _routingCornerViewTappedBlock;
    _MediaControlsEndpointsDataSource *_pickerDataSource;
}

@property(nonatomic, getter=isDismissing) _Bool dismissing; // @synthesize dismissing=_dismissing;
@property(retain, nonatomic) _MediaControlsEndpointsDataSource *pickerDataSource; // @synthesize pickerDataSource=_pickerDataSource;
@property(copy, nonatomic) CDUnknownBlockType routingCornerViewTappedBlock; // @synthesize routingCornerViewTappedBlock=_routingCornerViewTappedBlock;
@property(copy, nonatomic) CDUnknownBlockType launchNowPlayingAppBlock; // @synthesize launchNowPlayingAppBlock=_launchNowPlayingAppBlock;
@property(retain, nonatomic) MPMediaControlsConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (void)routingViewController:(id)arg1 didPickRoute:(id)arg2;
- (void)mediaControlsPanelViewController:(id)arg1 didToggleRoutingPicker:(_Bool)arg2;
- (void)launchNowPlayingApp:(id)arg1;
- (void)_didSelectRoute;
- (id)_createOrReuseViewController;
@property(readonly, nonatomic) _Bool providesOwnPlatter;
@property(readonly, nonatomic) double preferredExpandedContentWidth;
@property(readonly, nonatomic) double preferredExpandedContentHeight;
- (id)dataSource;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

