//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMutableArray, NSSet;

@interface NSSaveChangesRequest
{
    NSSet *_insertedObjects;
    NSSet *_updatedObjects;
    NSSet *_deletedObjects;
    NSSet *_optimisticallyLockedObjects;
    unsigned long long _flags;
    NSMutableArray *_mutatedObjectIDsNotifications;
}

+ (void)initialize;
- (unsigned long long)requestType;
- (id)description;
@property(readonly) NSSet *lockedObjects;
@property(readonly) NSSet *deletedObjects;
@property(readonly) NSSet *updatedObjects;
@property(readonly) NSSet *insertedObjects;
- (id)init;
- (void)dealloc;
- (id)initWithInsertedObjects:(id)arg1 updatedObjects:(id)arg2 deletedObjects:(id)arg3 lockedObjects:(id)arg4;
- (_Bool)_secureOperation;
- (void)_setSecureOperation:(_Bool)arg1;

@end

