//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AAPasswordSecurityUIRequest
{
    unsigned long long _spyglassOptionMask;
}

@property(nonatomic) unsigned long long spyglassOptionMask; // @synthesize spyglassOptionMask=_spyglassOptionMask;
- (id)urlRequest;
- (id)urlString;

@end

