//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface AASecondaryAuthenticationRequest
{
    NSString *_primaryToken;
    NSString *_dsid;
}

+ (Class)responseClass;
- (void).cxx_destruct;
- (id)urlRequest;
- (id)urlString;
- (id)initWithDSID:(id)arg1 primaryToken:(id)arg2;

@end

