//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class FTAStarFuzzyMatchingConfig, NSData, NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface FTAStarFuzzyMatchingRequest : NSObject
{
    NSMutableDictionary *_storage;
    NSData *_data;
    const struct AStarFuzzyMatchingRequest *_root;
}

- (void).cxx_destruct;
- (id)flatbuffData;
- (Offset_0c0a1494)addObjectToBuffer:(void *)arg1;
@property(readonly, nonatomic) FTAStarFuzzyMatchingConfig *config;
@property(readonly, nonatomic) NSString *target;
@property(readonly, nonatomic) NSString *query;
@property(readonly, nonatomic) NSString *session_id;
@property(readonly, nonatomic) NSString *matcher_id;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithFlatbuffData:(id)arg1 root:(const struct AStarFuzzyMatchingRequest *)arg2 verify:(_Bool)arg3;
- (id)initWithFlatbuffData:(id)arg1 root:(const struct AStarFuzzyMatchingRequest *)arg2;
- (id)initAndVerifyWithFlatbuffData:(id)arg1;
- (id)initWithFlatbuffData:(id)arg1;

@end

