//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <TrialServer/TRIDateProviding-Protocol.h>

@class NSMutableDictionary, TRIKVStore;

@interface TRIExperimentFetchDateManager : NSObject <TRIDateProviding>
{
    TRIKVStore *_keyValueStore;
    NSMutableDictionary *_cachedLastFetchExperimentDates;
}

+ (id)managerWithKeyValueStore:(id)arg1;
+ (id)kvstoreKeyForContainer:(int)arg1 teamId:(id)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSMutableDictionary *cachedLastFetchExperimentDates; // @synthesize cachedLastFetchExperimentDates=_cachedLastFetchExperimentDates;
@property(readonly, nonatomic) TRIKVStore *keyValueStore; // @synthesize keyValueStore=_keyValueStore;
- (void)updateLastFetchExperimentDate:(id)arg1 forContainer:(int)arg2 teamId:(id)arg3;
- (id)lastFetchExperimentDateForContainer:(int)arg1 teamId:(id)arg2;
- (id)initWithKeyValueStore:(id)arg1;

@end

