//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

#import <CoreEmbeddedSpeechRecognition/NSSecureCoding-Protocol.h>

@class NSArray, NSDictionary, NSString;

@interface CESRUserData : NSObject <NSSecureCoding>
{
    NSString *_language;
    NSArray *_contactWordsWithFrequency;
    NSDictionary *_vocabularyWords;
    NSArray *_appNames;
    NSDictionary *_interactionSenderDisplayNames;
    NSDictionary *_searchEventValues;
    NSArray *_locationOfInterestNames;
    NSArray *_spatialLocationOfInterestNames;
    NSArray *_eventTitles;
    NSArray *_eventLocationNames;
    NSDictionary *_keyboardLMDynamicVocabularyItems;
    NSArray *_pexNamedEntityNames;
    NSArray *_corrections;
}

+ (_Bool)supportsSecureCoding;
+ (void)fetchUserDataWithLanguage:(id)arg1 options:(id)arg2 keepGoing:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)fetchUserDataWithLanguage:(id)arg1 options:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (id)_fetchFromMediaPlayerWithKeepGoing:(CDUnknownBlockType)arg1;
+ (void)_fetchFromSiriKitWithKeepGoing:(CDUnknownBlockType)arg1 contactNames:(id *)arg2 contactGroupNames:(id *)arg3 vocabularyWords:(id *)arg4;
- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *corrections; // @synthesize corrections=_corrections;
@property(copy, nonatomic) NSArray *pexNamedEntityNames; // @synthesize pexNamedEntityNames=_pexNamedEntityNames;
@property(copy, nonatomic) NSDictionary *keyboardLMDynamicVocabularyItems; // @synthesize keyboardLMDynamicVocabularyItems=_keyboardLMDynamicVocabularyItems;
@property(copy, nonatomic) NSArray *eventLocationNames; // @synthesize eventLocationNames=_eventLocationNames;
@property(copy, nonatomic) NSArray *eventTitles; // @synthesize eventTitles=_eventTitles;
@property(copy, nonatomic) NSArray *spatialLocationOfInterestNames; // @synthesize spatialLocationOfInterestNames=_spatialLocationOfInterestNames;
@property(copy, nonatomic) NSArray *locationOfInterestNames; // @synthesize locationOfInterestNames=_locationOfInterestNames;
@property(copy, nonatomic) NSDictionary *searchEventValues; // @synthesize searchEventValues=_searchEventValues;
@property(copy, nonatomic) NSDictionary *interactionSenderDisplayNames; // @synthesize interactionSenderDisplayNames=_interactionSenderDisplayNames;
@property(copy, nonatomic) NSArray *appNames; // @synthesize appNames=_appNames;
@property(copy, nonatomic) NSDictionary *vocabularyWords; // @synthesize vocabularyWords=_vocabularyWords;
@property(copy, nonatomic) NSArray *contactWordsWithFrequency; // @synthesize contactWordsWithFrequency=_contactWordsWithFrequency;
@property(readonly, copy, nonatomic) NSString *language; // @synthesize language=_language;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)debugDescription;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)_fetchEventKitWithKeepGoing:(CDUnknownBlockType)arg1;
- (void)_fetchCorrectionsWithKeepGoing:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_fetchDynamicKeyboardLanguageModelWithKeepGoing:(CDUnknownBlockType)arg1;
- (void)_fetchCoreRoutineWithKeepGoing:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_fetchCoreDuetSearchEventsWithKeepGoing:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_fetchCoreDuetInteractionsWithKeepGoing:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_fetchAppsWithKeepGoing:(CDUnknownBlockType)arg1;
- (void)_fetchPortraitWithKeepGoing:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (id)_fetchHomeKitVocabularyWithKeepGoing:(CDUnknownBlockType)arg1;
- (void)_fetchContactsAndSiriKitWithKeepGoing:(CDUnknownBlockType)arg1 options:(id)arg2 vocabularyWords:(id *)arg3;
- (void)_fetchContactsWithKeepGoing:(CDUnknownBlockType)arg1 options:(id)arg2 siriKitContactNames:(id)arg3 siriKitContactGroupNames:(id)arg4;
- (id)_fetchRankedContactIDsWithPSContactSuggester:(id)arg1 UpTo:(unsigned long long)arg2;
- (id)_initWithLanguage:(id)arg1;

@end

