//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MFRangedDataFilter
{
    struct _NSRange _range;
    unsigned long long _consumedLength;
}

+ (id)rangedFilterWithConsumer:(id)arg1 range:(struct _NSRange)arg2;
+ (id)rangedFilterWithConsumers:(id)arg1 range:(struct _NSRange)arg2;
@property(nonatomic) struct _NSRange range; // @synthesize range=_range;
- (long long)appendData:(id)arg1;

@end

