//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray;

@interface IBICSyncResult : NSObject
{
    NSMutableArray *_errors;
    NSMutableArray *_issues;
}

- (void).cxx_destruct;
@property(readonly) NSArray *issues; // @synthesize issues=_issues;
@property(readonly) NSArray *errors; // @synthesize errors=_errors;
- (id)description;
- (void)addIssues:(id)arg1;
- (void)addIssue:(id)arg1;
- (void)addErrors:(id)arg1;
- (void)addError:(id)arg1;
- (id)init;

@end

