//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Home/HFAccessoryProfileFiltering-Protocol.h>
#import <Home/HFAccessoryProfileGrouping-Protocol.h>

@class HFAccessoryProfileFilterOptions, HFAccessoryProfileGroupOptions, HMHome, NSMutableSet, NSString;

@interface HFAccessoryProfileGroupItemProvider <HFAccessoryProfileFiltering, HFAccessoryProfileGrouping>
{
    HFAccessoryProfileFilterOptions *_filterOptions;
    HFAccessoryProfileGroupOptions *_groupOptions;
    HMHome *_home;
    NSMutableSet *_profileGroupItems;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableSet *profileGroupItems; // @synthesize profileGroupItems=_profileGroupItems;
@property(readonly, nonatomic) HMHome *home; // @synthesize home=_home;
@property(retain, nonatomic) HFAccessoryProfileGroupOptions *groupOptions; // @synthesize groupOptions=_groupOptions;
@property(retain, nonatomic) HFAccessoryProfileFilterOptions *filterOptions; // @synthesize filterOptions=_filterOptions;
- (id)_profileGroupItemForProfiles:(id)arg1 groupIdentifier:(id)arg2;
- (id)_supportedProfileClasses;
- (id)invalidationReasons;
- (id)items;
- (id)reloadItems;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)initWithHome:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

