//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface HFSubstringNaturalLanguageOptions
{
    long long _formattingContext;
    long long _formattingStyle;
}

@property(nonatomic) long long formattingStyle; // @synthesize formattingStyle=_formattingStyle;
@property(nonatomic) long long formattingContext; // @synthesize formattingContext=_formattingContext;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithFormattingContext:(long long)arg1 formattingStyle:(long long)arg2;

@end

