//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Home/HFConditionItem-Protocol.h>

@class HFTimeCondition, NSString;

@interface HFTimeConditionItem <HFConditionItem>
{
    HFTimeCondition *_condition;
    unsigned long long _type;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) HFTimeCondition *condition; // @synthesize condition=_condition;
- (id)_subclass_updateWithOptions:(id)arg1;
- (id)initWithConditionType:(unsigned long long)arg1 condition:(id)arg2;
- (id)initWithConditionType:(unsigned long long)arg1;
- (id)initWithCondition:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

