//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <HomeKit/HMAccessoryCollectionSettingItem.h>

@interface HMAccessoryCollectionSettingItem (HFAlarmUtilities)
+ (id)hf_alarmItemsMatchingAlarmId:(id)arg1 withinItemArray:(id)arg2;
+ (id)hf_collectionSettingItemForAlarm:(id)arg1;
@end

