//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class SUUIEmbeddedMediaView, SUUIMediaComponent;

__attribute__((visibility("hidden")))
@interface SUUIGalleryPaneViewController : UIViewController
{
    SUUIMediaComponent *_component;
    long long _galleryIndex;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) long long galleryIndex; // @synthesize galleryIndex=_galleryIndex;
@property(readonly, nonatomic) SUUIMediaComponent *component; // @synthesize component=_component;
@property(readonly, nonatomic) SUUIEmbeddedMediaView *mediaView;
- (id)initWithMediaComponent:(id)arg1 galleryIndex:(long long)arg2;

@end

