//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <RemoteUI/RUITableViewRow.h>

@class NSLock, UITableViewCell;

@interface ICQCloudStorageGraphTableViewRow : RUITableViewRow
{
    NSLock *_tableCellLock;
    UITableViewCell *_tableCell;
}

- (void).cxx_destruct;
- (float)rowHeightWithMax:(float)arg1 peggedHeight:(float)arg2 tableView:(id)arg3 indexPath:(id)arg4;
- (id)tableCell;
- (id)init;

@end

