//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class HKHealthStore;

@interface HKHRCardioFitnessAnalyticsClientSignalSource
{
    HKHealthStore *_healthStore;
}

- (void).cxx_destruct;
- (id)biologicalSexStringWithError:(id *)arg1;
- (long long)bucketedAgeWithError:(id *)arg1;
- (id)initWithHealthStore:(id)arg1;

@end

