//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MLModel, MLModelConfiguration, NSArray, NSDictionary, NSString, _PSBehaviorRuleFeatureExtraction;

@interface _PSRuleRankingMLModel : NSObject
{
    _Bool _isAdaptedModel;
    _Bool _isAdaptedMLModelOK;
    double _scoreThreshold;
    NSArray *_scores;
    MLModel *_mlModel;
    NSDictionary *_metadata;
    NSDictionary *_psConfigForAdaptableModel;
    MLModelConfiguration *_adaptableModelConfiguration;
    NSString *_adaptedModelRecipeVersion;
    _PSBehaviorRuleFeatureExtraction *_feaExtHandle;
}

- (void).cxx_destruct;
@property(retain) _PSBehaviorRuleFeatureExtraction *feaExtHandle; // @synthesize feaExtHandle=_feaExtHandle;
@property(retain) NSString *adaptedModelRecipeVersion; // @synthesize adaptedModelRecipeVersion=_adaptedModelRecipeVersion;
@property(nonatomic) _Bool isAdaptedMLModelOK; // @synthesize isAdaptedMLModelOK=_isAdaptedMLModelOK;
@property(retain, nonatomic) MLModelConfiguration *adaptableModelConfiguration; // @synthesize adaptableModelConfiguration=_adaptableModelConfiguration;
@property(retain) NSDictionary *psConfigForAdaptableModel; // @synthesize psConfigForAdaptableModel=_psConfigForAdaptableModel;
@property _Bool isAdaptedModel; // @synthesize isAdaptedModel=_isAdaptedModel;
@property(retain) NSDictionary *metadata; // @synthesize metadata=_metadata;
@property(retain) MLModel *mlModel; // @synthesize mlModel=_mlModel;
@property(retain, nonatomic) NSArray *scores; // @synthesize scores=_scores;
@property double scoreThreshold; // @synthesize scoreThreshold=_scoreThreshold;
- (id)rankRules:(id)arg1 contextItems:(id)arg2;
- (id)scoresOnRules:(id)arg1 contextItems:(id)arg2;
- (id)giveModelDescription;
- (id)extractAdaptedModelRecipeID;
- (_Bool)isAdaptedModelUsed;
- (_Bool)isAdaptedModelCreated;
- (void)loadDefaultRuleMinerMLModel;
- (id)getAdaptedModelVersion;
- (id)initWithAdaptableModelConfig:(id)arg1 isAdaptedMLModelOK:(_Bool)arg2 scoreThreshold:(double)arg3;
- (id)initWithMLModel:(id)arg1 scoreThreshold:(double)arg2 isAdaptedModel:(_Bool)arg3 psConfigForAdaptableModel:(id)arg4 isAdaptedMLModelOK:(_Bool)arg5;

@end

