//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class _CDInteraction;

@interface _PSSharingContactRankerScoredContact : NSObject
{
    double _score;
    _CDInteraction *_interaction;
}

- (void).cxx_destruct;
@property(retain, nonatomic) _CDInteraction *interaction; // @synthesize interaction=_interaction;
@property(nonatomic) double score; // @synthesize score=_score;
- (id)initWithScore:(double)arg1 interaction:(id)arg2;

@end

