//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray;

@interface HRECharacteristicTriggerTemplate
{
    _Bool _characteristicPerServiceRule;
    _Bool _enforcePriority;
    _Bool _singleRecommendationPerSplit;
    _Bool _allowMultipleEventsFeature;
    NSArray *_triggerCharacteristicValues;
    NSArray *_characteristicTypePriority;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool allowMultipleEventsFeature; // @synthesize allowMultipleEventsFeature=_allowMultipleEventsFeature;
@property(nonatomic) _Bool singleRecommendationPerSplit; // @synthesize singleRecommendationPerSplit=_singleRecommendationPerSplit;
@property(nonatomic) _Bool enforcePriority; // @synthesize enforcePriority=_enforcePriority;
@property(nonatomic) _Bool characteristicPerServiceRule; // @synthesize characteristicPerServiceRule=_characteristicPerServiceRule;
@property(retain, nonatomic) NSArray *characteristicTypePriority; // @synthesize characteristicTypePriority=_characteristicTypePriority;
@property(retain, nonatomic) NSArray *triggerCharacteristicValues; // @synthesize triggerCharacteristicValues=_triggerCharacteristicValues;
- (id)_subclass_triggerBuilderForRecommendation:(id)arg1 withObjects:(id)arg2;
- (id)init;

@end

