//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSData, NSString, VCPPhotosFace;

__attribute__((visibility("hidden")))
@interface VCPFaceCrop : NSObject
{
    NSData *_faceCropData;
    VCPPhotosFace *_originatingFace;
    struct CGSize _cachedImageDimensions;
    short _state;
    NSString *_localIdentifier;
}

- (void).cxx_destruct;
@property(nonatomic) short state; // @synthesize state=_state;
@property(readonly, copy, nonatomic) NSString *localIdentifier; // @synthesize localIdentifier=_localIdentifier;
- (id)description;
- (struct CGSize)imageDimensions;
- (id)originatingFace;
- (id)faceCropData;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithFaceCropData:(id)arg1 originatingFace:(id)arg2;
- (id)initWithLocalIdentifier:(id)arg1 faceCropData:(id)arg2;

@end

