//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface VKRunningCurve : NSObject
{
    CDStruct_a199e3d1 _p0;
    double _t0;
    CDStruct_a199e3d1 _p1;
    double _t1;
    CDStruct_a199e3d1 _pu;
    double _tu;
    struct {
        double mb[4][3];
    } _mb;
    _Bool _mbValid;
}

- (id).cxx_construct;
- (CDStruct_a199e3d1)stateAtTime:(double)arg1;
- (_Bool)hasStateAtTime:(double)arg1;
- (void)appendPosition:(Matrix_6e1d3589)arg1 atTime:(double)arg2;
- (void)dealloc;
- (void)reset;
- (id)init;

@end

