//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

#import <CloudPhotoLibrary/NSCopying-Protocol.h>

@class NSString;

@interface CPLSuggestionMemory : PBCodable <NSCopying>
{
    NSString *_context;
    unsigned int _feature;
    NSString *_memoryIdentifier;
    unsigned int _type;
    CDStruct_35f57793 _has;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *context; // @synthesize context=_context;
@property(nonatomic) unsigned int feature; // @synthesize feature=_feature;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *memoryIdentifier; // @synthesize memoryIdentifier=_memoryIdentifier;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(readonly, nonatomic) _Bool hasContext;
@property(nonatomic) _Bool hasFeature;
@property(nonatomic) _Bool hasType;
@property(readonly, nonatomic) _Bool hasMemoryIdentifier;

@end

