//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface CPLTransaction : NSObject
{
    _Bool _dirty;
    NSString *_identifier;
}

+ (id)newTransactionWithIdentifier:(id)arg1 description:(id)arg2 keepPower:(_Bool)arg3;
+ (unsigned long long)transactionCount;
+ (id)transactions;
+ (void)endTransactionWithIdentifier:(id)arg1;
+ (void)beginTransactionWithIdentifier:(id)arg1 description:(id)arg2 keepPower:(_Bool)arg3;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)dealloc;
- (void)endTransaction;
- (id)initWithIdentifier:(id)arg1 description:(id)arg2 keepPower:(_Bool)arg3;

@end

