//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

#import <NanoMailKitServer/NSCopying-Protocol.h>

@class NSString;

@interface NNMKProtoMessageStatusUpdate : PBCodable <NSCopying>
{
    NSString *_messageId;
    unsigned int _statusVersion;
    unsigned int _updatedStatus;
    struct {
        unsigned int statusVersion:1;
        unsigned int updatedStatus:1;
    } _has;
}

@property(nonatomic) unsigned int statusVersion; // @synthesize statusVersion=_statusVersion;
@property(nonatomic) unsigned int updatedStatus; // @synthesize updatedStatus=_updatedStatus;
@property(retain, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
- (void).cxx_destruct;
- (void)mergeFrom:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyTo:(id)arg1;
- (void)writeTo:(id)arg1;
- (_Bool)readFrom:(id)arg1;
- (id)dictionaryRepresentation;
- (id)description;
@property(nonatomic) _Bool hasStatusVersion;
@property(nonatomic) _Bool hasUpdatedStatus;
@property(readonly, nonatomic) _Bool hasMessageId;

@end

