//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <DVTFoundation/NSObject-Protocol.h>

@class NSDictionary, NSMutableDictionary;

@protocol DVTPropertyListEncoding <NSObject>
- (void)encodeIntoPropertyList:(NSMutableDictionary *)arg1;
- (id)initWithPropertyList:(NSDictionary *)arg1 owner:(id)arg2;
@end

