//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray;

@interface FIUIWorkoutSummaryCompoundOption
{
    unsigned long long _compoundPredicateType;
    NSArray *_subOptions;
}

- (void).cxx_destruct;
- (_Bool)evaluateWithWorkout:(id)arg1 supportedMetrics:(id)arg2;
- (id)initWithRowType:(unsigned long long)arg1 compoundPredicateType:(unsigned long long)arg2 subOptions:(id)arg3;

@end

