//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MPSCore/MPSState.h>

@class MPSMatrix;

@interface MPSRNNMatrixTrainingState : MPSState
{
    MPSMatrix *singleGateZ;
    _Bool _isTemporary;
}

- (_Bool)isTemporary;
- (void)setReadCount:(unsigned long long)arg1;
- (void)dealloc;
- (id)initForSingleGateWithCommandBuffer:(id)arg1 matrixDescriptor:(id)arg2 isTemporary:(_Bool)arg3;

@end

