//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

__attribute__((visibility("hidden")))
@interface MCMContainerClassDeletedPath
{
}

+ (id)_posixOwnerForDeletedPathForContainerClass:(unsigned long long)arg1 user:(id)arg2;
+ (id)_deletedComponent;
+ (id)deletedURLWithUserIdentity:(id)arg1;
+ (id)deletedGlobalURL;
+ (id)containerPathForUserIdentity:(id)arg1 containerClass:(unsigned long long)arg2;

@end

