//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, RPCompanionLinkClient, RPCompanionLinkDevice;

@interface HUNearbyDevice : NSObject
{
    _Bool _activating;
    _Bool _shouldTrack;
    RPCompanionLinkDevice *_device;
    unsigned long long _connectionStatus;
    RPCompanionLinkClient *_client;
    NSMutableDictionary *_previousMessageCache;
}

+ (id)nearbyDeviceWithPeerDevice:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *previousMessageCache; // @synthesize previousMessageCache=_previousMessageCache;
@property(nonatomic) _Bool shouldTrack; // @synthesize shouldTrack=_shouldTrack;
@property(nonatomic, getter=isActivating) _Bool activating; // @synthesize activating=_activating;
@property(retain) RPCompanionLinkClient *client; // @synthesize client=_client;
@property(nonatomic) unsigned long long connectionStatus; // @synthesize connectionStatus=_connectionStatus;
@property(retain, nonatomic) RPCompanionLinkDevice *device; // @synthesize device=_device;
- (void).cxx_destruct;
- (void)sendMessage:(id)arg1;
- (void)purgeMessageCache;
- (void)setupSessionIfNecessary;
- (void)stop;
- (void)reset;
- (id)description;
- (_Bool)representsAWatch;
- (_Bool)representsPeerDevice:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)identifier;
- (id)name;
- (void)dealloc;
- (id)initWithPeerDevice:(id)arg1;

@end

