//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class HMDBackingStoreCacheGroup, NSArray, NSString, NSUUID;

__attribute__((visibility("hidden")))
@interface HMDBackingStoreCacheFetchModelObjects
{
    HMDBackingStoreCacheGroup *_group;
    CDUnknownBlockType _fetchResult;
    NSArray *_uuids;
    NSArray *_names;
    NSUUID *_parent;
    NSString *_type;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSUUID *parent; // @synthesize parent=_parent;
@property(retain, nonatomic) NSArray *names; // @synthesize names=_names;
@property(retain, nonatomic) NSArray *uuids; // @synthesize uuids=_uuids;
@property(copy, nonatomic) CDUnknownBlockType fetchResult; // @synthesize fetchResult=_fetchResult;
@property(retain, nonatomic) HMDBackingStoreCacheGroup *group; // @synthesize group=_group;
- (id)mainReturningError;
- (id)initWithGroup:(id)arg1 parent:(id)arg2 type:(id)arg3 fetchResult:(CDUnknownBlockType)arg4;
- (id)initWithParent:(id)arg1 type:(id)arg2 fetchResult:(CDUnknownBlockType)arg3;
- (id)initWithGroup:(id)arg1 names:(id)arg2 fetchResult:(CDUnknownBlockType)arg3;
- (id)initWithNames:(id)arg1 fetchResult:(CDUnknownBlockType)arg2;
- (id)initWithGroup:(id)arg1 uuids:(id)arg2 fetchResult:(CDUnknownBlockType)arg3;
- (id)initWithUUIDs:(id)arg1 fetchResult:(CDUnknownBlockType)arg2;

@end

