//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <HMFoundation/HMFObject.h>

#import <HomeKitDaemon/HMDLogEventDataSyncStateContext-Protocol.h>

@class HMFUnfairLock, NSString;

@interface HMDCloudSyncLogEventDataSyncStateManager : HMFObject <HMDLogEventDataSyncStateContext>
{
    HMFUnfairLock *_lock;
    _Bool _firstDataSyncEventReceived;
    unsigned long long _dataSyncState;
}

+ (id)currentContext;
- (void).cxx_destruct;
@property _Bool firstDataSyncEventReceived; // @synthesize firstDataSyncEventReceived=_firstDataSyncEventReceived;
@property(setter=updateWithDataSyncState:) unsigned long long dataSyncState; // @synthesize dataSyncState=_dataSyncState;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

