//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <HMFoundation/HMFObject.h>

@class HMDHome, HMFMessageDispatcher, NSMutableDictionary, NSObject, NSString, NSUUID;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface HMDRemoteMessageForwarder : HMFObject
{
    HMDHome *_home;
    HMFMessageDispatcher *_messageDispatcher;
    NSUUID *_UUID;
    NSUUID *_contextUUID;
    NSObject<OS_dispatch_queue> *_workQueue;
    NSMutableDictionary *_messagesByIdentifier;
}

+ (id)logCategory;
+ (id)remoteMessageForwarderUUIDFromUUID:(id)arg1;
- (void).cxx_destruct;
@property(readonly) NSMutableDictionary *messagesByIdentifier; // @synthesize messagesByIdentifier=_messagesByIdentifier;
@property(readonly) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(readonly, copy) NSUUID *contextUUID; // @synthesize contextUUID=_contextUUID;
@property(readonly, copy) NSUUID *UUID; // @synthesize UUID=_UUID;
@property(readonly) HMFMessageDispatcher *messageDispatcher; // @synthesize messageDispatcher=_messageDispatcher;
@property(readonly) __weak HMDHome *home; // @synthesize home=_home;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *messageReceiveQueue;
@property(readonly, nonatomic) NSUUID *messageTargetUUID;
- (void)handleResponseMessage:(id)arg1;
- (id)messageForForwardedMessage:(id)arg1;
- (void)redispatchToResidentMessage:(id)arg1;
- (void)configureWithMessageDispatcher:(id)arg1;
- (id)initWithHome:(id)arg1 UUID:(id)arg2 workQueue:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

