//
//     Generated by classdump-c 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, NSUUID;
@protocol HMDSiriEndpointProfileMessageHandlerDataSource;

__attribute__((visibility("hidden")))
@interface HMDSiriEndpointProfileMessageHandler : NSObject
{
    id <HMDSiriEndpointProfileMessageHandlerDataSource> _dataSource;
    NSUUID *_homeUUID;
}

+ (id)logCategory;
- (void).cxx_destruct;
@property(readonly, copy) NSUUID *homeUUID; // @synthesize homeUUID=_homeUUID;
@property __weak id <HMDSiriEndpointProfileMessageHandlerDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (id)logIdentifier;
- (id)dataSourceHubAccessories;
- (id)dataSourceSiriEndpointOnboardingManager;
- (id)deleteHistoryForAccessoryUUID:(id)arg1 onHubAccessory:(id)arg2;
- (id)deleteHistoryForAccessoryUUID:(id)arg1 onHubAccessories:(id)arg2;
- (void)handleSiriEndpointDeleteSiriHistoryRequestMessage:(id)arg1;
- (void)handleSiriEndpointApplyOnboardingSelectionsRequestMessage:(id)arg1;
- (id)initWithHomeUUID:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

